### PR TITLE
Show attached images

### LINKED ISSUE #1053: Directly embed linked images and videos
Will make for a way smoother experience.

### PR DESCRIPTION
**Pull request by jakobsack**
Show images attached to the mail below the text. 

Please test with mails with 

1. 8+ images attached
2. some images and some documents attached
3. no images and some documents attached

For some reason not all images of the first email are loaded when the mail app is opened. I can not find the reason for this behavior. After loading another mail everything works fine.

Fixes #1053, cc @jancborchardt  @jospoortvliet  @ChristophWurst @Gomez

### CODE REVIEW

**Comment by Gomez** [comment]
Wow, this is super awesome! 
If i add a huge image (4k), i cant scroll right. We should scale the images, or open big pictures in a new tab?

**Comment by jakobsack** [comment]
Scaling should be done on client side in javascript. I'll see what I can do.

**Comment by jancborchardt** [comment]
If the images are too big, scale them to fit the width of the viewport (that is, the message detail width). Smaller pictures should not be enlarged.

And on click we could show the original separately (as to zoom in), if that’s possible. Or we utilize the Gallery slideshow view, that’d be awesome integration! cc @oparoz

**Comment by oparoz** [comment]
Gallery could have a /slideshow endpoint sending everything needed to launch the slideshow, but you will create a dependency. On the plus side, it means users always get the same viewers and at some point it could work with videos as well.

**Comment by jancborchardt** [comment]
Yeah, it would be an optional »dependency« – more of an enhancement. :)

**Comment by jakobsack** [comment]
Hey everyone, I've just updated this branch. Attached images now have a maximal width.

I'd like to merge this pull request soon, advanced features could be added in new ones.

**Comment by Gomez** [comment]
Superb work! Tested and works fine!
Just a PHPUnit error todo and another review pls:
@enoch85 @jancborchardt @ChristophWurst @irgendwie

**Comment by jakobsack** [comment]
@Gomez Fixed the error

**Comment by Gomez** [comment]
As @jancborchardt would say: "Squash the commits" and we are good to go :P
Another Review pls? @ChristophWurst @irgendwie @enoch85

**Comment by ChristophWurst** [comment]
This is tagged as 0.4 – should we get this into 0.3 or leave it open?

**Comment by jakobsack** [comment]
I don't see a reason to wait for 0.4. If it's done it's done.

**Comment by enoch85** [comment]
Agree with @jakobsack --^

**Comment by enoch85** [comment]
@PoPoutdoor Could you help testing this?

**Comment by irgendwie** [comment]
Nice work!
LGTM :+1:

**Comment by jancborchardt** [comment]
Oi, next time squash the commits please. ;)

**Pull request merged**
