### PR TITLE
Fix Content Security Policy for frame-src

### PR DESCRIPTION
**Pull request by Spacefish**
To make HTML mails work again in Owncloud 8.1

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
@LukasReschke THX

**Comment by LukasReschke** [comment]
:+1: – though the fact that the tests do still pass mean we probably have no unit tests for this function :)

**Comment by DeepDiver1975** [comment]
:+1:

**Comment by Spacefish** [comment]
@LukasReschke  yeah looks like it :) i saw Core has a lot of Unit Tests arround Content-Security things. But Mail doesn´t

**Pull request merged**
