### PR TITLE
Increase test coverage 2

### PR DESCRIPTION
**Pull request by DeepDiver1975**

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
That's really funny - the tests fail when php 5.5 and 5.6 are connecting with gmail

**Comment by Xenopathic** [comment]
:+1: Can we roll this through ASAP? Seems like master is broken without the default parameter change. The other tests work fine.

**Comment by DeepDiver1975** [comment]
I only want to merge a green travis status - let's go for php 5.4 only for now

**Comment by jancborchardt** [comment]
Coverage up to 66%! Can we go to 100% for the release? ;)

**Comment by DeepDiver1975** [comment]
> Coverage up to 66%! Can we go to 100% for the release? ;)

ehhh-no

**Pull request merged**
