### PR TITLE
Fix undefined index - fixes #656

### LINKED ISSUE #656: Errors while adding mail from contact in adressbook
### Steps to reproduce

1. Write a new message
2. Add an email adress that's existing in your contacts

**EDIT** Tried again and it doesn't show the same errors. Maybe it's something else. Anyway, the undefined index EMAIL should be fixed.

### Actual behaviour

It works, but I get this messages in log.

```
Error	PHP	Undefined index: REQUEST_URI at /var/www/owncloud/apps/calendar/appinfo/app.php#41	2015-05-11T19:45:01+00:00
Error	PHP	Undefined offset: 0 at /var/www/owncloud/apps/contacts/lib/backend/shared.php#90	2015-05-11T19:44:58+00:00
Error	PHP	Undefined index: EMAIL at /var/www/owncloud/apps/mail/lib/service/contactsintegration.php#41	2015-05-11T19:44:57+00:00
Error	PHP	Undefined index: EMAIL at /var/www/owncloud/apps/mail/lib/service/contactsintegration.php#41	2015-05-11T19:44:57+00:00
Error	PHP	Undefined index: EMAIL at /var/www/owncloud/apps/mail/lib/service/contactsintegration.php#41	2015-05-11T19:44:57+00:00
Error	PHP	Undefined index: EMAIL at /var/www/owncloud/apps/mail/lib/service/contactsintegration.php#41	2015-05-11T19:44:57+00:00
Error	PHP	Undefined offset: 0 at /var/www/owncloud/apps/contacts/lib/backend/shared.php#90	2015-05-11T19:44:57+00:00
Error	PHP	Undefined offset: 0 at /var/www/owncloud/apps/contacts/lib/backend/shared.php#90	2015-05-11T19:44:57+00:00
```

### Expected behaviour

No errors

### Server and Version

8.0.3
PHP 5.5
Mail 0.1

### PR DESCRIPTION
**Pull request by DeepDiver1975**
@enoch85 please have a look - THX

Fixes #656

### CODE REVIEW

**Comment by jancborchardt** [comment]
@enoch85 also please check if this fixes https://github.com/owncloud/mail/issues/656 for you. :)

**Comment by enoch85** [comment]
Get this:

```
Error	PHP	Undefined offset: 0 at /var/www/owncloud/apps/contacts/lib/backend/shared.php#90	2015-05-22T21:58:58+00:00
Error	PHP	Undefined offset: 0 at /var/www/owncloud/apps/contacts/lib/backend/shared.php#90	2015-05-22T21:58:57+00:00
Error	PHP	Undefined index: size at /var/www/owncloud/lib/private/files/cache/scanner.php#268	2015-05-22T22:15:04+00:00
Error	PHP	Undefined index: size at /var/www/owncloud/lib/private/files/cache/scanner.php#265	2015-05-22T22:15:04+00:00
Error	PHP	Undefined index: mimetype at /var/www/owncloud/lib/private/files/cache/scanner.php#263	2015-05-22T22:15:04+00:00
Error	PHP	Undefined index: size at /var/www/owncloud/lib/private/files/cache/scanner.php#268	2015-05-22T22:15:04+00:00
Error	PHP	Undefined index: size at /var/www/owncloud/lib/private/files/cache/scanner.php#265	2015-05-22T22:15:04+00:00
Error	PHP	Undefined index: mimetype at /var/www/owncloud/lib/private/files/cache/scanner.php#263	2015-05-22T22:15:04+00:00
Error	PHP	Undefined index: size at /var/www/owncloud/lib/private/files/cache/scanner.php#268	2015-05-22T22:15:04+00:00
Error	PHP	Undefined index: size at /var/www/owncloud/lib/private/files/cache/scanner.php#265	2015-05-22T22:15:04+00:00
Error	PHP	Undefined index: mimetype at /var/www/owncloud/lib/private/files/cache/scanner.php#263	2015-05-22T22:15:04+00:00
Error	PHP	Undefined index: size at /var/www/owncloud/lib/private/files/cache/scanner.php#268	2015-05-22T22:15:04+00:00
```

Patched with the RAW file, and replaced the content with the latest updates, just as usual.

**Comment by enoch85** [comment]
and no, not fixed...

```
Error	PHP	Undefined index: REQUEST_URI at /var/www/owncloud/apps/calendar/appinfo/app.php#41	2015-05-23T00:45:02+02:00
Error	PHP	Undefined index: REQUEST_URI at /var/www/owncloud/apps/calendar/appinfo/app.php#41	2015-05-22T22:30:02+00:00
```

**Comment by DeepDiver1975** [comment]
@enoch85 the errors you are mentioning are related to core or calendar - this PR can only fix these:
````
Error   PHP Undefined index: EMAIL at /var/www/owncloud/apps/mail/lib/service/contactsintegration.php#41    2015-05-11T19:44:57+00:00
Error   PHP Undefined index: EMAIL at /var/www/owncloud/apps/mail/lib/service/contactsintegration.php#41    2015-05-11T19:44:57+00:00
Error   PHP Undefined index: EMAIL at /var/www/owncloud/apps/mail/lib/service/contactsintegration.php#41    2015-05-11T19:44:57+00:00
Error   PHP Undefined index: EMAIL at /var/www/owncloud/apps/mail/lib/service/contactsintegration.php#41    2015-05-11T19:44:57+00:00

**Comment by enoch85** [comment]
@DeepDiver1975 Ahh, mixed up the errors, alot of stress right now. 

Confirmed. :+1:

**Pull request merged**
