### PR TITLE
run CI js tests only once

### LINKED ISSUE #1105: [CI] test javascript only once
Currently javascript tests are executed for each php version and database type. Since it's the same every time (we don't depend on core or anything) it's useless to re-run those tests.

Running js tests only once would also speed up CI builds.

### PR DESCRIPTION
**Pull request by ChristophWurst**
fixes #1105

@DeepDiver1975 @Gomez @itheiss @irgendwie @Xenopathic does anybody have any objections of running JS tests only once?

### CODE REVIEW

**Comment by ChristophWurst** [comment]
# Comparison
## Before (37min 55sec):
bildschirmfoto von 2015-09-22 11-10-36

## After (28min 13sec):
bildschirmfoto von 2015-09-22 11-12-47

**Comment by clementhk** [comment]
Good idea, the test is taking longer and longer somehow.

**Comment by ChristophWurst** [comment]
> the test is taking longer and longer somehow.

That *could* be the mail server. Maybe google slows intentionally if there are too many requests at once.

**Comment by Gomez** [comment]
Good! Fixes #1105

**Pull request merged**
