### PR TITLE
Improves autoconfig by querying different mozilla isp sources

### PR DESCRIPTION
**Pull request by Scheirle**
Before this PR we only query `https://autoconfig.thunderbird.net/v1.1/{DOMAIN}`. A lot of small providers are not in this source.

This PR adds provider specific source(s): `https://autoconfig.{DOMAIN}/mail/config-v1.1.xml`, ...

Related:
 - https://github.com/owncloud/mail/issues/678
 - https://developer.mozilla.org/en-US/docs/Mozilla/Thunderbird/Autoconfiguration

### CODE REVIEW

**Comment by ChristophWurst** [comment]
@LukasReschke is it save to use http sources for autoconfig or should we use https only?

**Comment by Scheirle** [comment]
I don't understand why the `ContactsIntegrationTest::testDisabledContactsManager` test case fails ([Travis](https://travis-ci.org/owncloud/mail/jobs/122764608#L604))
I didn't change anything related to that.  :confused:

**Comment by ChristophWurst** [comment]
Maybe because you're using libxml [here](https://github.com/owncloud/mail/pull/1407/files#diff-ef389dfd6f1846ed9169f92813567082R39)? Try clearing xml errors with [libxml_clear_errors](http://php.net/manual/en/function.libxml-clear-errors.php), maybe that helps.
cc @DeepDiver1975

**Comment by Scheirle** [comment]
@ChristophWurst using `libxml_clear_errors` worked, thanks.

**Comment by ChristophWurst** [comment]
Awesome. Let me know when this is ready to review/test!

**Comment by ChristophWurst** [comment]
:+1: thanks a lot for this enhancement!

**Pull request merged**
