### PR TITLE
Speed up unified inbox loading by caching some redundant imap calls

### PR DESCRIPTION
**Pull request by ChristophWurst**
Since unified inbox felt kind of slow when initially loading the app after browser cache has been cleared, I had a look at what might cause it. It turned out the uniform inbox implementation re-creates accounts again for each message that is being loaded (bulk message load route). This resulted in 32 imap connections for 2 imap accounts. Moreover, whenever the special folder 'inbox' was queried, the imap server was asked for a list of mailboxes.

I added some in-memory caching to prevent useless calls to the imap server per request. As a result, loading 10 messages of the unified inbox in bulk now takes about 3.9s, where it took 12.8 without those optimizations. 3 instead of 32 imap connections are needed.

@owncloud/mail please test and review this, thanks.

### CODE REVIEW

**Comment by jancborchardt** [comment]
ARE YOU KIDDING ME!? This is superfast now. :D Awesome :+1: 

Please also test & review this @matiasdelellis @PoPoutdoor @phsc @aspdye :)

**Comment by PoPoutdoor** [comment]
Much faster now :+1:

**Comment by aspdye** [comment]
:+1: 
Great work :)

**Comment by ChristophWurst** [comment]
Great. I'll have a look at the tests before merging, seems like something is broken now.

**Comment by ChristophWurst** [comment]
Ok, I had to remove one little optimization since that caused problems. It´s still pretty fast.
@jancborchardt @PoPoutdoor @aspdye could anyone of you please test this again? Thank you.

**Comment by jancborchardt** [comment]
I get these errors with this PR now, and some mails don’t open in the unified inbox:
```
{"reqId":"+uV+HbnTSAIBv7YyKDIM","remoteAddr":"127.0.0.1","app":"PHP","message":"The hardcoded value you are using for the $referenceType argument of the Symfony\\Component\\Routing\\Generator\\UrlGenerator::generate method is deprecated since version 2.8 and will not be supported anymore in 3.0. Use the constants defined in the UrlGeneratorInterface instead. at \/home\/jan\/owncloud\/3rdparty\/symfony\/routing\/Generator\/UrlGenerator.php#147","level":0,"time":"2015-12-30T18:43:09+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/mail\/accounts\/-1\/folders\/YWxsLWluYm94ZXM%3D\/messages?ids=WzEsMTI0NDBd%2CWzEsMTI0Mzld%2CWzMsOTMwXQ%3D%3D%2CWzEsMTI0MDJd%2CWzEsMTIzOTld"}
{"reqId":"+uV+HbnTSAIBv7YyKDIM","remoteAddr":"127.0.0.1","app":"PHP","message":"The hardcoded value you are using for the $referenceType argument of the Symfony\\Component\\Routing\\Generator\\UrlGenerator::generate method is deprecated since version 2.8 and will not be supported anymore in 3.0. Use the constants defined in the UrlGeneratorInterface instead. at \/home\/jan\/owncloud\/3rdparty\/symfony\/routing\/Generator\/UrlGenerator.php#147","level":0,"time":"2015-12-30T18:43:09+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/mail\/accounts\/-1\/folders\/YWxsLWluYm94ZXM%3D\/messages?ids=WzEsMTI0NDBd%2CWzEsMTI0Mzld%2CWzMsOTMwXQ%3D%3D%2CWzEsMTI0MDJd%2CWzEsMTIzOTld"}
{"reqId":"+uV+HbnTSAIBv7YyKDIM","remoteAddr":"127.0.0.1","app":"PHP","message":"The hardcoded value you are using for the $referenceType argument of the Symfony\\Component\\Routing\\Generator\\UrlGenerator::generate method is deprecated since version 2.8 and will not be supported anymore in 3.0. Use the constants defined in the UrlGeneratorInterface instead. at \/home\/jan\/owncloud\/3rdparty\/symfony\/routing\/Generator\/UrlGenerator.php#147","level":0,"time":"2015-12-30T18:43:10+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/mail\/accounts\/-1\/folders\/YWxsLWluYm94ZXM%3D\/messages?ids=WzEsMTI0NDBd%2CWzEsMTI0Mzld%2CWzMsOTMwXQ%3D%3D%2CWzEsMTI0MDJd%2CWzEsMTIzOTld"}
{"reqId":"+uV+HbnTSAIBv7YyKDIM","remoteAddr":"127.0.0.1","app":"PHP","message":"The hardcoded value you are using for the $referenceType argument of the Symfony\\Component\\Routing\\Generator\\UrlGenerator::generate method is deprecated since version 2.8 and will not be supported anymore in 3.0. Use the constants defined in the UrlGeneratorInterface instead. at \/home\/jan\/owncloud\/3rdparty\/symfony\/routing\/Generator\/UrlGenerator.php#147","level":0,"time":"2015-12-30T18:43:10+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/mail\/accounts\/-1\/folders\/YWxsLWluYm94ZXM%3D\/messages?ids=WzEsMTI0NDBd%2CWzEsMTI0Mzld%2CWzMsOTMwXQ%3D%3D%2CWzEsMTI0MDJd%2CWzEsMTIzOTld"}
{"reqId":"+uV+HbnTSAIBv7YyKDIM","remoteAddr":"127.0.0.1","app":"PHP","message":"Call to undefined method OC_Helper::mimetypeIcon() at \/home\/jan\/owncloud\/apps\/mail\/lib\/controller\/messagescontroller.php#378","level":3,"time":"2015-12-30T18:43:10+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/mail\/accounts\/-1\/folders\/YWxsLWluYm94ZXM%3D\/messages?ids=WzEsMTI0NDBd%2CWzEsMTI0Mzld%2CWzMsOTMwXQ%3D%3D%2CWzEsMTI0MDJd%2CWzEsMTIzOTld"}
```

**Comment by ChristophWurst** [comment]
> I get these errors with this PR now, and some mails don’t open in the unified inbox:

Do you get those errors on this PR-branch only or also on master?

**Comment by ChristophWurst** [comment]
I see those errors on my dev-env too, although mail is on master. Can you confirm that it´s not related?

**Comment by jancborchardt** [comment]
Yeah, master too. Different issue, so merging these improvements.

**Comment by Gomez** [comment]
Impressive work my friend!

**Comment by jancborchardt** [comment]
My face when I tried this out

**Comment by enoch85** [comment]
@jancborchardt you made my day with that comment! Lool!

**Pull request merged**
