### PR TITLE
Don't double load accounts ...

### LINKED ISSUE #304: After adding a new account - its not shown immediately in settings
The account is there, i can see the inbox, but the account is not in settings. 

Full refresh is needed

### PR DESCRIPTION
**Pull request by DeepDiver1975**
refs #537
fixes #304

@jancborchardt @Gomez

### CODE REVIEW

**Comment by jancborchardt** [comment]
@DeepDiver1975 is this WIP or to review?

**Comment by DeepDiver1975** [comment]
Wip

**Comment by jancborchardt** [comment]
@DeepDiver1975 the spinner issue is not that important – but I would rather have it overlay than completely missing. Can you remove commit 4fc341e again?

**Comment by DeepDiver1975** [comment]
> Can you remove commit 4fc341e again?

sure ...

**Comment by DeepDiver1975** [comment]
@jancborchardt done

**Comment by Xenopathic** [comment]
Nice :+1:

**Pull request merged**
