### PR TITLE
Adding build step to create appstore tar + use travis for deployment

### LINKED ISSUE #1317: Use travis to build github releases
## ownCloud Mail

https://docs.travis-ci.com/user/deployment/releases

Already done - https://github.com/DeepDiver1975/ownCloudCLA/blob/master/.travis.yml#L10-L18

https://github.com/DeepDiver1975/ownCloudCLA/releases

### PR DESCRIPTION
**Pull request by DeepDiver1975**
fixes #1317

### CODE REVIEW

**Comment by ChristophWurst** [comment]
is that testable in some way?

**Comment by DeepDiver1975** [comment]
> is that testable in some way?

we need to create a tag and based on this tag a release will be built

**Comment by DeepDiver1975** [comment]
rebasing ....

**Comment by Gomez** [comment]
As it does not harm i merge. Lets test it with v0.3.1

**Pull request merged**
