### PR TITLE
#522 Fix uid validity branch

### PR DESCRIPTION
**Pull request by clementhk**
This fixed all failed tests.
Please be aware that this pr is towards uid-validity branch in #522.

On top of this, please set `Concurrent jobs` to 1 on travis-ci.org.

### CODE REVIEW

**Comment by clementhk** [comment]
Build log: https://travis-ci.org/clementhk/mail/builds/60038633.

**Comment by jancborchardt** [comment]
@clementhk nice! @DeepDiver1975 please review!

@clementhk generally speaking we prefer clean commit logs – can you please use »git squash« to squash your commits into one? Thanks! :)

**Comment by jancborchardt** [comment]
(I just set the concurrent jobs to 1.)

**Comment by clementhk** [comment]
@jancborchardt It is a clean commit logs, each of the commit solve a different problem.
Please let me know what to squash if you think otherwise.

**Comment by jancborchardt** [comment]
@clementhk ok, nevermind then. :)

**Comment by Xenopathic** [comment]
All of the changes make sense :+1: (assuming you are done adding features)

**Comment by DeepDiver1975** [comment]
oh - nice!  missed that one - I actually like this approach better then mine

**Pull request merged**
