### PR TITLE
make header bar scroll instead of fixed, fix #328

### LINKED ISSUE #328: Scroll bar hidden/overlayed by title bar
### Steps to reproduce
1. Open any mail
2. Check the titlebar region with respect to the scrollbar for the message.

### Actual behaviour
On the top 50 pixels or so, the title bar covers the scrollbar. See this screenshot:
owncloud-mail-titlebar

### Expected behaviour
The scrollbar should either start below the title bar or should not be overlayed by it

### Client configuration
**Browser:** Firefox 32.0.1 / Chrome 37.0.2062
**Operating system:** Windows 7

### PR DESCRIPTION
**Pull request by jancborchardt**
Fix https://github.com/owncloud/mail/issues/328, please review @RandolfCarter @owncloud/designers @wurstchristoph @irgendwie @Henni @Gomez

### CODE REVIEW

**Comment by jancborchardt** [comment]
@colmoneill what do you think?

**Comment by Xenopathic** [comment]
:-1: Original version looks better. This makes sense for smaller screens with limited vertical space, but on a desktop, I like it better the way it was before.

**Comment by jancborchardt** [comment]
Alright – then I’ll change it to just apply this for the mobile styles when the screen space is limited. :)

**Comment by jancborchardt** [comment]
@Xenopathic please review again. :)

**Comment by Xenopathic** [comment]
:+1:

**Pull request merged**
