### PR TITLE
remove deprecated mimetype method call

### LINKED ISSUE #1197: Mails with attachments can not be opened
This occurs both in the unified inbox and the seperate inboxes. Not sure if these errors in the log are related:

```
The hardcoded value you are using for the $referenceType argument of the Symfony\\Component\\Routing\\Generator\\UrlGenerator::generate method
is deprecated since version 2.8 and will not be supported anymore in 3.0.
Use the constants defined in the UrlGeneratorInterface instead.
at \/home\/jan\/owncloud\/3rdparty\/symfony\/routing\/Generator\/UrlGenerator.php#147",
"method":"GET",
"url":"\/owncloud\/index.php\/apps\/mail\/accounts\/-1\/folders\/YWxsLWluYm94ZXM%3D\/messages\/WzEsMTI0NjJd"

Call to undefined method OC_Helper::mimetypeIcon()
at \/home\/jan\/owncloud\/apps\/mail\/lib\/controller\/messagescontroller.php#378",
"method":"GET",
"url":"\/owncloud\/index.php\/apps\/mail\/accounts\/-1\/folders\/YWxsLWluYm94ZXM%3D\/messages\/WzEsMTI0NjJd"
```

@owncloud/mail pretty grave issue, so we should definitely fix this for 0.3

### PR DESCRIPTION
**Pull request by ChristophWurst**
fixes #1197

@jancborchardt @owncloud/mail test & review please

### CODE REVIEW

**Comment by jancborchardt** [comment]
Now I get even more errors:
```
{"reqId":"AmIz4K+pBXiyFmVVzxd2","remoteAddr":"127.0.0.1","app":"PHP","message":"The hardcoded value you are using for the $referenceType argument of the Symfony\\Component\\Routing\\Generator\\UrlGenerator::generate method is deprecated since version 2.8 and will not be supported anymore in 3.0. Use the constants defined in the UrlGeneratorInterface instead. at \/home\/jan\/owncloud\/3rdparty\/symfony\/routing\/Generator\/UrlGenerator.php#147","level":0,"time":"2016-01-02T16:54:12+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/mail\/accounts\/-1\/folders\/YWxsLWluYm94ZXM%3D\/messages"}
{"reqId":"AmIz4K+pBXiyFmVVzxd2","remoteAddr":"127.0.0.1","app":"PHP","message":"The hardcoded value you are using for the $referenceType argument of the Symfony\\Component\\Routing\\Generator\\UrlGenerator::generate method is deprecated since version 2.8 and will not be supported anymore in 3.0. Use the constants defined in the UrlGeneratorInterface instead. at \/home\/jan\/owncloud\/3rdparty\/symfony\/routing\/Generator\/UrlGenerator.php#147","level":0,"time":"2016-01-02T16:54:12+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/mail\/accounts\/-1\/folders\/YWxsLWluYm94ZXM%3D\/messages"}
{"reqId":"AmIz4K+pBXiyFmVVzxd2","remoteAddr":"127.0.0.1","app":"PHP","message":"The hardcoded value you are using for the $referenceType argument of the Symfony\\Component\\Routing\\Generator\\UrlGenerator::generate method is deprecated since version 2.8 and will not be supported anymore in 3.0. Use the constants defined in the UrlGeneratorInterface instead. at \/home\/jan\/owncloud\/3rdparty\/symfony\/routing\/Generator\/UrlGenerator.php#147","level":0,"time":"2016-01-02T16:54:12+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/mail\/accounts\/-1\/folders\/YWxsLWluYm94ZXM%3D\/messages"}
{"reqId":"AmIz4K+pBXiyFmVVzxd2","remoteAddr":"127.0.0.1","app":"PHP","message":"The hardcoded value you are using for the $referenceType argument of the Symfony\\Component\\Routing\\Generator\\UrlGenerator::generate method is deprecated since version 2.8 and will not be supported anymore in 3.0. Use the constants defined in the UrlGeneratorInterface instead. at \/home\/jan\/owncloud\/3rdparty\/symfony\/routing\/Generator\/UrlGenerator.php#147","level":0,"time":"2016-01-02T16:54:12+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/mail\/accounts\/-1\/folders\/YWxsLWluYm94ZXM%3D\/messages"}
{"reqId":"AmIz4K+pBXiyFmVVzxd2","remoteAddr":"127.0.0.1","app":"PHP","message":"The hardcoded value you are using for the $referenceType argument of the Symfony\\Component\\Routing\\Generator\\UrlGenerator::generate method is deprecated since version 2.8 and will not be supported anymore in 3.0. Use the constants defined in the UrlGeneratorInterface instead. at \/home\/jan\/owncloud\/3rdparty\/symfony\/routing\/Generator\/UrlGenerator.php#147","level":0,"time":"2016-01-02T16:54:12+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/mail\/accounts\/-1\/folders\/YWxsLWluYm94ZXM%3D\/messages"}
{"reqId":"AmIz4K+pBXiyFmVVzxd2","remoteAddr":"127.0.0.1","app":"index","message":"Exception: {\"Exception\":\"OCP\\\\AppFramework\\\\QueryException\",\"Message\":\"Could not resolve request! Class request does not exist\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/jan\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/utility\\\/simplecontainer.php(104): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->resolve('request')\\n#1 \\\/home\\\/jan\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/utility\\\/simplecontainer.php(64): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->query('request')\\n#2 \\\/home\\\/jan\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/utility\\\/simplecontainer.php(83): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->buildClass(Object(ReflectionClass))\\n#3 \\\/home\\\/jan\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/utility\\\/simplecontainer.php(104): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->resolve('OCA\\\\\\\\Mail\\\\\\\\Contro...')\\n#4 \\\/home\\\/jan\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/app.php(97): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->query('OCA\\\\\\\\Mail\\\\\\\\Contro...')\\n#5 \\\/home\\\/jan\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/routing\\\/routeactionhandler.php(45): OC\\\\AppFramework\\\\App::main('MessagesControl...', 'index', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#6 [internal function]: OC\\\\AppFramework\\\\routing\\\\RouteActionHandler->__invoke(Array)\\n#7 \\\/home\\\/jan\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(297): call_user_func(Object(OC\\\\AppFramework\\\\routing\\\\RouteActionHandler), Array)\\n#8 \\\/home\\\/jan\\\/owncloud\\\/lib\\\/base.php(871): OC\\\\Route\\\\Router->match('\\\/apps\\\/mail\\\/acco...')\\n#9 \\\/home\\\/jan\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n#10 {main}\",\"File\":\"\\\/home\\\/jan\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/utility\\\/simplecontainer.php\",\"Line\":89}","level":3,"time":"2016-01-02T16:54:12+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/mail\/accounts\/-1\/folders\/YWxsLWluYm94ZXM%3D\/messages"}
```
And an »Error while loading messages.« notification as well as an unsafe-eval CSP notice in the JS console, cc @LukasReschke

**Comment by ChristophWurst** [comment]
Damn. At least the first errors should be resolved with PR https://github.com/owncloud/core/pull/21393

**Comment by ChristophWurst** [comment]
@jancborchardt please test again. There was no message with attachments when I first tested it, sorry :see_no_evil: 

I wonder why the strange error message "Could not resolve request! Class request does not exist" was shown. That makes no sense to me…

**Comment by jancborchardt** [comment]
Seems to work now :+1: ;)

A second review please, @owncloud/mail folks!

**Comment by jancborchardt** [comment]
Yo, another quick review please. ;) @ Lukasreschke @irgendwie

**Comment by Gomez** [comment]
This only happens on ownCloud master? With 8.2 all is fine > good to merge

**Comment by ChristophWurst** [comment]
> This only happens on ownCloud master? With 8.2 all is fine > good to merge

Yes, this would be a problem for production systems once oc9 is out. (ref https://github.com/owncloud/core/pull/21288)

**Pull request merged**
