### PR TITLE
add grunt task for running jscs checks

### PR DESCRIPTION
**Pull request by wurstchristoph**
usage: "grunt jscs"
https://github.com/jscs-dev/grunt-jscs/

@Gomez review please :)

### CODE REVIEW

**Comment by Gomez** [comment]
Nice :)
:+1: 
So, can we add jshint, too?

**Comment by wurstchristoph** [comment]
@Gomez added ;-)

**Comment by Gomez** [comment]
Thanks! 
:+1:

**Comment by Gomez** [comment]
Can someone check this out, too:
@DeepDiver1975 @clementhk @Xenopathic
Should we add some more docu to get the grunt task setup? Or just links to docu?

**Comment by DeepDiver1975** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
> Should we add some more docu to get the grunt task setup? Or just links to docu?

well - let's keep this that way for now

**Pull request merged**
