### PR TITLE
Add more url tests

### PR DESCRIPTION
**Pull request by Gomez**
This adds the url from https://github.com/owncloud/mail/issues/641

This needs to be merged with https://github.com/owncloud/mail/pull/797!

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
https://github.com/owncloud/mail/commit/721be793e318d6b4ce17255e38ad2c727ec8ed27 holds now the whole changes set as of #797 - let's see if tests pass ....

**Comment by Gomez** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
nice :+1:

**Comment by jancborchardt** [comment]
So you said 

> This needs to be merged with #797!

Should we merge that then?

**Comment by Gomez** [comment]
No, @DeepDiver1975 merged it already here. I will close #797!

**Comment by jancborchardt** [comment]
Cool! So https://github.com/owncloud/mail/issues/641 is fixed as well? :)

**Pull request merged**
