### PR TITLE
Add tests to the list of allowed paths

### PR DESCRIPTION
**Pull request by oparoz**
Most apps can't run their tests any more because of a new restriction in core:
https://github.com/owncloud/core/pull/18396

This fixes the bootstrap.

@DeepDiver1975 @jancborchardt

### CODE REVIEW

**Comment by oparoz** [comment]
Argh, since you only have one branch for all ownCloud versions, I (or someone else) needs to add a version check...

**Comment by Gomez** [comment]
@oparoz I added a version check, but cant get it to work on all versions. Can you please have a look?

**Comment by ChristophWurst** [comment]
ok, tests pass again :+1:

**Comment by oparoz** [comment]
Thanks @ChristophWurst !

**Comment by jancborchardt** [comment]
@oparoz awesome to see you contributing to the Mail app too! :)

**Comment by oparoz** [comment]
Pure luck, a one off! ;)

**Comment by jancborchardt** [comment]
@oparoz hehe, you’re going to get sucked in just like I got sucked into Gallery contributions. ;D

**Pull request merged**
