### PR TITLE
set 'from' dropdown to current account, fix #297

### LINKED ISSUE #297: Send new mail/message from account of last selected folder (currently active one)
When composing a new mail, the 'from' email address seems to always be the first account.
If we were in a folder of another account before cicking the new mail button, the 'from' field should default to that account's identity/email address (Thunderbird does this).

### PR DESCRIPTION
**Pull request by jancborchardt**
Fixes #297

Please review @zinks- @Xenopathic @irgendwie :)

### CODE REVIEW

**Comment by jancborchardt** [comment]
@DeepDiver1975 Travis says `'currentAccountId' is not defined.` – is that because for a single-account setup that variable is not set? So I guess a simple `if (!_.isUndefined(currentAccountId))` around it will suffice?

**Comment by DeepDiver1975** [comment]
tested :+1:

**Comment by DeepDiver1975** [comment]
@jancborchardt js has been adjusted - To learn a lot you have, my young Padawan!

**Comment by jancborchardt** [comment]
Ah yeah, the correct object/function, eh?

**Comment by jancborchardt** [comment]
Thx!

**Pull request merged**
