### PR TITLE
invalidate js cache if app version changes

### LINKED ISSUE #965: Cache invalidation for updates
Some changes like PR #956 require the cache to be cleared when you upgrade the app. Since we can't expect users to do that manually, some kind of cache invalidation should be used whenever the app version changes.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/26275359-cache-invalidation-for-updates?utm_campaign=plugin&utm_content=tracker%2F216487&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F216487&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by ChristophWurst**
fixes #965

### CODE REVIEW

**Comment by Gomez** [comment]
First i get this:

```
ReferenceError: Cookies is not defined
<anonymous> jquery.storageapi.js:420
<anonymous> jquery.storageapi.js:23
<anonymous>
```

Later this:

callstack

I cleared localstorage, before.

**Comment by ChristophWurst** [comment]
@Gomez good catch. I get those errors too after re-installing js dependencies.

**Comment by ChristophWurst** [comment]
Downgrading the lib helps. We should check if we need that lib at all, it seems to be unmaintained

**Comment by Gomez** [comment]
fine now!

**Pull request merged**
