### PR TITLE
Make mail ownCloud7 compliant

### PR DESCRIPTION
**Pull request by DeepDiver1975**
refs #642 

@jancborchardt @zinks- @rullzer @MorrisJobke please review and test - THX

### CODE REVIEW

**Comment by jancborchardt** [comment]
Also cc @clementhk @irgendwie @wurstchristoph check this out ^

**Comment by jancborchardt** [comment]
Oh and @aimlessadam please review this as well as it fixes #642 :)

**Comment by jancborchardt** [comment]
@DeepDiver1975 we can also just put the CSS stuff on the bottom of the normal CSS file with a note to be removed if we would drop ownCloud 7 compatibility. That seems a bit simpler than conditionally loading another CSS file. What do you think? I can do it right away.

**Comment by jancborchardt** [comment]
Works fine still on my ownCloud 8 dev setup. But on my (slightly older) ownCloud 7 I get these errors.

First when installing this notice:
```
Invalid OCS content returned for app mail
```
Then the app does not load:
```
Call to undefined method OC\\Server::getCrypto()
at /apps\/mail\/appinfo\/application.php line 121
```

Any idea? Is that because the ownCloud 7 is _too_ old? cc @LukasReschke because crypto.

**Comment by DeepDiver1975** [comment]
Hmm ... might be that we require a certain 7.0.x   .... let me check later

**Comment by jancborchardt** [comment]
The version I have is 7.0.2 (pulled via git).

**Comment by jancborchardt** [comment]
Will also test with a fresh local setup.

**Comment by jancborchardt** [comment]
@DeepDiver1975 works very nicely with latest ownCloud 7! :+1: :) We can’t do anything about search not working, right?

Another review please @aimlessadam @clementhk @zinks- @irgendwie @MorrisJobke! Last one for 0.1 :rocket:

**Comment by irgendwie** [comment]
@jancborchardt Used latest stable7 (from git) and the mail app seems to work as expected - tried some basic stuff! :+1: very nice @DeepDiver1975

**Pull request merged**
