### PR TITLE
Fix code checker

### PR DESCRIPTION
**Pull request by DeepDiver1975**

### CODE REVIEW

**Comment by Xenopathic** [comment]
:+1: Code looks good

**Comment by jancborchardt** [comment]
And stuff still works :+1:

**Comment by Xenopathic** [comment]
This has broken compatibility with oC 8.0... will oC Mail 0.1 be restricted to 8.1 and above only?

**Comment by jancborchardt** [comment]
Oh lala – @DeepDiver1975 we want to preserve 8.0 compatibility, right? Can you fix that?

(I’m fine with breaking ownCloud 7 compat, but 8.0 we should definitely work with.)

**Comment by jancborchardt** [comment]
And @Xenopathic thanks for finding it out! We mostly test with our master installations.

**Comment by Xenopathic** [comment]
@jancborchardt Hehe, I run it on my 'production' server (3 users :smile:) so I'm running the latest stable.

**Pull request merged**
