### PR TITLE
Use the proper method on the server object

### LINKED ISSUE #1207: Exception: {"Exception":"OCP\\AppFramework\\QueryException","Message":"Could not resolve request! Class request does not exist"
500 while loading unified inbox

Latest nightly

~~~
Fatal 	index 	Exception: {"Exception":"OCP\\AppFramework\\QueryException","Message":"Could not resolve request! Class request does not exist","Code":0,"Trace":"#0 \/owncloud\/lib\/private\/appframework\/utility\/simplecontainer.php(98): OC\\AppFramework\\Utility\\SimpleContainer->resolve('request')\n#1 \/owncloud\/lib\/private\/appframework\/utility\/simplecontainer.php(59): OC\\AppFramework\\Utility\\SimpleContainer->query('request')\n#2 \/owncloud\/lib\/private\/appframework\/utility\/simplecontainer.php(78): OC\\AppFramework\\Utility\\SimpleContainer->buildClass(Object(ReflectionClass))\n#3 \/owncloud\/lib\/private\/appframework\/utility\/simplecontainer.php(98): OC\\AppFramework\\Utility\\SimpleContainer->resolve('OCA\\\\Mail\\\\Contro...')\n#4 \/owncloud\/lib\/private\/appframework\/app.php(96): OC\\AppFramework\\Utility\\SimpleContainer->query('OCA\\\\Mail\\\\Contro...')\n#5 \/owncloud\/lib\/private\/appframework\/routing\/routeactionhandler.php(45): OC\\AppFramework\\App::main('MessagesControl...', 'index', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#6 [internal function]: OC\\AppFramework\\routing\\RouteActionHandler->__invoke(Array)\n#7 \/owncloud\/lib\/private\/route\/router.php(283): call_user_func(Object(OC\\AppFramework\\routing\\RouteActionHandler), Array)\n#8 \/owncloud\/lib\/base.php(874): OC\\Route\\Router->match('\/apps\/mail\/acco...')\n#9 \/owncloud\/index.php(48): OC::handleRequest()\n#10 {main}","File":"\/owncloud\/lib\/private\/appframework\/utility\/simplecontainer.php","Line":84} 	2016-01-06T10:36:41+08:00
Fatal 	index 	Exception: {"Exception":"OCP\\AppFramework\\QueryException","Message":"Could not resolve request! Class request does not exist","Code":0,"Trace":"#0 \/owncloud\/lib\/private\/appframework\/utility\/simplecontainer.php(98): OC\\AppFramework\\Utility\\SimpleContainer->resolve('request')\n#1 \/owncloud\/lib\/private\/appframework\/utility\/simplecontainer.php(59): OC\\AppFramework\\Utility\\SimpleContainer->query('request')\n#2 \/owncloud\/lib\/private\/appframework\/utility\/simplecontainer.php(78): OC\\AppFramework\\Utility\\SimpleContainer->buildClass(Object(ReflectionClass))\n#3 \/owncloud\/lib\/private\/appframework\/utility\/simplecontainer.php(98): OC\\AppFramework\\Utility\\SimpleContainer->resolve('OCA\\\\Mail\\\\Contro...')\n#4 \/owncloud\/lib\/private\/appframework\/app.php(96): OC\\AppFramework\\Utility\\SimpleContainer->query('OCA\\\\Mail\\\\Contro...')\n#5 \/owncloud\/lib\/private\/appframework\/routing\/routeactionhandler.php(45): OC\\AppFramework\\App::main('MessagesControl...', 'index', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#6 [internal function]: OC\\AppFramework\\routing\\RouteActionHandler->__invoke(Array)\n#7 \/owncloud\/lib\/private\/route\/router.php(283): call_user_func(Object(OC\\AppFramework\\routing\\RouteActionHandler), Array)\n#8 \/owncloud\/lib\/base.php(874): OC\\Route\\Router->match('\/apps\/mail\/acco...')\n#9 \/owncloud\/index.php(48): OC::handleRequest()\n#10 {main}","File":"\/owncloud\/lib\/private\/appframework\/utility\/simplecontainer.php","Line":84} 	2016-01-06T10:36:38+08:00
Fatal 	index 	Exception: {"Exception":"OCP\\AppFramework\\QueryException","Message":"Could not resolve request! Class request does not exist","Code":0,"Trace":"#0 \/owncloud\/lib\/private\/appframework\/utility\/simplecontainer.php(98): OC\\AppFramework\\Utility\\SimpleContainer->resolve('request')\n#1 \/owncloud\/lib\/private\/appframework\/utility\/simplecontainer.php(59): OC\\AppFramework\\Utility\\SimpleContainer->query('request')\n#2 \/owncloud\/lib\/private\/appframework\/utility\/simplecontainer.php(78): OC\\AppFramework\\Utility\\SimpleContainer->buildClass(Object(ReflectionClass))\n#3 \/owncloud\/lib\/private\/appframework\/utility\/simplecontainer.php(98): OC\\AppFramework\\Utility\\SimpleContainer->resolve('OCA\\\\Mail\\\\Contro...')\n#4 \/owncloud\/lib\/private\/appframework\/app.php(96): OC\\AppFramework\\Utility\\SimpleContainer->query('OCA\\\\Mail\\\\Contro...')\n#5 \/owncloud\/lib\/private\/appframework\/routing\/routeactionhandler.php(45): OC\\AppFramework\\App::main('MessagesControl...', 'show', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#6 [internal function]: OC\\AppFramework\\routing\\RouteActionHandler->__invoke(Array)\n#7 \/owncloud\/lib\/private\/route\/router.php(283): call_user_func(Object(OC\\AppFramework\\routing\\RouteActionHandler), Array)\n#8 \/owncloud\/lib\/base.php(874): OC\\Route\\Router->match('\/apps\/mail\/acco...')\n#9 \/owncloud\/index.php(48): OC::handleRequest()\n#10 {main}","File":"\/owncloud\/lib\/private\/appframework\/utility\/simplecontainer.php","Line":84} 	2016-01-06T10:36:38+08:00
~~~

### PR DESCRIPTION
**Pull request by DeepDiver1975**
@ChristophWurst 

fixes #1207 for me

### CODE REVIEW

**Comment by ChristophWurst** [comment]
This is only a fix for oc >= 8.2, see https://github.com/owncloud/core/blob/c5a200c4198de951dabdd3f783ade655b8ea6434/lib/public/iservercontainer.php#L444-L450

**Comment by ChristophWurst** [comment]
@DeepDiver1975 did you test this on oc7, oc8 or oc8.1? :D

**Comment by DeepDiver1975** [comment]
This is only 8.2+

**Comment by ChristophWurst** [comment]
> This is only 8.2+

:+1: ok, so we'll need another fix for 8.1-

**Pull request merged**
