### PR TITLE
Allow delete of messages in our special fav folder

### LINKED ISSUE #553: Delete "Favorites" message not working
Messages in the favorites folder cannot be deleted. 

owncloud.log says ```Could not open mailbox "INBOX/FLAGGED"```

Horde log:
```
------------------------------
>> Wed, 29 Apr 2015 12:50:22 +0000
>> Connection to: imap://imap.world4you.com/
>> Server connection took 0.01 seconds.
S: * OK [CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE STARTTLS AUTH=PLAIN AUTH=LOGIN] Dovecot ready.
C: 1 AUTHENTICATE PLAIN [INITIAL CLIENT RESPONSE (username: xxx@yyy.at)]
S: 1 OK [CAPABILITY IMAP4rev1 UNSELECT IDLE NAMESPACE QUOTA CHILDREN ID] Logged in
>> Command 1 took 0.0499 seconds.
C: 2 LIST "" *
S: * LIST (\HasNoChildren) "." "test folder"
S: * LIST (\HasNoChildren) "." "testfolder2"
S: * LIST (\HasNoChildren) "." "Sent"
S: * LIST (\HasNoChildren) "." "Drafts"
S: * LIST (\HasNoChildren) "." "Trash"
S: * LIST (\HasNoChildren) "." "INBOX"
S: 2 OK List completed.
>> Command 2 took 0.0091 seconds.
C: 3 STATUS INBOX (MESSAGES)
S: * STATUS "INBOX" (MESSAGES 123)
S: 3 OK Status completed.
>> Command 3 took 0.0094 seconds.
C: 4 STATUS INBOX (MESSAGES)
S: * STATUS "INBOX" (MESSAGES 123)
S: 4 OK Status completed.
>> Command 4 took 0.0103 seconds.
C: 5 STATUS Sent (MESSAGES)
S: * STATUS "Sent" (MESSAGES 93)
S: 5 OK Status completed.
>> Command 5 took 0.0089 seconds.
C: 6 STATUS Sent (MESSAGES)
S: * STATUS "Sent" (MESSAGES 93)
S: 6 OK Status completed.
>> Command 6 took 0.0089 seconds.
C: 7 STATUS Drafts (MESSAGES)
S: * STATUS "Drafts" (MESSAGES 5)
S: 7 OK Status completed.
>> Command 7 took 0.01 seconds.
C: 8 STATUS Drafts (MESSAGES)
S: * STATUS "Drafts" (MESSAGES 5)
S: 8 OK Status completed.
>> Command 8 took 0.0091 seconds.
C: 9 STATUS Trash (MESSAGES)
S: * STATUS "Trash" (MESSAGES 66)
S: 9 OK Status completed.
>> Command 9 took 0.0086 seconds.
C: 10 STATUS Trash (MESSAGES)
S: * STATUS "Trash" (MESSAGES 66)
S: 10 OK Status completed.
>> Command 10 took 0.0104 seconds.
C: 11 STATUS INBOX (MESSAGES RECENT UIDNEXT UIDVALIDITY UNSEEN)
S: * STATUS "INBOX" (MESSAGES 123 RECENT 0 UIDNEXT 168 UIDVALIDITY 1428599115 UNSEEN 0)
S: 11 OK Status completed.
>> Command 11 took 0.0098 seconds.
C: 12 STATUS INBOX (MESSAGES RECENT UIDNEXT UIDVALIDITY UNSEEN)
S: * STATUS "INBOX" (MESSAGES 123 RECENT 0 UIDNEXT 168 UIDVALIDITY 1428599115 UNSEEN 0)
S: 12 OK Status completed.
>> Command 12 took 0.0096 seconds.
C: 13 STATUS Trash (MESSAGES)
S: * STATUS "Trash" (MESSAGES 66)
S: 13 OK Status completed.
>> Command 13 took 0.0096 seconds.
C: 14 STATUS Trash (MESSAGES)
S: * STATUS "Trash" (MESSAGES 66)
S: 14 OK Status completed.
>> Command 14 took 0.01 seconds.
C: 15 SELECT INBOX/FLAGGED
S: 15 NO Invalid mailbox name: INBOX/FLAGGED
>> Command 15 took 0.0091 seconds.
C: 16 LOGOUT
S: * BYE Logging out
S: 16 OK Logout completed.
>> Command 16 took 0.0085 seconds.
```

### PR DESCRIPTION
**Pull request by DeepDiver1975**
- fixes #553

@jancborchardt @wurstchristoph

### CODE REVIEW

**Comment by jancborchardt** [comment]
Nice, works as well! :+1: waiting for Travis again

**Comment by clementhk** [comment]
I can see that if there are multiple trash box, we are taking the first one now, would be cool to make use of guessBestMailBox().

**Comment by DeepDiver1975** [comment]
@clementhk sounds reasonable - can I ask you to open an issue or even a pr to fix this right away?  Thx

**Comment by zinks-** [comment]
:+1:

**Comment by wurstchristoph** [comment]
:+1:

**Comment by jancborchardt** [comment]
@DeepDiver1975 this needs a rebase

**Comment by clementhk** [comment]
Might not need it if you merge #597.

**Pull request merged**
