### PR TITLE
Fix tipsy not shown for next message in trash

### PR DESCRIPTION
**Pull request by irgendwie**
Fix for bug #614.
Seems like it's a jQuery bug?!

@wurstchristoph @jancborchardt review please!

### CODE REVIEW

**Comment by irgendwie** [comment]
Ok, doesn't seem like a jQuery bug and more like the tipsy is generated, but at the wrong location. (Probably a compatibility issue between the tipsies and jQuery)

After the slideup function call, we delete every tipsy, which leads to no tipsy at all for the next message, because the mouseover event was already called.
I solved this by manually calling the mouseover event for the current mouse position, which leads to a correct placed tipsy for the next message in the list (and only if the mouse is over the element of course).

**Comment by Gomez** [comment]
Is this still valid? I dont  get "Delete permanently" at all in trash?

**Comment by irgendwie** [comment]
@Gomez There should be tipsies in the trash! For Firefox and Chrome, they are visible with the current master for me!

**Comment by Gomez** [comment]
@irgendwie Hmm, would you send me a screenshot?

**Comment by irgendwie** [comment]
@Gomez 

tipsy

**Comment by jancborchardt** [comment]
Fixes #614 :+1: good stuff! :)

**Comment by jancborchardt** [comment]
(And yeah, I do get tipsies in the Trash as intended.)

**Comment by Gomez** [comment]
No tipsies for me. And the original-title text is missing. Maybe something with special folders?

```
<div original-title="" class="icon-delete action delete"></div>
```

**Comment by jancborchardt** [comment]
original-title is getting filled in by Tipsy normally, from the »title« attribute. Any JS errors? Does it work with another account or in another browser?

**Comment by wurstchristoph** [comment]
:+1: fixes it!

**Comment by Gomez** [comment]
@jancborchardt No Tipsy for me :( Let us look at the next meetup...

**Comment by jancborchardt** [comment]
@Gomez you and you strange custom setups ;)

**Comment by Gomez** [comment]
@jancborchardt You and your average/simple/boring setups :)

**Pull request merged**
