### PR TITLE
remove empty and unneeded compose.css file

### PR DESCRIPTION
**Pull request by jancborchardt**
Simple change, please review @enoch85 @irgendwie @zinks- everyone :)

### CODE REVIEW

**Comment by enoch85** [comment]
:+1:

**Comment by irgendwie** [comment]
LGTM :+1:

**Comment by jancborchardt** [comment]
Btw @DeepDiver1975 number of the pull request.

We achieved it! :metal:

**Comment by enoch85** [comment]
@jancborchardt Oh no, you got to that before me. Was thinking of making something fun out of it, but you beat me to it. :smiling_imp:

**Pull request merged**
