### PR TITLE
add 'sentmail' to special folders detection

### PR DESCRIPTION
**Pull request by jancborchardt**
As talked about in https://github.com/owncloud/mail/issues/411#issuecomment-103142914, please review @MeCias @DeepDiver1975 @zinks-

### CODE REVIEW

**Comment by MeCias** [comment]
No complains from my side, thank you for the work. :thumbsup:

**Comment by zinks-** [comment]
:+1:

**Comment by zinks-** [comment]
@jancborchardt  We should think about a setting, because these lists are going to grow!

**Comment by jancborchardt** [comment]
@zinks- them growing is fine though. I don’t really see the need for a setting as we should fix this in the app for everyone. :)

**Pull request merged**
