### PR TITLE
fix account form being autofilled with username and password in Chrome & Safari

### LINKED ISSUE #566: Autofill of the email settings form
These were the values that autofilled when adding an account to the mail app.

screenshot from 2015-05-01 22 35 44

I had to go and delete the autofilled values to find out what the form actually wanted, and it filled in based on my oC account, which are not the same as my external mail settings.

### PR DESCRIPTION
**Pull request by jancborchardt**
fix #566 

Please review @colmoneill @blizzz @Xenopathic @wurstchristoph @irgendwie 

@blizzz thank you for the code! :) As you see you can improve yours by using the standard `.hidden-visually` class from core, as well as adding `tabindex="-1"` so it doesn’t interfere with keyboard navigation.

### CODE REVIEW

**Comment by irgendwie** [comment]
Can **not** reproduce this bug with "Chromium 42.0.2311.135".

**Comment by jancborchardt** [comment]
@irgendwie does this pull request fix the bug for both browsers?

**Comment by irgendwie** [comment]
Dunno, I'm using neither of them two. :see_no_evil:
Feedback from @colmoneill is needed.

**Comment by jancborchardt** [comment]
Also cc @LukasReschke for Safari testing.

**Comment by Xenopathic** [comment]
I'll try to test this (as soon as I'm finished with this physics lesson...)

**Comment by Xenopathic** [comment]
Works great :+1:

Interesting thing I noticed though (@irgendwie this might be why it didn't work for you): the autofill doesn't happen if the email field already has a value, such as when an email address is set in your Personal settings. The IMAP Password box remains blank in this case.

**Comment by jancborchardt** [comment]
@Xenopathic yep, forgot to note that. The issue only appears in the first place if the email field is blank. (That’s how I found https://github.com/owncloud/core/issues/16057 ;)

**Comment by LukasReschke** [comment]
This is a huge hack and only will work until the browsers change their behaviour. A better fix is what we do in core where we use an explicit store credential button for example for the mail settings.

Without something like this this can pretty easily leak your password to a service provider withour you knowing…

**Comment by jancborchardt** [comment]
@LukasReschke I’m not entirely sure I know what you mean. What do we do in core which is comparable to this? And how could your password be leaked here – the hidden boxes are not sent anywhere.

**Pull request merged**
