### PR TITLE
Adding translation sync preproc command ...

### LINKED ISSUE #1031: Pre process task for transifex.com
As we lose the translations in the handlebar js templates, we created a script to add them back:
https://github.com/owncloud/mail/pull/1030

The script need to be added to transiflex. @jancborchardt Can you do this? Otherwise we wait for @DeepDiver1975

### PR DESCRIPTION
**Pull request by DeepDiver1975**
fixes #1031

### CODE REVIEW

**Comment by ChristophWurst** [comment]
:+1:  Nice! This means we can also delete https://github.com/owncloud/mail/blob/master/translations.js

**Comment by DeepDiver1975** [comment]
> :+1: Nice! This means we can also delete https://github.com/owncloud/mail/blob/master/translations.js

an be put to gitignore I assume?

**Comment by DeepDiver1975** [comment]
Works - merging

**Comment by ChristophWurst** [comment]
> an be put to gitignore I assume?

Exactly. Thanks!

**Pull request merged**
