### PR TITLE
open first mailbox when clicking the account's email address

### PR DESCRIPTION
**Pull request by ChristophWurst**
While switching between different account's inboxes, I found myself clicking on the account name instead of the 'inbox' mailbox. Hence, I thought we could load the first mailbox of the account in that situation, which most likely is the inbox of that account.

@jancborchardt @skjnldsv what do you think?

Not sure if we should also change the cursor accordingly.

### CODE REVIEW

**Comment by jancborchardt** [comment]
Makes perfect sense indeed. :)

Trying this out with 2 accounts, it doesn't seem to work though. The account names / email addresses are not clickable or nothing happens.

**Comment by ChristophWurst** [comment]
Tested again with single and two accounts: works as expected on FF and Chromium. The account email address is clickable (although the cursor does not change) and the first mailbox is loaded. If the inbox is selected already, the mailbox is reloaded.
Please have a look at your browser's debugging console. Do you see any logs/errors?

**Comment by Gomez** [comment]
Works for me. :+1:

**Comment by jancborchardt** [comment]
Ahhh … guess I forgot to run make on this one. ;)

**Pull request merged**
