### PR TITLE
Abort message loading when the composer is being shown

### LINKED ISSUE #708: Message is loaded/rendered although 'New message' button was clicked
I found another timing issue: When you click the 'New message' button while a message is loaded, the composer is shown shortly and then replaced by the message.

Steps to reproduce:
- click a message in the message list
- while the message loads (spinner visible), click the 'New message' button
- the composer is shown shortly, but then replaced by the clicked message

Expected behavior:
The message load request is aborted and the composer view is shown

### PR DESCRIPTION
**Pull request by wurstchristoph**
fixes #708

### CODE REVIEW

**Comment by irgendwie** [comment]
Problem:

If you click on a message (doesn't matter if it's text or html) and quickly click the "New message" Button, the spinner is **not** removed.
Meaning, you click the "New message" Button, before even the layout is loaded.

**Comment by wurstchristoph** [comment]
@irgendwie It _should_ be fixed now

**Comment by wurstchristoph** [comment]
@irgendwie @jancborchardt 
I updated the commit and fixed another issue: when clicking through messages fast, they are all rendered after each other when the request finishes. Previous message loading request should be aborted

**Comment by jancborchardt** [comment]
:+1: looks good to me. :)

**Comment by jancborchardt** [comment]
@irgendwie @Henni @colmoneill we need another review here. :)

**Comment by colmoneill** [comment]
Yep this works great. :+1:

**Pull request merged**
