### PR TITLE
fix placement of reply button, ref #900

### PR DESCRIPTION
**Pull request by jancborchardt**
Fix https://github.com/owncloud/mail/issues/900 and https://github.com/owncloud/mail/issues/1252, cc @Bullnados @tobiasKaminsky for review.

What’s missing (cc @Gomez): When the reply button is disabled, clicking it should scroll down to the reply box and focus it as well.

### CODE REVIEW

**Comment by Bullnados** [comment]
great :)
but atm i cant review it. Have lost focus on OC.

**Comment by Gomez** [comment]
@ChristophWurst Events don't get fired on disabled inputs. I used this before, you know something better? http://stackoverflow.com/a/3100395/4046794

**Comment by jancborchardt** [comment]
Any idea on this? JS wizardry needed @Henni @raimund-schluessler @MorrisJobke

**Comment by Gomez** [comment]
Sorry @jancborchardt. I have done work here. Its just css wizardry now. Check it out and test it, i think you will see the problem.

**Pull request merged**
