### PR TITLE
Updated regex for URL detection. Updates #641

### PR DESCRIPTION
**Pull request by jcbrand**
This regex takes a bit of a different approach. Instead of matching allowed
characters, it instead checks that disallowed characters are not present.

Here's the regex:
```/(ht|f)tp(s?)\:\/\/[a-zA-Z0-9\-\._]+(\:[0-9]+)?(\/[^!*';:@&=+$,?#\ \]]*)*(\?[^!*';:\=@&+$,?#\ \]]+=[^!*';:\=@&$?#\ \]]+(&[^!*';:\=@&+$,?#\ \]]+=[^!*';:\=@&+$?#\ \]]*)*)?(\#\!?[^!*';:@&$,?#\ \]]*)?/```

Breaking it down (the URL spec is [here](http://www.w3.org/Addressing/URL/url-spec.txt) ):

/
`(ht|f)tp(s?)\:`      The scheme (or protocol) with the colon that separates the scheme from the rest of the URL., Matches `http:` or `ftp:` or `https:` or `ftps:`
`\/\/`               This matches the double slash which indicates the start of internet protocol parts.
`[a-zA-Z0-9\-\._]+`   The Internet domain name or IP adresss (e.g. www.google.com, localhost, 192.168.1.1 )
`(\:[0-9]+)?`         The optional port number preceded by a colon (e.g. :8080)
`(\/)?([^!*';:@&=+$,?#\ \]]*)` The path. (e.g. Addressing/URL/url-spec.txt )
`(`
    `\?[^!*';:\=@&+$,?%#\ \]]+=[^!*';:\=@&$?#\ \]]+`    This matches the first URL paremeter (e.g. ?a=3).
    `(&[^!*';:\=@&+$,?%#\ \]]+=[^!*';:\=@&$?#\ \]]+)*` This matches subsequent URL parameters (e.g. &x=2&z=7)
`)?`                  This says that the URL parameters are optional.
`(\#\!?[^!*';:@&$,?#\ \]]*)?`    This matches zero or one document fragments and shebangs (e.g. #section or #!shebang )
/

The regex is very long and you might notice that there are certain clauses that are repeated, such as `[^!*';:\=@&$?#\ \]]+`.

I don't know much about using regexes in PHP, perhaps these clauses could be labeled or put in variables so that the regex could be made shorter?

I'll leave that to someone else who knows better about how that could be done.

P.S. I tested this regex here: https://regex101.com

The unmatched regexes reported in #641 worked there.

### CODE REVIEW

**Comment by jcbrand** [comment]
I see there's already some URLs in the tests that aren't matched. I submit a fix for that later, but now I first have to get back to other work.

**Comment by DeepDiver1975** [comment]
Looks like there are issues with : and =


````
1) OCA\Mail\Tests\Service\HtmlTest::testLinkDetection with data set #7 ('<a href="https://build.opensu...=1</a>', 'https://build.opensuse.org/pa...pand=1')

Failed asserting that two strings are identical.

--- Expected

+++ Actual

@@ @@

-<a href="https://build.opensuse.org/package/view_file/isv:ownCloud:community:7.0/owncloud/debian.changelog?expand=1" target="_blank" rel="noreferrer">https://build.opensuse.org/package/view_file/isv:ownCloud:community:7.0/owncloud/debian.changelog?expand=1</a>

+<a href="https://build.opensuse.org/package/view_file/isv" target="_blank" rel="noreferrer">https://build.opensuse.org/package/view_file/isv</a>:ownCloud:community:7.0/owncloud/debian.changelog?expand=1

/home/travis/build/owncloud/core/apps/mail/tests/service/htmltest.php:27

2) OCA\Mail\Tests\Service\HtmlTest::testLinkDetection with data set #8 ('(<a href="https://build.opens...1</a>)', '(https://build.opensuse.org/p...and=1)')

Failed asserting that two strings are identical.

--- Expected

+++ Actual

@@ @@

-(<a href="https://build.opensuse.org/package/view_file/isv:ownCloud:community:7.0/owncloud/debian.changelog?expand=1" target="_blank" rel="noreferrer">https://build.opensuse.org/package/view_file/isv:ownCloud:community:7.0/owncloud/debian.changelog?expand=1</a>)

+(<a href="https://build.opensuse.org/package/view_file/isv" target="_blank" rel="noreferrer">https://build.opensuse.org/package/view_file/isv</a>:ownCloud:community:7.0/owncloud/debian.changelog?expand=1)

/home/travis/build/owncloud/core/apps/mail/tests/service/htmltest.php:27

3) OCA\Mail\Tests\Service\HtmlTest::testLinkDetection with data set #11 ('<a href="http://www.amazon.de...er</a>', 'http://www.amazon.de/s/ref=nb...+Laser')

Failed asserting that two strings are identical.

--- Expected

+++ Actual

@@ @@

-<a href="http://www.amazon.de/s/ref=nb_sb_noss?__mk_de_DE=%C3%85M%C3%85%C5%BD%C3%95%C3%91&url=search-alias%3Daps&field-keywords=Fax%2C+Kopierer+scanner+Laser&rh=i%3Aaps%2Ck%3AFax%5Cc+Kopierer+scanner+Laser" target="_blank" rel="noreferrer">http://www.amazon.de/s/ref=nb_sb_noss?__mk_de_DE=%C3%85M%C3%85%C5%BD%C3%95%C3%91&url=search-alias%3Daps&field-keywords=Fax%2C+Kopierer+scanner+Laser&rh=i%3Aaps%2Ck%3AFax%5Cc+Kopierer+scanner+Laser</a>

+<a href="http://www.amazon.de/s/ref" target="_blank" rel="noreferrer">http://www.amazon.de/s/ref</a>=nb_sb_noss?__mk_de_DE=%C3%85M%C3%85%C5%BD%C3%95%C3%91&url=search-alias%3Daps&field-keywords=Fax%2C+Kopierer+scanner+Laser&rh=i%3Aaps%2Ck%3AFax%5Cc+Kopierer+scanner+Laser

/home/travis/build/owncloud/core/apps/mail/tests/service/htmltest.php:27

**Comment by jcbrand** [comment]
@DeepDiver1975 Yes, shouldn't be hard to fix, the check is a bit too strict it seems. I'll have to get back to it a bit later because I don't have more time right.

**Comment by jcbrand** [comment]
The tests now pass. I think it would be a good idea to also add tests for the URLs mentioned in #641.

I'm willing to do this if no one else does, but I'd need some time to figure the testing story out.

**Comment by Gomez** [comment]
Awesome work!
Just add the URL here: https://github.com/owncloud/mail/blob/master/tests/service/htmltest.php#L43
Thats it right @DeepDiver1975 @ChristophWurst ?

**Comment by DeepDiver1975** [comment]
> Just add the URLs here: https://github.com/owncloud/mail/blob/master/tests/service/htmltest.php#L43
> Thats it right @DeepDiver1975 @ChristophWurst ?

yes

**Comment by Gomez** [comment]
Thanks @jcbrand its merged! :)

**Comment by jcbrand** [comment]
Super! My first owncloud contribution :)

**Comment by jancborchardt** [comment]
Awww yeah – and it was in the Mail app. ;) You need to come to the [ownCloud Conf](https://owncloud.org/conf/) now :D

**Comment by jcbrand** [comment]
Thanks! Can't guarantee that I'd go yet, but I've added it to my calendar.

**Pull request closed without merging**
