### PR TITLE
prefill cc field

### LINKED ISSUE #609: Regression: cc field not prefilled on replies
Heyhey @wurstchristoph it seems your commit e97e87480a856c33cbc0e7431fb9eabcf9357393 broke the display/prefill of cc when replying. ;) The field is shown, but not correctly filled in.

cc @DeepDiver1975

### PR DESCRIPTION
**Pull request by wurstchristoph**
fixes #609

### CODE REVIEW

**Comment by jancborchardt** [comment]
Nice, works! :+1:

I only wonder how the commit of yours I mentioned in #609 caused that problem. :D

**Comment by clementhk** [comment]
Hi,

Problem with this pr is that cc from local storage draft will no longer be filled.

**Comment by clementhk** [comment]
IMO you need to also make local storage draft use list in cc then fill in replyCcList.

**Comment by jancborchardt** [comment]
@wurstchristoph can you fix that what @clementhk noted? Thanks! :)

@clementhk good catch!

**Pull request merged**
