### PR TITLE
[WIP] cache message list and messages locally

### PR DESCRIPTION
**Pull request by wurstchristoph**
As described in #480 it is a great performance boost to cache messages locally.
Since IMAP messages have an unique UID, messages can be cached without ever needing to update them.

# Current progress
- [ ] cache message list
- [x] cache messages
- [ ] get rid of old messages (ttl)

### CODE REVIEW

**Comment by jancborchardt** [comment]
Whoo, great stuff! :) Let me know as soon as the message list is cached as well and I’ll test.

**Comment by jancborchardt** [comment]
@wurstchristoph so we’re actually thinking about reverting the caching for the accounts/folders list  #501 because it caused so many issues.

Maybe better something for 0.2? What do you think @DeepDiver1975 @wurstchristoph @zinks- @Gomez @Xenopathic @PoPoutdoor everyone?

**Comment by Xenopathic** [comment]
Looking at the facts:

* Caching breaks deleting accounts, and is reported to break on creation of accounts.
* oC Mail 0.1 is due to be released in 11 days time
* The issue report has been around for a while, and no obvious fix has been found

I vote for reverting until after 0.1

**Comment by jancborchardt** [comment]
Disabled caching for now via https://github.com/owncloud/mail/pull/536

**Comment by wurstchristoph** [comment]
I also think it's a good idea to move this to 0.2

**Comment by jancborchardt** [comment]
@wurstchristoph you mentioned on IRC you feel this is outdated and want to close it. That’s fine – just go ahead as we have https://github.com/owncloud/mail/issues/480 to track the general feature. :) Maybe also update that with your findings and how we could proceed better,

**Pull request closed without merging**
