### PR TITLE
replace deprecated Util::getServerHost, Util::getServerProtocol

### LINKED ISSUE #1199: Replace deprecated util methods
We're using some deprecated util methods of the owncloud core:
- [ ] ``Util::formatDate`` (not yet removed)
- [ ] ``Util::imagePath`` (not yet removed, https://github.com/owncloud/core/pull/21844)
- [x] ``Util::getServerProtocol`` (not yet removed)
- [x] ``Util::getServerHost`` (not yet removed)

### PR DESCRIPTION
**Pull request by ChristophWurst**
partially fixes #1199

### CODE REVIEW

**Comment by ChristophWurst** [comment]
This is yet another method that has been deprecated and removed, but the replacement is not available for all core versions we support: https://github.com/owncloud/core/blob/188acd5e4e4bf9e35e327ecf8389c75ead744732/lib/public/irequest.php#L162-L168

**Comment by DeepDiver1975** [comment]
> This is yet another method that has been deprecated and removed

this is why travis is failing on oc7 and oc8 .... I see these options:
- keep the current code until we only support oc8.1+
- introduce a version dependent code base for these calls

**Comment by ChristophWurst** [comment]
Ok, let's go for the easier one and replace those method calls later. Moving to 0.4

**Comment by ChristophWurst** [comment]
I added a version-hack like in #1247

**Comment by Gomez** [comment]
This needs a rebase. Lets run travis again..

**Comment by ChristophWurst** [comment]
> This needs a rebase. Lets run travis again..

done

**Pull request merged**
