### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by clementhk**
@DeepDiver1975

I was wrong in your pr, that it is using guessBestMailBox() already, but here's some cleanup during the read through.
Feel free to reject it as it has nothing to do with fixing, but just some small optimizes.

### CODE REVIEW

**Comment by clementhk** [comment]
You might need to review it per commit as I wrote it from master then rebased it on top of yours.

**Comment by Xenopathic** [comment]
Per commit that looks good, but I think the history got a bit messed up. Could you submit a new PR (or try git magic on this PR if you feel brave!), with your changes merged into one commit? I know they are unrelated changes, but they all fall under the banner of 'Cleanup', so one commit will suffice :smile:

**Comment by clementhk** [comment]
Here you go.

**Comment by Xenopathic** [comment]
@clementhk You've got some other commits in there. Problem is, this can't be merged until #588 is merged, and you won't be able to have a good history until that is merged either. I'd suggest waiting for that to get merged, then rebasing this on top of master again.

**Comment by clementhk** [comment]
Yeah, that's why this is push towards #588 branch, not master. If this will not get merged into that branch then I'll make a new one towards master. 
Thanks for your review.

**Comment by Xenopathic** [comment]
AHH, I see. So used to seeing merged to master :laughing: That still doesn't explain those phantom commits though...

**Comment by clementhk** [comment]
That's what happen if you write it on top of master then rebase it on top of another branch that is from an older master. All unrelated from newer master commits will join.

**Comment by clementhk** [comment]
I'll make a new pr so there's no confusion once I get on my laptop.

**Comment by jancborchardt** [comment]
Great! :)

**Comment by jancborchardt** [comment]
Follow-up at https://github.com/owncloud/mail/pull/610

**Pull request closed without merging**
