### PR TITLE
refactor autoconfig

### PR DESCRIPTION
**Pull request by ChristophWurst**
- [x] split class into multiple classes
- [x] ~~make testable~~
- [x] ~~add unit tests~~

This PR is already pretty big. Let's add tests in another one ;-)

@clementhk @DeepDiver1975 @Gomez @irgendwie @itheiss @Xenopathic review and test this please :-)

### CODE REVIEW

**Comment by Gomez** [comment]
Got this, on my own domain, which is not in Mozilla DB:
```
{"reqId":"sbxNyLKhcbK0lJtWeQ37","remoteAddr":"127.0.0.1","app":"PHP","message":"Call to undefined method OCA\\Mail\\Service\\AutoConfig\\SmtpServerDetector::getMxRecord() at \/home\/gomez\/public_html\/mail_dev\/core\/apps\/mail\/lib\/service\/autoconfig\/smtpserverdetector.php#51","level":3,"time":"2015-09-26T08:50:25+00:00"}
```

**Comment by ChristophWurst** [comment]
@Gomez good catch!

Should be fixed now. Please test again ;-)

**Comment by Gomez** [comment]
Not found:
```
{"reqId":"6edad4dd8a1acc154f9fcf2664860c50","remoteAddr":"127.0.0.1","app":"PHP","message":"Class 'OCA\\Mail\\Service\\AutoConfig\\Account' not found at \/home\/gomez\/public_html\/mail_dev\/core\/apps\/mail\/lib\/service\/autoconfig\/smtpconnectivitytester.php#81","level":3,"time":"2015-10-02T09:06:44+00:00"}
```

**Comment by ChristophWurst** [comment]
Whoops, I forgot that. Could you please test this again? I tested it with my accounts, couldn't find bugs there – there are many paths autoconfig can possibly take depending on the account you use for testing…

**Comment by Gomez** [comment]
:+1:

**Pull request merged**
