### PR TITLE
add requirejs optimizer for packaging

### PR DESCRIPTION
**Pull request by ChristophWurst**
basically this is groundwork for packaging the next release, see #981

@DeepDiver1975 @Gomez @irgendwie @jakobsack @jancborchardt  @zinks- 

With this PR we can optimize the packaged version of this app by putting all dependencies into a single file. This includes all the JavaScript and Template (HTML) files.

As running the optimizer is a task for packaging, I added the ``r.js`` call to our ``Makefile``. To separate between development and production environment, the only thing that came up my mind was the ``DEBUG`` setting of ownCloud. Therefore I use this variable to determine whether to include the optimized version or load any file asynchronously.
I still don't think that's the perfect, way… I'm sure someone will try to use the app with ``DEBUG`` set to true and no optimized file generated.

If anybody has an solution for the above problem, let me know ;-)

### CODE REVIEW

**Comment by ChristophWurst** [comment]
btw: when using the optimized version, about 55 fewer requests are needed for loading the app :rocket:

**Comment by Gomez** [comment]
Cool. 
I dont have installed bower globally, the Makescript failed. Would be better if we only depend on npm and use the rest from the project dir?

**Comment by ChristophWurst** [comment]
> Would be better if we only depend on npm and use the rest from the project dir?

Sure, makes sense. I updated my commit. Please test again ;-)

**Comment by Gomez** [comment]
:+1:

**Pull request merged**
