### PR TITLE
resize textarea when content was changed programmatically

### LINKED ISSUE #582: Encrypted text inserted by Mailvelope does not resize textarea nor activate send button
There’s a slight issue with Mailvelope we need to look into: The message text pasted into the textarea does not result in the textarea being resized nor the send button being activated:
capture du 2015-05-04 12 28 30

### PR DESCRIPTION
**Pull request by wurstchristoph**
fixes #582 
@aidanamavi @irgendwie @jancborchardt please review

If anybody knows a better way of detecting programmatic changes of textareas, please let me know :-)

### CODE REVIEW

**Comment by jancborchardt** [comment]
@wurstchristoph testing with the original Mailvelope problem, it doesn’t fully work yet. Only as soon as I click into the textarea again, it expands.

**Comment by aidanamavi** [comment]
@jancborchardt I'm tidying up some code based on the recent PR by @wurstchristoph which fixes and enhances his code. I'll have it pushed in an hour or so.

**Comment by jancborchardt** [comment]
@aidanamavi great! Now that you’re both in the ownCloud org it means that you can both work on this branch and directly just collaborate. :)

**Comment by jancborchardt** [comment]
Moving to 0.3 as it only happens with Mailvelope. If you can manage it for 0.2 that’s cool though. :)

**Comment by aidanamavi** [comment]
Reviews, please. @jancborchardt @irgendwie @wurstchristoph @DeepDiver1975 @zinks-

**Comment by aidanamavi** [comment]
To review the newest changes, please see pull #800.

**Comment by wurstchristoph** [comment]
closing this in favor of #800

**Pull request closed without merging**
