### PR TITLE
if manual setup is open, close it after successful connection, fix #331

### LINKED ISSUE #331: Failed advanced account creation breaks interface
When adding an account using the advanced configuration options, the top password box disappears since there are two separate IMAP and SMTP passwords instead. However, if creating that account fails, the advanced settings dialog closes, but the top password box does not return. Opening advanced configuration brings that password box back, at least until the advanced configuration is closed again.

A fix would be to not close advanced settings when adding the account fails.

### PR DESCRIPTION
**Pull request by jancborchardt**
This moves the manual setup toggle code into a function. Also fixes #331 in that the manual setup area is only closed on successful connection.

Please test @Xenopathic @zinks- @PoPoutdoor 

And have a look at the code @DeepDiver1975 ;)

### CODE REVIEW

**Comment by Xenopathic** [comment]
The manual setup no longer closes if creating the account failed, which is good, but I seem to be unable to test a successful manual setup due to other issues (I'm getting 400 Bad Request). Is it necessary to explicitly close the manual setup if creating the account succeeded though? I thought that the display immediately changes to something else anyway, so surely it is unneeded and will never be seen?

**Comment by Xenopathic** [comment]
Marking as priority as it is very user-unfriendly and confusing. Please rebase :smile:

**Comment by jancborchardt** [comment]
Manually rebased the current state in https://github.com/owncloud/mail/pull/504

**Comment by jancborchardt** [comment]
@Xenopathic btw, the 400 bad request might be related to https://github.com/owncloud/mail/issues/330 – a fix is available at https://github.com/owncloud/mail/pull/436, can you test that?

**Pull request closed without merging**
