### PR TITLE
fix getSpecialFolder(), ref #444

### LINKED ISSUE #444: Cannot connect to gmail account
I pulled master to the apps directory, set the correct user/group, installed the missing dependencies in the mail app folder using composer.phar, changed user/group accordingly, activated the mail app and tried to insert the desired data. Tried both: automatic and manual. Tried both: gmail and googlemail address. No result with the automatic method, 'bad request' result with the manual method.

Settings:  imap.gmail.com, 993, SSL, user=email, password and smtp.gmail.com, 465, SSL, user=email, password

Log:

{"reqId":"b9c79b324f141edc05f12821f5c9e976","remoteAddr":"xxxxx","app":"mail","message":"Setting up manually configured account","level":1,"time":"2015-04-02T08:12:53+00:00","method":"POST","url":"\/owncloud\/index.php\/apps\/mail\/accounts"}
{"reqId":"b9c79b324f141edc05f12821f5c9e976","remoteAddr":"xxxxx","app":"mail","message":"Connecting to imap","level":0,"time":"2015-04-02T08:12:53+00:00","method":"POST","url":"\/owncloud\/index.php\/apps\/mail\/accounts"}
{"reqId":"b9c79b324f141edc05f12821f5c9e976","remoteAddr":"xxxxx","app":"mail","message":"Creating account failed: Error when communicating with the mail server.","level":3,"time":"2015-04-02T08:13:03+00:00","method":"POST","url":"\/owncloud\/index.php\/apps\/mail\/accounts"}

### PR DESCRIPTION
**Pull request by clementhk**
I'm not so sure about the coding style, but this sure fixed the problem. Fix #444 (Cannot connect to Gmail account)

### CODE REVIEW

**Comment by jancborchardt** [comment]
@clementhk woo, thank you for the pull request! :)

@marlemion @wurstchristoph @Xenopathic can you please test if this fixes #444 for you?

**Comment by marlemion** [comment]
Something went wrong. First it didn't load the previoudly working, non-gmail accounts anymore. So I deleted all accounts and readded the gmail accounts. After that it gets added, but all columns stay blank and the little ccircles in the middle and right column keep rotating forever.

{"reqId":"0f97f923e822d4662b861c7d726173f7","remoteAddr":"80.137.89.104","app":"mail","message":"Setting up manually configured account","level":1,"time":"2015-04-25T14:49:05+00:00","method":"POST","url":"\/owncloud\/index.php\/apps\/mail\/accounts"}
{"reqId":"0f97f923e822d4662b861c7d726173f7","remoteAddr":"80.137.89.104","app":"mail","message":"Connecting to imap","level":0,"time":"2015-04-25T14:49:05+00:00","method":"POST","url":"\/owncloud\/index.php\/apps\/mail\/accounts"}
{"reqId":"0f97f923e822d4662b861c7d726173f7","remoteAddr":"80.137.89.104","app":"mail","message":"Connecting to smtp","level":0,"time":"2015-04-25T14:49:06+00:00","method":"POST","url":"\/owncloud\/index.php\/apps\/mail\/accounts"}
{"reqId":"0f97f923e822d4662b861c7d726173f7","remoteAddr":"80.137.89.104","app":"mail","message":"account created 11","level":0,"time":"2015-04-25T14:49:07+00:00","method":"POST","url":"\/owncloud\/index.php\/apps\/mail\/accounts"}
{"reqId":"5e6536315eb721d3adf4957373c505d3","remoteAddr":"80.137.89.104","app":"PHP","message":"Call to a member function getFolderId() on null at \/var\/www\/localhost\/htdocs\/owncloud\/apps\/mail\/lib\/account.php#223","level":3,"time":"2015-04-25T14:49:11+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/mail\/accounts\/11\/folders"}
{"reqId":"84cedc4a317b0b5f9afc5b8fd525d881","remoteAddr":"80.137.89.104","app":"PHP","message":"Call to a member function getFolderId() on null at \/var\/www\/localhost\/htdocs\/owncloud\/apps\/mail\/lib\/account.php#223","level":3,"time":"2015-04-25T14:49:14+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/mail\/accounts\/11\/folders"}
{"reqId":"8f2d2b798093ea8e05240a4c7419fac8","remoteAddr":"80.137.89.104","app":"carddav","message":"Exception: {\"Message\":\"No basic authentication headers were found\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(126): Sabre\\\\DAV\\\\Auth\\\\Backend\\\\AbstractBasic->authenticate(Object(Sabre\\\\DAV\\\\Server), 'ownCloud')\\n#1 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(106): OC_Connector_Sabre_Auth->auth(Object(Sabre\\\\DAV\\\\Server), 'ownCloud')\\n#2 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Auth\\\/Plugin.php(108): OC_Connector_Sabre_Auth->authenticate(Object(Sabre\\\\DAV\\\\Server), 'ownCloud')\\n#3 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod('PROPFIND', '')\\n#4 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Server.php(433): call_user_func_array(Array, Array)\\n#5 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Server.php(455): Sabre\\\\DAV\\\\Server->broadcastEvent('beforeMethod', Array)\\n#6 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Server.php(214): Sabre\\\\DAV\\\\Server->invokeMethod('PROPFIND', '')\\n#7 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/apps\\\/contacts\\\/appinfo\\\/remote.php(88): Sabre\\\\DAV\\\\Server->exec()\\n#8 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/remote.php(54): require_once('\\\/var\\\/www\\\/localh...')\\n#9 {main}\",\"File\":\"\\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Auth\\\/Backend\\\/AbstractBasic.php\",\"Line\":73}","level":0,"time":"2015-04-25T14:50:04+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/carddav\/"}
{"reqId":"1bc966096148e095f60218695cefa85d","remoteAddr":"80.137.89.104","app":"carddav","message":"Exception: {\"Message\":\"No basic authentication headers were found\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(126): Sabre\\\\DAV\\\\Auth\\\\Backend\\\\AbstractBasic->authenticate(Object(Sabre\\\\DAV\\\\Server), 'ownCloud')\\n#1 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(106): OC_Connector_Sabre_Auth->auth(Object(Sabre\\\\DAV\\\\Server), 'ownCloud')\\n#2 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Auth\\\/Plugin.php(108): OC_Connector_Sabre_Auth->authenticate(Object(Sabre\\\\DAV\\\\Server), 'ownCloud')\\n#3 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod('PROPFIND', 'principals\\\/eger')\\n#4 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Server.php(433): call_user_func_array(Array, Array)\\n#5 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Server.php(455): Sabre\\\\DAV\\\\Server->broadcastEvent('beforeMethod', Array)\\n#6 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Server.php(214): Sabre\\\\DAV\\\\Server->invokeMethod('PROPFIND', 'principals\\\/eger')\\n#7 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/apps\\\/contacts\\\/appinfo\\\/remote.php(88): Sabre\\\\DAV\\\\Server->exec()\\n#8 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/remote.php(54): require_once('\\\/var\\\/www\\\/localh...')\\n#9 {main}\",\"File\":\"\\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Auth\\\/Backend\\\/AbstractBasic.php\",\"Line\":73}","level":0,"time":"2015-04-25T14:50:05+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/carddav\/principals\/eger\/"}
{"reqId":"30a0869bdc86f15c8742a3f8a026e5aa","remoteAddr":"80.137.89.104","app":"carddav","message":"Exception: {\"Message\":\"No basic authentication headers were found\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(126): Sabre\\\\DAV\\\\Auth\\\\Backend\\\\AbstractBasic->authenticate(Object(Sabre\\\\DAV\\\\Server), 'ownCloud')\\n#1 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(106): OC_Connector_Sabre_Auth->auth(Object(Sabre\\\\DAV\\\\Server), 'ownCloud')\\n#2 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Auth\\\/Plugin.php(108): OC_Connector_Sabre_Auth->authenticate(Object(Sabre\\\\DAV\\\\Server), 'ownCloud')\\n#3 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod('PROPFIND', 'addressbooks\\\/eg...')\\n#4 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Server.php(433): call_user_func_array(Array, Array)\\n#5 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Server.php(455): Sabre\\\\DAV\\\\Server->broadcastEvent('beforeMethod', Array)\\n#6 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Server.php(214): Sabre\\\\DAV\\\\Server->invokeMethod('PROPFIND', 'addressbooks\\\/eg...')\\n#7 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/apps\\\/contacts\\\/appinfo\\\/remote.php(88): Sabre\\\\DAV\\\\Server->exec()\\n#8 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/remote.php(54): require_once('\\\/var\\\/www\\\/localh...')\\n#9 {main}\",\"File\":\"\\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Auth\\\/Backend\\\/AbstractBasic.php\",\"Line\":73}","level":0,"time":"2015-04-25T14:50:06+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/carddav\/addressbooks\/eger\/"}
{"reqId":"509f9d686857c15d7d34182d6bd4f8ab","remoteAddr":"80.137.89.104","app":"carddav","message":"Exception: {\"Message\":\"No basic authentication headers were found\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(126): Sabre\\\\DAV\\\\Auth\\\\Backend\\\\AbstractBasic->authenticate(Object(Sabre\\\\DAV\\\\Server), 'ownCloud')\\n#1 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(106): OC_Connector_Sabre_Auth->auth(Object(Sabre\\\\DAV\\\\Server), 'ownCloud')\\n#2 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Auth\\\/Plugin.php(108): OC_Connector_Sabre_Auth->authenticate(Object(Sabre\\\\DAV\\\\Server), 'ownCloud')\\n#3 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod('PROPFIND', 'addressbooks\\\/eg...')\\n#4 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Server.php(433): call_user_func_array(Array, Array)\\n#5 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Server.php(455): Sabre\\\\DAV\\\\Server->broadcastEvent('beforeMethod', Array)\\n#6 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Server.php(214): Sabre\\\\DAV\\\\Server->invokeMethod('PROPFIND', 'addressbooks\\\/eg...')\\n#7 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/apps\\\/contacts\\\/appinfo\\\/remote.php(88): Sabre\\\\DAV\\\\Server->exec()\\n#8 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/remote.php(54): require_once('\\\/var\\\/www\\\/localh...')\\n#9 {main}\",\"File\":\"\\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Auth\\\/Backend\\\/AbstractBasic.php\",\"Line\":73}","level":0,"time":"2015-04-25T14:50:07+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/carddav\/addressbooks\/eger\/kontakte\/"}

**Comment by clementhk** [comment]
@marlemion are you sure it has nothing to do with https://github.com/owncloud/mail/pull/510 ? Can you also try it on a fresh master?

**Comment by jancborchardt** [comment]
@marlemion please reset the app first: https://github.com/owncloud/mail#resetting-the-app :) Probably the problem lies with the password or with caching.

**Comment by Xenopathic** [comment]
Code makes sense :+1:

**Comment by marlemion** [comment]
I reset the database and repulled mail plus the php stuff. Still same symptoms.

**Comment by clementhk** [comment]
You have put this in your browser? `localStorage.clear();`

**Comment by marlemion** [comment]
Where should I put this in my browser?

**Comment by jancborchardt** [comment]
@marlemion press Ctrl+Shift+j to bring up the browser console, then paste that in and press enter. It should say »undefined« but that’s ok. Then reload the page (ideally with clearing the cache by pressing Ctrl+Shift+r). Then try again.

**Comment by clementhk** [comment]
Put it in developer console.

@jancborchardt I hope you guys can put this somewhere clearer so people can just click it instead of trying to run it in the browser.

**Comment by clementhk** [comment]
@marlemion (maybe you could use a different browser to test it if you cannot find where to execute that js)

**Comment by jancborchardt** [comment]
@clementhk well, ideally it doesn’t need to be done. And it’s just a remnant of the caching that was there – new users won’t experience this issue.

**Comment by marlemion** [comment]
I have tried opera - same issue. Konqueror seems to have some more problems with the mail app.

The console popped up in firefox (my default browser), but I could neither type nor paste in it.

**Comment by jancborchardt** [comment]
@clementhk can you rebase this onto master? Maybe some issues were fixed there.

@wurstchristoph @Xenopathic can you also test this, since you reported #444 as well?

**Comment by Xenopathic** [comment]
Well, the changes make sense. :+1: My gmail setup is working prior to this though...

**Comment by jancborchardt** [comment]
Ok, then if @DeepDiver1975, @wurstchristoph or @irgendwie say this change works we can merge it in.

**Comment by clementhk** [comment]
I'll send a pr to horde to fix this problem for good.

**Comment by wurstchristoph** [comment]
issue #444 seems to be resolved already.

Changing ```> 0``` to ```> 1``` makes sense anyway :+1:

**Comment by Xenopathic** [comment]
CI isn't happy about the encrypted credentials. @jancborchardt @DeepDiver1975 Ready for merge?

**Pull request merged**
