### PR TITLE
Bower sync

### PR DESCRIPTION
**Pull request by itheiss**

### CODE REVIEW

**Comment by jancborchardt** [comment]
@itheiss what was this? ;D

**Comment by itheiss** [comment]
Are you spying me ;D Tried to merge the Bower branch into my repository. But I was to stupid :-((

**Comment by jancborchardt** [comment]
@itheiss well I get notifications about pull requests. :D Any contributions are welcome, if you need help just join us in our #owncloud-mail IRC channel.

**Comment by ChristophWurst** [comment]
@itheiss maybe that helps: https://help.github.com/articles/syncing-a-fork/ ;-)

**Pull request closed without merging**
