### PR TITLE
restore setup view state only on error

### LINKED ISSUE #1565: TypeError: _this.ui.iconLoading.hide is not a function
Happens while adding a (second) account:
bildschirmfoto von 2016-07-17 16-37-13

### PR DESCRIPTION
**Pull request by ChristophWurst**
if the setup was successful, we replace the setup view with a loading view.

fixes #1565

### CODE REVIEW

**Comment by ChristophWurst** [comment]
blocked CI-wise by https://github.com/owncloud/mail/pull/1571

**Comment by ChristophWurst** [comment]
@jancborchardt test this please

**Comment by ChristophWurst** [comment]
@owncloud/mail I need some review power on this :-)

**Comment by jancborchardt** [comment]
Do we have some @owncloud/mail folks who want to test this as well? :) Come join the fun, Mail app development is at a fast pace!

**Comment by jancborchardt** [comment]
@haseebeqx @Scheirle you up for testing this? :)

**Comment by tahaalibra** [comment]
Great, Everything works fine. Just 1 thing i want to confirm that is on adding an account B, when a previous account A is already there, then on success the loading view loads account A. After adding a new account should we load the "All Inboxes" or the New Account that is added

**Comment by ChristophWurst** [comment]
@tahaalibra good point. We shoud definitely either load the unified inbox or the newly added account

**Comment by jancborchardt** [comment]
Yeah, good point – I’d say we should load the unified inbox. :)

**Pull request merged**
