### PR TITLE
remove dots from buttons

### PR DESCRIPTION
**Pull request by ChristophWurst**
@jancborchardt as discussed

### CODE REVIEW

**Comment by itheiss** [comment]
What about the translation files e.g. l10n/de_DE.json? Will they be changed in a seperate PR?

**Comment by ChristophWurst** [comment]
> What about the translation files e.g. l10n/de_DE.json? Will they be changed in a seperate PR?

Translation is handled via Transifex, therefore we don't change those files.

**Comment by itheiss** [comment]
Oki! Does that mean "Check messages ..." and "Load more …" have to be changed directly in Transiflex to keep translations working? Still learning how everything is working ...

**Comment by ChristophWurst** [comment]
> Oki! Does that mean "Check messages ..." and "Load more …" have to be changed directly in Transiflex to keep translations working?

Yes, exactly. That might unfortunately take some time…

> Still learning how everything is working ...

No worries ;-) There's also a decent documentation on ownCloud (app) development: https://doc.owncloud.org/server/8.2/developer_manual/

**Comment by Gomez** [comment]
:+1:  Kill the dots!

**Comment by jakobsack** [comment]
:+1:

**Comment by jancborchardt** [comment]
Good detail improvement! :)

**Pull request merged**
