### PR TITLE
log why sending a new mail failed

### PR DESCRIPTION
**Pull request by wurstchristoph**
in favor of #485

### CODE REVIEW

**Comment by Xenopathic** [comment]
It'd be a good idea to log the mail ID to aid debugging

**Comment by wurstchristoph** [comment]
Do you mean something like this:

	if ($mailbox) {
		$this->logger->error('Sending a new mail failed: '
			. $ex->getMessage());
	} else {
		$this->logger->error('Sending a reply of message '
			. $messageId . ' failed: ' . $ex->getMessage());
	}

As it could be newly created mail, it doesn't necessarily have an ID at that point. Therefore an ID could only be logged if the mail is a reply

**Comment by jancborchardt** [comment]
@Henni can you test this?

**Comment by Xenopathic** [comment]
@wurstchristoph Hmm, I see how that is an issue. Ideally we need some way to identify which message caused the error, but hopefully in most cases the exception message will state everything that is needed (like 'failed to connect to mail.domain.com'). Leave it as it is for now :smile:

Oh, :+1: too

**Comment by Henni** [comment]
I checked out this pull request and it seems that it doesn't fix my problem. (#485)
There is a message in the log but it doesn't contain any additional info.
> Sending mail failed: IMAP error reported by server.

I also commented on #485 to specify my problem in more detail.

**Pull request merged**
