### PR TITLE
update horde libs

### PR DESCRIPTION
**Pull request by ChristophWurst**
- [x] TODO: test

### CODE REVIEW

**Comment by ChristophWurst** [comment]
app didn't explode while manually testing it, so I guess this is ready for another review/test of @owncloud/mail :-)

**Comment by enoch85** [comment]
I will test this when I get home.

**Comment by enoch85** [comment]
```
  - Installing pear-pear.horde.org/horde_translation (2.2.1)
    Loading from cache
  - Installing pear-pear.horde.org/horde_util (2.5.8)
    Downloading: 100%         
  - Installing pear-pear.horde.org/horde_nls (2.2.0)
    Loading from cache
  - Installing pear-pear.horde.org/horde_exception (2.0.8)
    Loading from cache
  - Installing pear-pear.horde.org/horde_date (2.3.1)
    Downloading: 100%         
  - Installing pear-pear.horde.org/horde_stream_filter (2.0.4)
    Loading from cache
  - Installing pear-pear.horde.org/horde_stream (1.6.3)
    Loading from cache
  - Installing pear-pear.horde.org/horde_socket_client (2.1.1)
    Loading from cache
  - Installing pear-pear.horde.org/horde_stream_wrapper (2.1.3)
    Loading from cache
  - Installing pear-pear.horde.org/horde_support (2.1.5)
    Loading from cache
  - Installing pear-pear.horde.org/horde_crypt_blowfish (1.1.1)
    Loading from cache
  - Installing pear-pear.horde.org/horde_secret (2.0.6)
    Loading from cache
  - Installing pear-pear.horde.org/horde_text_flowed (2.0.3)
    Loading from cache
  - Installing pear-pear.horde.org/horde_mime (2.10.0)
    Downloading: 100%         
  - Installing pear-pear.horde.org/horde_idna (1.0.4)
    Loading from cache
  - Installing pear-pear.horde.org/horde_mail (2.6.3)
    Loading from cache
  - Installing pear-pear.horde.org/horde_listheaders (1.2.4)
    Loading from cache
  - Installing pear-pear.horde.org/horde_imap_client (2.29.8)
    Downloading: 100%         
  - Installing pear-pear.horde.org/horde_smtp (1.9.3)
    Loading from cache
  - Installing pear-pear.horde.org/horde_text_filter (2.3.4)
    Loading from cache
Generating autoload files
npm install --production
npm WARN prefer global coffee-script@1.10.0 should be installed with -g
mail@0.5.3 /tmp/mail
├── bower@1.7.9 
├─┬ grunt@1.0.1 
│ ├── coffee-script@1.10.0 
│ ├─┬ dateformat@1.0.12 
│ │ ├── get-stdin@4.0.1 
│ │ └─┬ meow@3.7.0 
│ │   ├─┬ camelcase-keys@2.1.0 
│ │   │ └── camelcase@2.1.1 
│ │   ├── decamelize@1.2.0 
│ │   ├─┬ loud-rejection@1.6.0 
│ │   │ ├─┬ currently-unhandled@0.4.1 
│ │   │ │ └── array-find-index@1.0.1 
│ │   │ └── signal-exit@3.0.0 
│ │   ├── map-obj@1.0.1 
│ │   ├── minimist@1.2.0 
│ │   ├─┬ normalize-package-data@2.3.5 
│ │   │ ├── hosted-git-info@2.1.5 
│ │   │ ├─┬ is-builtin-module@1.0.0 
│ │   │ │ └── builtin-modules@1.1.1 
│ │   │ ├── semver@5.3.0 
│ │   │ └─┬ validate-npm-package-license@3.0.1 
│ │   │   ├─┬ spdx-correct@1.0.2 
│ │   │   │ └── spdx-license-ids@1.2.2 
│ │   │   └─┬ spdx-expression-parse@1.0.2 
│ │   │     └── spdx-exceptions@1.0.5 
│ │   ├── object-assign@4.1.0 
│ │   ├─┬ read-pkg-up@1.0.1 
│ │   │ ├─┬ find-up@1.1.2 
│ │   │ │ ├── path-exists@2.1.0 
│ │   │ │ └─┬ pinkie-promise@2.0.1 
│ │   │ │   └── pinkie@2.0.4 
│ │   │ └─┬ read-pkg@1.1.0 
│ │   │   ├─┬ load-json-file@1.1.0 
│ │   │   │ ├── graceful-fs@4.1.5 
│ │   │   │ ├─┬ parse-json@2.2.0 
│ │   │   │ │ └─┬ error-ex@1.3.0 
│ │   │   │ │   └── is-arrayish@0.2.1 
│ │   │   │ ├── pify@2.3.0 
│ │   │   │ └─┬ strip-bom@2.0.0 
│ │   │   │   └── is-utf8@0.2.1 
│ │   │   └── path-type@1.1.0 
│ │   ├─┬ redent@1.0.0 
│ │   │ ├─┬ indent-string@2.1.0 
│ │   │ │ └─┬ repeating@2.0.1 
│ │   │ │   └─┬ is-finite@1.0.1 
│ │   │ │     └── number-is-nan@1.0.0 
│ │   │ └── strip-indent@1.0.1 
│ │   └── trim-newlines@1.0.0 
│ ├── eventemitter2@0.4.14 
│ ├── exit@0.1.2 
│ ├─┬ findup-sync@0.3.0 
│ │ └── glob@5.0.15 
│ ├─┬ glob@7.0.5 
│ │ ├── fs.realpath@1.0.0 
│ │ ├─┬ inflight@1.0.5 
│ │ │ └── wrappy@1.0.2 
│ │ ├── inherits@2.0.1 
│ │ └── once@1.3.3 
│ ├─┬ grunt-cli@1.2.0 
│ │ └── resolve@1.1.7 
│ ├── grunt-known-options@1.1.0 
│ ├─┬ grunt-legacy-log@1.0.0 
│ │ ├── colors@1.1.2 
│ │ ├─┬ grunt-legacy-log-utils@1.0.0 
│ │ │ ├─┬ chalk@1.1.3 
│ │ │ │ ├── ansi-styles@2.2.1 
│ │ │ │ ├── escape-string-regexp@1.0.5 
│ │ │ │ ├─┬ has-ansi@2.0.0 
│ │ │ │ │ └── ansi-regex@2.0.0 
│ │ │ │ ├── strip-ansi@3.0.1 
│ │ │ │ └── supports-color@2.0.0 
│ │ │ └── lodash@4.3.0 
│ │ ├── hooker@0.2.3 
│ │ ├── lodash@3.10.1 
│ │ └── underscore.string@3.2.3 
│ ├─┬ grunt-legacy-util@1.0.0 
│ │ ├── async@1.5.2 
│ │ ├── getobject@0.1.0 
│ │ ├── lodash@4.3.0 
│ │ └─┬ which@1.2.10 
│ │   └── isexe@1.1.2 
│ ├── iconv-lite@0.4.13 
│ ├─┬ js-yaml@3.5.5 
│ │ ├─┬ argparse@1.0.7 
│ │ │ └── sprintf-js@1.0.3 
│ │ └── esprima@2.7.2 
│ ├─┬ minimatch@3.0.2 
│ │ └─┬ brace-expansion@1.1.6 
│ │   ├── balanced-match@0.4.2 
│ │   └── concat-map@0.0.1 
│ ├─┬ nopt@3.0.6 
│ │ └── abbrev@1.0.9 
│ ├── path-is-absolute@1.0.0 
│ └── rimraf@2.2.8 
└── requirejs@2.2.0
``` 

Works! :+1:

**Comment by ChristophWurst** [comment]
> Works! :+1:

What exactly did you test besides installed the dependencies?

**Comment by enoch85** [comment]
@ChristophWurst I ran my script to build the nighlty, and included this patch. It worked.

**Comment by ChristophWurst** [comment]
@owncloud/mail please test the app with the udpated horde libs. Thanks

**Comment by jancborchardt** [comment]
Stuff still seems to work :+1:

**Pull request merged**
