### PR TITLE
attachment style fixes

### PR DESCRIPTION
**Pull request by jancborchardt**
All kinds of alignment issues before:
capture du 2016-08-24 13-58-15
After:
capture du 2016-08-24 13-57-31

Please review @ChristophWurst @Gomez @DeepDiver1975 @Henni @irgendwie :)

### CODE REVIEW

**Comment by irgendwie** [comment]
LGTM :+1:

**Comment by jancborchardt** [comment]
@irgendwie awesome to have you back reviewing stuff by the way! :)

**Comment by irgendwie** [comment]
@jancborchardt I'm trying to stay active in my spare time although having a lot of work to do ;-)

**Comment by ChristophWurst** [comment]
nice!

**Pull request merged**
