### PR TITLE
Fix attachments

### LINKED ISSUE #1371: Adding attachments not working
When using the file chooser, there is an error in the JS console and no reaction in the UI:
```
Uncaught ChildViewContainerMissingError:
The specified "childViewContainer" was not found: ul
in backbone.marionette.js line 901
```

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/32260829-adding-attachments-not-working?utm_campaign=plugin&utm_content=tracker%2F216487&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F216487&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by ChristophWurst**
Replacing Backbone views with Marionette views reduces code complexity and fixes the attachments bug.

fixes #1371 

@jancborchardt @owncloud/mail

---
This change is [Reviewable](https://reviewable.io/reviews/owncloud/mail/1378)

### CODE REVIEW

**Comment by ChristophWurst** [comment]
@BenS89 could you test this please?

**Comment by ChristophWurst** [comment]
This has been tested by @BenS89, see https://github.com/owncloud/mail/issues/1380#issuecomment-203077709

@Gomez @owncloud/mail ok to merge then?

**Comment by Gomez** [comment]
Will test it soon, too.

**Comment by Gomez** [comment]
Perfect! 
@ChristophWurst Should we release 0.4.1 as this one is important? Would you add it to the Changelog?

**Comment by ChristophWurst** [comment]
> @ChristophWurst Should we release 0.4.1 as this one is important? Would you add it to the Changelog?

Yep, let's release it as 0.4.1

**Pull request merged**
