### PR TITLE
Add missing implementation of ILogger::logException()

### PR DESCRIPTION
**Pull request by DeepDiver1975**

### CODE REVIEW

**Comment by ChristophWurst** [comment]
Please also add this method to the unit tests: https://github.com/owncloud/mail/blob/master/tests/service/loggertest.php#L25-L36

**Comment by Gomez** [comment]
Does we need to add the same version_compare?

https://github.com/owncloud/mail/pull/1058/files

We need to get this in before we can merge other stuff.

**Comment by DeepDiver1975** [comment]
> Does we need to add the same version_compare?

yes - we need that on the unit test - will add ....

**Comment by DeepDiver1975** [comment]
all green -> merge

**Comment by Gomez** [comment]
perfect!

**Pull request merged**
