### PR TITLE
Fix for #1228

### PR DESCRIPTION
**Pull request by ErikPel**

### CODE REVIEW

**Comment by ChristophWurst** [comment]
From https://github.com/owncloud/mail/issues/1228#issuecomment-177316846:
> Can there be multiple tooltips shown at once without this bug or would it work if we just put (".tooltip").remove() into the delete function?

This could work as a temporary fix. Generally, it's error prone to have a jQuery selector executed on a class that might be reused in other parts of the application.
@ErikPel please also try 
```js
var _this = this;
this.$el.addClass('transparency').slideUp(function() {
    _this.$('.tipsy').remove();
    _this.$('.tooltip').remove();
```
That way the jQuery selector is scoped to the message view. That should be the way to go.

Thanks a lot for your contribution! You can join us in our IRC channel #owncloud-mail on freenode. If you need any help, let me know ;-)

**Comment by ErikPel** [comment]
@ChristophWurst 
Is there reason why there are two different
`    $('.tipsy').remove();
`
functions ran in
https://github.com/owncloud/mail/blob/master/js/views/message.js#L84
and
https://github.com/owncloud/mail/blob/master/js/views/message.js#L89
?

I changed it the way you suggested @ChristophWurst 
Is it alright now?

**Comment by ChristophWurst** [comment]
> @ChristophWurst
> Is there reason why there are two different
> $('.tipsy').remove();
> functions ran in
> https://github.com/owncloud/mail/blob/master/js/views/message.js#L84
> and
> https://github.com/owncloud/mail/blob/master/js/views/message.js#L89
> ?

That's indeed strange. I assume removing it once should be enough. I'll have a look…

**Comment by ChristophWurst** [comment]
Nope, that does not work because the tipsy is actually placed outside the message element. Therefore ``this.$(...)`` doesn't catch it.
Please change it back to ``$(...)`` by removing your last commit. Sorry for pointing you to the wrong direction :see_no_evil:

**Comment by ErikPel** [comment]
@ChristophWurst It's all good, man
Rebased to revert the change

**Comment by ChristophWurst** [comment]
:+1: perfect. Thanks for you contribution. We'll merge this PR once 0.3 has been released!

**Pull request merged**
