### PR TITLE
remove deprecated params calls; add some unit tests

### PR DESCRIPTION
**Pull request by ChristophWurst**
``$this->params(..)`` is deprecated, so I removed all the calls and added method parameters

@DeepDiver1975 @LukasReschke @Xenopathic review please :)

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
We have to test this on oc7.

**Comment by DeepDiver1975** [comment]
> yes - but we do not test appframeworks phpdoc parsing to get an understanding of parameter types - may guts feeling is telling be that this feature was not available in oc7

I love version information on our public api - https://github.com/owncloud/core/blob/master/lib/public/appframework/controller.php#L157

so this change is okay :+1:

**Comment by LukasReschke** [comment]
Ah you refered to that - stupid me :gun:

**Comment by LukasReschke** [comment]
:+1:

**Pull request merged**
