### PR TITLE
Message Backbone model/collection

### PR DESCRIPTION
**Pull request by ChristophWurst**
Messages are the only entity we do not yet manage as backbone model/collection. This is the first shot into fixing this.

The next steps will be to use backbone/horde sync to update folders.

ref #1314 

@Gomez @DeepDiver1975 @tahaalibra @irgendwie review please

### CODE REVIEW

**Comment by Gomez** [comment]
Error on deleting mails:
callstack

**Comment by ChristophWurst** [comment]
@Gomez fixed. Please test again

**Comment by Gomez** [comment]
I took over to just fix the jscs errors. Hope you dont mind :)

**Comment by ChristophWurst** [comment]
@Gomez rebased and fixed a small jasmine bug. Please re-review, I'd like to continue with this little cleanup :rocket:

**Comment by Gomez** [comment]
backbone.radio was used before, how does this work?

**Comment by ChristophWurst** [comment]
> backbone.radio was used before, how does this worked?

correct, but the dependency graph did not require to load it before. It's now a sub-dependency of a module that I touched with this PR

**Pull request merged**
