### PR TITLE
Go for php7

### LINKED ISSUE #1050: php7 compatibility
We should prepare for supporting php 7 once it's released and supported by core as some people might want to upgrade for performance reasons. At the moment horde is holding us back from running on php7, composer package install throws errors like:
```
$ composer install

Loading composer repositories with package information

Installing dependencies (including require-dev) from lock file

Your requirements could not be resolved to an installable set of packages.

  Problem 1

    - Installation request for pear-pear.horde.org/horde_crypt_blowfish 1.1.0 -> satisfiable by pear-pear.horde.org/Horde_Crypt_Blowfish[1.1.0].

    - pear-pear.horde.org/Horde_Crypt_Blowfish 1.1.0 requires php <6.0.0.0 -> your PHP version (7.0.0-dev) or "config.platform.php" value does not satisfy that requirement.

  Problem 2

    - Installation request for pear-pear.horde.org/horde_date 2.1.1 -> satisfiable by pear-pear.horde.org/Horde_Date[2.1.1].

    - pear-pear.horde.org/Horde_Date 2.1.1 requires php <6.0.0.0 -> your PHP version (7.0.0-dev) or "config.platform.php" value does not satisfy that requirement.

  Problem 3

    - Installation request for pear-pear.horde.org/horde_exception 2.0.6 -> satisfiable by pear-pear.horde.org/Horde_Exception[2.0.6].

    - pear-pear.horde.org/Horde_Exception 2.0.6 requires php <6.0.0.0 -> your PHP version (7.0.0-dev) or "config.platform.php" value does not satisfy that requirement.

  Problem 4

    - Installation request for pear-pear.horde.org/horde_idna 1.0.3 -> satisfiable by pear-pear.horde.org/Horde_Idna[1.0.3].

    - pear-pear.horde.org/Horde_Idna 1.0.3 requires php <6.0.0.0 -> your PHP version (7.0.0-dev) or "config.platform.php" value does not satisfy that requirement.

  Problem 5

    - Installation request for pear-pear.horde.org/horde_imap_client 2.29.2 -> satisfiable by pear-pear.horde.org/Horde_Imap_Client[2.29.2].

    - pear-pear.horde.org/Horde_Imap_Client 2.29.2 requires php <6.0.0.0 -> your PHP version (7.0.0-dev) or "config.platform.php" value does not satisfy that requirement.

  Problem 6

    - Installation request for pear-pear.horde.org/horde_listheaders 1.2.2 -> satisfiable by pear-pear.horde.org/Horde_ListHeaders[1.2.2].

    - pear-pear.horde.org/Horde_ListHeaders 1.2.2 requires php <6.0.0.0 -> your PHP version (7.0.0-dev) or "config.platform.php" value does not satisfy that requirement.

  Problem 7

    - Installation request for pear-pear.horde.org/horde_mail 2.6.2 -> satisfiable by pear-pear.horde.org/Horde_Mail[2.6.2].

    - pear-pear.horde.org/Horde_Mail 2.6.2 requires php <6.0.0.0 -> your PHP version (7.0.0-dev) or "config.platform.php" value does not satisfy that requirement.

  Problem 8

    - Installation request for pear-pear.horde.org/horde_mime 2.9.2 -> satisfiable by pear-pear.horde.org/Horde_Mime[2.9.2].

    - pear-pear.horde.org/Horde_Mime 2.9.2 requires php <6.0.0.0 -> your PHP version (7.0.0-dev) or "config.platform.php" value does not satisfy that requirement.

  Problem 9

    - Installation request for pear-pear.horde.org/horde_nls 2.0.5 -> satisfiable by pear-pear.horde.org/Horde_Nls[2.0.5].

    - pear-pear.horde.org/Horde_Nls 2.0.5 requires php <6.0.0.0 -> your PHP version (7.0.0-dev) or "config.platform.php" value does not satisfy that requirement.

  Problem 10

    - Installation request for pear-pear.horde.org/horde_secret 2.0.4 -> satisfiable by pear-pear.horde.org/Horde_Secret[2.0.4].

    - pear-pear.horde.org/Horde_Secret 2.0.4 requires php <6.0.0.0 -> your PHP version (7.0.0-dev) or "config.platform.php" value does not satisfy that requirement.

  Problem 11

    - Installation request for pear-pear.horde.org/horde_smtp 1.9.1 -> satisfiable by pear-pear.horde.org/Horde_Smtp[1.9.1].

    - pear-pear.horde.org/Horde_Smtp 1.9.1 requires php <6.0.0.0 -> your PHP version (7.0.0-dev) or "config.platform.php" value does not satisfy that requirement.

  Problem 12

    - Installation request for pear-pear.horde.org/horde_socket_client 2.0.0 -> satisfiable by pear-pear.horde.org/Horde_Socket_Client[2.0.0].

    - pear-pear.horde.org/Horde_Socket_Client 2.0.0 requires php <6.0.0.0 -> your PHP version (7.0.0-dev) or "config.platform.php" value does not satisfy that requirement.

  Problem 13

    - Installation request for pear-pear.horde.org/horde_stream 1.6.2 -> satisfiable by pear-pear.horde.org/Horde_Stream[1.6.2].

    - pear-pear.horde.org/Horde_Stream 1.6.2 requires php <6.0.0.0 -> your PHP version (7.0.0-dev) or "config.platform.php" value does not satisfy that requirement.

  Problem 14

    - Installation request for pear-pear.horde.org/horde_stream_filter 2.0.3 -> satisfiable by pear-pear.horde.org/Horde_Stream_Filter[2.0.3].

    - pear-pear.horde.org/Horde_Stream_Filter 2.0.3 requires php <6.0.0.0 -> your PHP version (7.0.0-dev) or "config.platform.php" value does not satisfy that requirement.

  Problem 15

    - Installation request for pear-pear.horde.org/horde_stream_wrapper 2.1.2 -> satisfiable by pear-pear.horde.org/Horde_Stream_Wrapper[2.1.2].

    - pear-pear.horde.org/Horde_Stream_Wrapper 2.1.2 requires php <6.0.0.0 -> your PHP version (7.0.0-dev) or "config.platform.php" value does not satisfy that requirement.

  Problem 16

    - Installation request for pear-pear.horde.org/horde_support 2.1.4 -> satisfiable by pear-pear.horde.org/Horde_Support[2.1.4].

    - pear-pear.horde.org/Horde_Support 2.1.4 requires php <6.0.0.0 -> your PHP version (7.0.0-dev) or "config.platform.php" value does not satisfy that requirement.

  Problem 17

    - Installation request for pear-pear.horde.org/horde_text_filter 2.3.2 -> satisfiable by pear-pear.horde.org/Horde_Text_Filter[2.3.2].

    - pear-pear.horde.org/Horde_Text_Filter 2.3.2 requires php <6.0.0.0 -> your PHP version (7.0.0-dev) or "config.platform.php" value does not satisfy that requirement.

  Problem 18

    - Installation request for pear-pear.horde.org/horde_text_flowed 2.0.2 -> satisfiable by pear-pear.horde.org/Horde_Text_Flowed[2.0.2].

    - pear-pear.horde.org/Horde_Text_Flowed 2.0.2 requires php <6.0.0.0 -> your PHP version (7.0.0-dev) or "config.platform.php" value does not satisfy that requirement.

  Problem 19

    - Installation request for pear-pear.horde.org/horde_translation 2.2.0 -> satisfiable by pear-pear.horde.org/Horde_Translation[2.2.0].

    - pear-pear.horde.org/Horde_Translation 2.2.0 requires php <6.0.0.0 -> your PHP version (7.0.0-dev) or "config.platform.php" value does not satisfy that requirement.

  Problem 20

    - Installation request for pear-pear.horde.org/horde_util 2.5.6 -> satisfiable by pear-pear.horde.org/Horde_Util[2.5.6].

    - pear-pear.horde.org/Horde_Util 2.5.6 requires php <6.0.0.0 -> your PHP version (7.0.0-dev) or "config.platform.php" value does not satisfy that requirement.
```

The only thing I could find in the horde bugtracker is: https://bugs.horde.org/ticket/13988

@DeepDiver1975 @Gomez @irgendwie @Xenopathic any idea?

### PR DESCRIPTION
**Pull request by DeepDiver1975**
fixes #1050

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
3 issues


````
 Problem 1

    - Installation request for pear-pear.horde.org/horde_nls 2.1.0 -> satisfiable by pear-pear.horde.org/Horde_Nls[2.1.0].

    - pear-pear.horde.org/Horde_Nls 2.1.0 requires php <6.0.0.0 -> your PHP version (7.0.2) or value of "config.platform.php" in composer.json does not satisfy that requirement.

  Problem 2

    - Installation request for pear-pear.horde.org/horde_socket_client 2.1.0 -> satisfiable by pear-pear.horde.org/Horde_Socket_Client[2.1.0].

    - pear-pear.horde.org/Horde_Socket_Client 2.1.0 requires php <6.0.0.0 -> your PHP version (7.0.2) or value of "config.platform.php" in composer.json does not satisfy that requirement.

  Problem 3

    - pear-pear.horde.org/Horde_Nls 2.1.0 requires php <6.0.0.0 -> your PHP version (7.0.2) or value of "config.platform.php" in composer.json does not satisfy that requirement.

    - pear-pear.horde.org/Horde_Date 2.2.0 requires pear-pear.horde.org/horde_nls <3.0.0.0 -> satisfiable by pear-pear.horde.org/Horde_Nls[2.1.0].

    - Installation request for pear-pear.horde.org/horde_date 2.2.0 -> satisfiable by pear-pear.horde.org/Horde_Date[2.2.0].

**Comment by DeepDiver1975** [comment]
we are not yet there ...

**Comment by ChristophWurst** [comment]
> we are not yet there ...

:cry:

**Comment by clementhk** [comment]
Can we do this and see what happens?
(if you guys don't like it we could still use it to see how the test goes)

```
diff --git a/Makefile b/Makefile
index 9ac32fd..dc9c6f9 100644
--- a/Makefile
+++ b/Makefile
@@ -20,7 +20,7 @@ composer.phar:
 install-deps: install-composer-deps install-npm-deps install-bower-deps
 
 install-composer-deps: composer.phar
-       php composer.phar install
+       php composer.phar install --ignore-platform-reqs
 
 install-npm-deps:
        npm install --production
```

**Comment by clementhk** [comment]
https://github.com/horde/horde/pull/172
It's merged upstream, maybe we don't need my pr.
We would still need https://github.com/clementhk/mail/commit/781bcf3947d922716cb84f45c4c1d0044a304ba4 though.

**Comment by ChristophWurst** [comment]
fixed in https://github.com/owncloud/mail/pull/1300

**Pull request closed without merging**
