### PR TITLE
Implement search

### PR DESCRIPTION
**Pull request by DeepDiver1975**
@jancborchardt

### CODE REVIEW

**Comment by jancborchardt** [comment]
Nice, great start! Just one issue: No other folder than the inbox of the first account can be opened.

The other folders show »No messages in this folder!« and this error in the log:
```
{"reqId":"g\/pFb4D5TJfYbCPtl6Gf","remoteAddr":"127.0.0.1",
"app":"PHP","message":"Undefined index: text at \/home\/jan\/owncloud\/apps\/mail\/vendor\/pear-pear.horde.org\/Horde_Imap_Client\/Horde\/Imap\/Client\/Search\/Query.php#243",
"level":0,"time":"2015-04-13T22:11:10+00:00","method":"GET",
"url":"\/owncloud\/index.php\/apps\/mail\/accounts\/2\/folders\/SU5CT1g%3D\/messages"}
```

**Comment by jancborchardt** [comment]
Nice!!!

Just one thing left now: If you have multiple accounts, the folder highlight is a bit messed up. Each account always has a folder highlighted as active. So even if you only have the sent folder of account 2 open, the last folder you opened in account 1 will also be highlighted in the sidebar.

**Comment by jancborchardt** [comment]
And second thing: The »load more« button is missing.

**Comment by jancborchardt** [comment]
Another thing: What seems to be searched is the sender and the message body. What is _not_ searched though is the subject and people in cc. Can we add that?

**Comment by jancborchardt** [comment]
When there are no results, we should
* show a message: »No results for **searchterm**«
* add a button »Clear search« below it
* do not show the »Load more« button

**Comment by DeepDiver1975** [comment]
> Another thing: What seems to be searched is the sender and the message body. What is not searched though is the subject and people in cc. Can we add that?

we need to have a closer look - according to the api call message body and all headers are searched.

**Comment by jancborchardt** [comment]
Mmmmmhh now we can search our mails

**Pull request merged**
