### PR TITLE
handle 400 responses returned while creating a new account

### LINKED ISSUE #330: Adding not-autodetected account result in 400
When trying to add an account with advanced configuration the request fails:
naamloos

Tested on PHP 5.4 & 5.3. No errors in the log.

### PR DESCRIPTION
**Pull request by wurstchristoph**
fixes #330

### CODE REVIEW

**Comment by jancborchardt** [comment]
@LEDfan can you review if this fixes #330 for you?

**Comment by jancborchardt** [comment]
Oi @LEDfan, you alive? ;) Would be cool if you can review if it fixes your issue #330 :)

**Comment by LEDfan** [comment]
There is now an error shown, but I still can't add my mail account.

**Comment by wurstchristoph** [comment]
@LEDfan what error is shown?
If you enable debugging mode, there should be logs why the account creation failed. Could you please post them?

**Comment by jancborchardt** [comment]
@LEDfan any updates ^? A detailed log / debugging info would be cool. :)

**Comment by jancborchardt** [comment]
cc @Xenopathic can you test this?

@wurstchristoph we need a rebase here. :)

**Comment by Xenopathic** [comment]
I am unable to trigger this code. Creating a Gmail account succeeds, but I get a 'Error while loading selected account' message shortly afterwards, and every time I load the page. This is accompanied by the 'IMAP error reported by server' exception printed to the logs.

**Comment by wurstchristoph** [comment]
@jancborchardt rebased ;-)

**Comment by jancborchardt** [comment]
Aaand best rebase this as well again cause of the password encryption. ;)

**Comment by DeepDiver1975** [comment]
:+1:

**Pull request merged**
