### PR TITLE
Move startup logic to App::onStart

### PR DESCRIPTION
**Pull request by ChristophWurst**
This PR moves some code to better fitting places. Moving the start-up logic out of classes it doesn't really fit will make the introduction of the Backbone router easier as we now have all in one place.

I couldn't find any new errors, @Gomez @jancborchardt test this please

### CODE REVIEW

**Comment by ChristophWurst** [comment]
> codacy/pr — Good work! A positive commit.

Wohoo! It's the first time it's not complaining :D

**Comment by jancborchardt** [comment]
No clue about this. ;) Maybe @irgendwie is a better person to ask / test here.

**Comment by ChristophWurst** [comment]
@jancborchardt simply use this branch today and tell me if you face any problems. The intention was to not change any functionality, but move some code around as a preparation for future PRs.

**Comment by jancborchardt** [comment]
Couldn’t find any issues so far, using it normally. :) :+1:

**Comment by ChristophWurst** [comment]
nice, thanks for testing

**Pull request merged**
