### PR TITLE
change to secure connection

### PR DESCRIPTION
**Pull request by enoch85**
cc @ChristophWurst  @Gomez

### CODE REVIEW

**Comment by ChristophWurst** [comment]
maybe we can then remove the ``"secure-http": false`` option too

**Comment by enoch85** [comment]
Done

**Comment by ChristophWurst** [comment]
Thanks @enoch85!

**Comment by ChristophWurst** [comment]
:+1: :rocket:

**Comment by enoch85** [comment]
Was a bit too quick there: https://getcomposer.org/doc/06-config.md#secure-http

Think we need the config option.

**Comment by enoch85** [comment]
No, this need to be reverted. I didn't check before, but it seems like we need to generate a SSL certificate to be able to get files over SSL. I thought it was just a simple change, but no.

**Pull request merged**
