### PR TITLE
highlight only one folder at a time

### LINKED ISSUE #440: Several folders highlighted when clicking through the list fast
When you click on different folders faster than they can load, the sidebar can look like this:
mail-folders
(In this case the »Sent« folder is open since it was clicked last.)

To fix this, we should remove the highlight on any other folder when clicking on a new folder. cc @wurstchristoph @zinks-

### PR DESCRIPTION
**Pull request by wurstchristoph**
```setFolderInactive``` removed as it is not necessary anymore

fixes #440

### CODE REVIEW

**Comment by jancborchardt** [comment]
Will check it out right now! Does this also fix the follow-up issue you mentioned as comment in #440 about the message list loading for every folder you click? Or would that be a separate PR?

**Comment by jancborchardt** [comment]
(Answering myself: No it doesn’t fix that second issue. :) But the highlighting fix works!

@wurstchristoph do you want to fix the other issue in this PR as well? Because it kind of belongs together it seems. Otherwise the UI is more polished than the requests. ;)

**Comment by jancborchardt** [comment]
Oh, it seems that this pull request (in comparison to master) results in sending 3 or 4 emails instead of one. ;)

(You probably will see it in your inbox as I sent you an email just now.)

**Comment by wurstchristoph** [comment]
Are you sure that multiple sent emails are caused by this PR? It doesn't change anything but the UI.

Regarding the second issue: To be honest, I have no idea on how to deal with those concurrent ajax calls, therefore I cannot fix it (for now)... :disappointed:

**Comment by jancborchardt** [comment]
Ok, I’ll have to test it again. Weirdly enough it happened, and didn’t happen when I switched back to master. But maybe it was something else.

**Comment by jancborchardt** [comment]
The multiple mail sending must have been something else. :+1: here. :)

**Pull request merged**
