### PR TITLE
remove contributor agreement

### PR DESCRIPTION
**Pull request by wurstchristoph**
Additionally, I added some parts of the newer CONTRIBUTOR.md file of the core repository

@DeepDiver1975 @jancborchardt @zinks-

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
:+1:

**Comment by zinks-** [comment]
:+1:

**Comment by jancborchardt** [comment]
On a similar note though, it would be cool to add some of you awesome contributors to the [ownCloud github organization](https://github.com/owncloud). Then you can work in branches of this repo directly, merge pull requests when they have two +1s, close issues etc.

@zinks- @wurstchristoph @clementhk @irgendwie & @Henni do you want to get added to the org? For that you need to either sign the contributor agreement for that or state that all your code is MIT licensed. In this case of the Mail app it's mainly a formality, but it's because you will also have access to the core and other repositories. (Of course we only do stuff via pull requests in any case.)

@Xenopathic @Gomez you are already in the org, but need to switch your visibility from Private to Public at https://github.com/orgs/owncloud/people ;)

**Comment by colmoneill** [comment]
Well that certainly sounds nice!! I'd be in, even though my contributions have not been very important yet...

**Comment by aidanamavi** [comment]
@jancborchardt I'd love to be added to the ownCloud GitHub organization. I really appreciate the offer!

I couldn't find the contributor agreement. Could you link me to it?

**Comment by clementhk** [comment]
@jancborchardt how do I do that?

**Comment by wurstchristoph** [comment]
@aidanamavi you can find it here: https://owncloud.org/contribute/agreement/

**Comment by aidanamavi** [comment]
Thanks for the link @wurstchristoph 

I just sent my signed contributor agreement. :)

**Pull request merged**
