### PR TITLE
Stop unread counter from decrementing if star / unstar messages.

### PR DESCRIPTION
**Pull request by irgendwie**
fix for #542.

### CODE REVIEW

**Comment by irgendwie** [comment]
@wurstchristoph @zinks- @jancborchardt review please!

**Comment by jancborchardt** [comment]
lol @ the commit message

**Comment by irgendwie** [comment]
:see_no_evil: changed the commit message @jancborchardt

**Comment by jancborchardt** [comment]
Nice work! :+1: fixes the issue

Please give it another review @DeepDiver1975 @Gomez

**Comment by rullzer** [comment]
:+1: works and the code looks clean!

**Comment by zinks-** [comment]
all errors are gone and the counter behaves as expected ! :+1:

**Comment by jancborchardt** [comment]
@zinks- @rullzer @irgendwie please check https://github.com/owncloud/mail/pull/635 – it refactors the code in a way that this code block will be removed anyway.

**Comment by jancborchardt** [comment]
@irgendwie merging this as it works and was reviewed. :) We will update https://github.com/owncloud/mail/pull/635

**Comment by jancborchardt** [comment]
Merging this as well right now because it was tested by 3. Travis takes too long atm and will delay the release. :(

**Pull request merged**
