### PR TITLE
Prevent merge conflicts of the changelog files

### PR DESCRIPTION
**Pull request by ChristophWurst**
- [x] TODO: exclude from archives

### CODE REVIEW

**Comment by ChristophWurst** [comment]
@Gomez @tahaalibra review please

**Comment by tahaalibra** [comment]
i read about this method on gitlab...looks good, github does not support it, but it works locally, lets merge it and test it out

**Comment by Gomez** [comment]
@tahaalibra Sure, go on and press the button :+1:

**Comment by ChristophWurst** [comment]
it's a great feeling, push the button ;-)

**Comment by ChristophWurst** [comment]
@tahaalibra please delete the branch after merging. thanks.

**Pull request merged**
