### PR TITLE
Unread/read status syncing, message list syncing, and infinite scrolling w/feedback.

### LINKED ISSUE #499: Automatic lazy loading of more messages when scrolled to the end of the list
Currently when you scroll down the message list you need to manually click »Load more …«. Instead, more mails should automatically get loaded shortly before you reach the end of the list.

Similar to pull to refresh / automatically loading newer messages: https://github.com/owncloud/mail/issues/104

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/11391226-automatic-lazy-loading-of-more-messages-when-scrolled-to-the-end-of-the-list?utm_campaign=plugin&utm_content=tracker%2F216487&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F216487&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #773: [master] under yet unknown conditions the check-messages-button disappears

### PR DESCRIPTION
**Pull request by aidanamavi**
Added event handler for message click to toggle the unseen flag.
Added syncing for the message unseen flag to the mail server.
Added unseen status fetcher for the Inbox folder.
Added message list syncing.
Added infinite scrolling message list with feedback.

Fixes #773	Detect flag changes and expunged messages
Fixes #499	Automatic lazy loading of more messages when scrolled to the end of the list
Fixes #104	Pull to refresh & automatic update of messages
Related #633	"Check messages" should sync deleted messages as well.

### CODE REVIEW

**Comment by jancborchardt** [comment]
Awesome! :) Only one thing: Everything in one commit? Sounds like it ideally should be 3 commits to properly separate the features. That way the history is more useful and if there are any issues we can more easily track them down.

cc @ChristophWurst @DeepDiver1975

**Comment by aidanamavi** [comment]
I got carried away, because as I was developing the syncing of the message list I noticed how many other things were interdependent. I know I could have cut the commits up in hind sight, but this was a big learning process for me. I hope the new features will make up for it. :) I'll be sure to be more proactive about smaller commits in the future.

**Comment by jancborchardt** [comment]
@aidanamavi yeah, I guess it’ll not be a problem – @ChristophWurst @DeepDiver1975 @irgendwie what do you say?

Gotta go test this right now. :)

**Comment by jancborchardt** [comment]
@aidanamavi oh and in case you don’t know: Since you are in the ownCloud organization, you do not need to fork the Mail app – you can create a branch directly in this repository. (No pushing to master though, ever. :)

**Comment by jancborchardt** [comment]
Hm – the lazy loading does not seem to work in the individual inboxes. In the unified inbox it loads all messages (or nearly all) very fast. But the message display is very janky – it already happened twice now that I clicked delete on a message, and a split second before (or while I was clicking) suddenly another message was below the mouse cursor and that got deleted instead!

Also, some new errors in the owncloud.log which I haven’t seen on master yet:
```
{"reqId":"zn67QpQLaCGX29roZruw","remoteAddr":"127.0.0.1","app":"core","message":"OC_Image->loadFromBase64, could not load","level":0,"time":"2015-06-29T13:08:37+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/mail\/accounts\/-1\/folders\/YWxsLWluYm94ZXM%3D\/messages?from=0&to=375"}
{"reqId":"HhC\/9DpnH4L56Qn7luWp","remoteAddr":"127.0.0.1","app":"no app in context","message":"Message moved to trash: 9378 from mailbox INBOX","level":1,"time":"2015-06-29T13:08:39+00:00","method":"DELETE","url":"\/owncloud\/index.php\/apps\/mail\/accounts\/-1\/folders\/YWxsLWluYm94ZXM%3D\/messages\/WzE3LDkzNzhd"}
{"reqId":"9jByAppD8jjwuq4EzZI4","remoteAddr":"127.0.0.1","app":"mail","message":"loading messages 0 to 375 of folder <>","level":0,"time":"2015-06-29T13:08:43+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/mail\/accounts\/-1\/folders\/YWxsLWluYm94ZXM%3D\/messages?from=0&to=375"}
{"reqId":"9jByAppD8jjwuq4EzZI4","remoteAddr":"127.0.0.1","app":"PHP","message":"imagecreatefromstring(): Empty string or invalid image at \/home\/jan\/owncloud\/lib\/private\/image.php#622","level":0,"time":"2015-06-29T13:08:49+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/mail\/accounts\/-1\/folders\/YWxsLWluYm94ZXM%3D\/messages?from=0&to=375"}
{"reqId":"9jByAppD8jjwuq4EzZI4","remoteAddr":"127.0.0.1","app":"core","message":"OC_Image->loadFromBase64, could not load","level":0,"time":"2015-06-29T13:08:49+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/mail\/accounts\/-1\/folders\/YWxsLWluYm94ZXM%3D\/messages?from=0&to=375"}
{"reqId":"9jByAppD8jjwuq4EzZI4","remoteAddr":"127.0.0.1","app":"PHP","message":"imagecreatefromstring(): Empty string or invalid image at \/home\/jan\/owncloud\/lib\/private\/image.php#622","level":0,"time":"2015-06-29T13:08:49+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/mail\/accounts\/-1\/folders\/YWxsLWluYm94ZXM%3D\/messages?from=0&to=375"}
{"reqId":"9jByAppD8jjwuq4EzZI4","remoteAddr":"127.0.0.1","app":"core","message":"OC_Image->loadFromBase64, could not load","level":0,"time":"2015-06-29T13:08:49+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/mail\/accounts\/-1\/folders\/YWxsLWluYm94ZXM%3D\/messages?from=0&to=375"}
{"reqId":"1f75wmof3BJfauOQ+7+l","remoteAddr":"127.0.0.1","app":"mail","message":"loading messages 0 to 374 of folder <>","level":0,"time":"2015-06-29T13:08:53+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/mail\/accounts\/-1\/folders\/YWxsLWluYm94ZXM%3D\/messages?from=0&to=374"}
```

**Comment by aidanamavi** [comment]
@jancborchardt Ah, that's right. I'll do that, because in cases especially like this, it would make sense for someone to jump in and debug with me.

Lazy loading works for other folder, but it just occurred to me that I wrote the code to disable lazy loading once the current folder no longer has any older messages to load, which means lazy loading is disabled app-wide from that point on. Easy fix. In the mean time, fresh the page to test in different folders.

I'll have to test further to find that janky bug. I have yet to experience it. Further info would be helpful.

I looked through my ownCloud.log and have none of those messages except the one about mail loading messages. I didn't code that in, so I presume that was already there and meant for debugging.

**Comment by aidanamavi** [comment]
@jancborchardt I think I know what movement you mean when referring to janky. When the additional messages are loading, an element at the end of the message list displays a loading-icon, or error message when appropriate. As it is removed when messages are done loading or errors are resolved, the message list moves upward a little bit.

If we remove that, there is no feedback, but the additional messages load without interrupting the scroll placement. We can add feedback with OC.notifications, but that isn't as intuitive; and when there is an error, the multiple calls end up spamming and then breaking the OC.notifications. Reducing call times isn't an option, because then there is no infinite scroll - it's scroll down, wait several seconds impatiently, repeat XX times to reach message XX. As you mentioned the loading takes just a moment, and I didn't expect anyone/you to have such quick trigger fingers. :) What are your thoughts?

**Comment by jancborchardt** [comment]
>  an element at the end of the message list displays a loading-icon, or error message when appropriate

You could just always display an item with the same height there. Just that it has no content when there is no loading-icon or message there. That would probably get rid of the jankiness.

**Comment by aidanamavi** [comment]
@jancborchardt Good idea. I'll give it a go tomorrow, and see if that does the trick.

**Comment by aidanamavi** [comment]
Made all the updates on #834 @jancborchardt

**Pull request closed without merging**
