### PR TITLE
Fixed message deletion bug, and message loading.

### LINKED ISSUE #730: On deletion, switch to newer mail instead of older
Currently when you delete an email, the next one automatically getting opened is the next older one. Usually email apps do it the other way around: Opening the next newer one.

We should switch that around hence. :) (That also makes it simpler to follow conversations for now while will don't have threading #21 - simply start at the oldest one and delete to get to the next one.)
Of course when you delete the first message in the current folder there should be a special case where the second message (the older one) is opened instead.

### PR DESCRIPTION
**Pull request by aidanamavi**
Fixed delete function.
Fixed message loading function.
Modified delete function to load a newer message upon deletion, otherwise load an older message upon deletion.

Resolves issues #730 and #753

### CODE REVIEW

**Comment by jancborchardt** [comment]
Nice, works great and fixes both issues! :+1: another review please @colmoneill @irgendwie @wurstchristoph

**Comment by wurstchristoph** [comment]
Nice :+1:

**Comment by jancborchardt** [comment]
Awesome @aidanamavi! Good to have you on board as JS wiz. :)

**Comment by aidanamavi** [comment]
Thanks @jancborchardt! I'm happy I can contribute in some way :)

**Pull request merged**
