### PR TITLE
don't ignore context parameter

### PR DESCRIPTION
**Pull request by ChristophWurst**

### CODE REVIEW

**Comment by Gomez** [comment]
Does this fix this errors:
```
"app":"no app in context"
```

**Comment by ChristophWurst** [comment]
> Does this fix this errors:
> 
> "app":"no app in context"

Could you please post the complete log entry where this happened?

**Comment by Gomez** [comment]
Hmm, can reproduce anymore. I am not sure what this does, as it is only a logger var, its is safe to merge?

**Comment by Gomez** [comment]
rebase needed.

**Comment by DeepDiver1975** [comment]
rebased

**Comment by ChristophWurst** [comment]
@Gomez @DeepDiver1975 can we merge this?

**Comment by Gomez** [comment]
Cant really decide. But looks like it cant break anything important.

**Comment by itheiss** [comment]
LGTM :+1: 

At least didn't break anything for me ...

**Pull request merged**
