### PR TITLE
Fix message deletion by 'del' hotkey while adding a new mail account.

### LINKED ISSUE #912: Message deletion triggered while adding account
If you use the delete key while adding a second account, the currently opened message is being deleted. This is pretty critical because you may delete newly arrived mails while setting up this app without noticing anything!

@DeepDiver1975 @jancborchardt 0.2 or 0.3?

### PR DESCRIPTION
**Pull request by irgendwie**
Fixes #912

It's done by checking if the message list is visible or not. Good idea? Bad idea? Review pls! @ChristophWurst

### CODE REVIEW

**Comment by jancborchardt** [comment]
@irgendwie u coming to ze ownCloud conf now? We’re sitting at the Mail app hacking table and miss you. ;)

**Comment by irgendwie** [comment]
@jancborchardt :yum: sry, can't! still I try to fix some bugs while you guys are partying hard :smiley:

**Comment by Gomez** [comment]
We restructure the js files. Best if you can create a new one pr, rebase would be difficult. 

Thanks!

**Comment by irgendwie** [comment]
@Gomez rebased.
@ChristophWurst review and merge pls :smile:

**Comment by ChristophWurst** [comment]
:+1:

**Pull request merged**
