### PR TITLE
use LoadingView instead of manually adding/removing classes

### LINKED ISSUE #1025: Use loading views instead of manually adding classes with jQuery
Currently loading spinners are shown by adding css classes to elements using jQuery. In certain situations this can lead to classes not being removed or added.

To solve that problem cleanly, I'd suggest we add 'loading views' which are shown until the 'real' view has finished loading.

An example would be loading accounts (left sidebar): Simply create a new view/template with only one element (div) that has the loading spinner class and add it to the DOM. Once the real view/data has been loaded, replace that loading view.

### PR DESCRIPTION
**Pull request by ChristophWurst**
Now there's also a single spinner when loading a folder for the first time instead of two.

fixes #1025 

TODO:
 - [x] use LoadingView as a replacement for the NavigationView loading spinner
 - [ ] fix broken SettingsView (core's slide js magic does not work if the html of the settings menu is not present at page load)
 - [ ] add missing LoadingView before accounts have been loaded (https://github.com/owncloud/mail/pull/1399#issuecomment-204666363)

@jancborchardt @Gomez @tahaalibra could you try this branch and tell me if there's anything I forgot? I'm not 100% sure if the changes cover all possible transitions between the UI's states.

---
This change is [Reviewable](https://reviewable.io/reviews/owncloud/mail/1399)

### CODE REVIEW

**Comment by jancborchardt** [comment]
Nice! Except one thing: Between the left navigation loading and the main content having loaded, there is only a spinner starting at a certain point. And if it loads from cache, seemingly not at all.

**Comment by ChristophWurst** [comment]
@jancborchardt could you take a quick screenshot/video? I'm not sure if I understand which spinner you're referring to

**Comment by jancborchardt** [comment]
There is no center area spinner while the left navigation is loading (in this case not fully yet) or already loaded:
capture du 2016-04-02 09-28-48

**Comment by jancborchardt** [comment]
Shortly after this screenshot, the account list on the left is fully populated, and then all emails incl the current one appear. (From cache I assume)

**Comment by ChristophWurst** [comment]
Thanks, I'll try to fix that too

**Comment by Gomez** [comment]
Looks good. Lets clean it up and merge. After merging i do a 0.4.2.
@ChristophWurst Would you separate the commits?

**Pull request closed without merging**
