### PR TITLE
Set type of user inputs to text instead of email - fixes #520

### LINKED ISSUE #520: Inputs for IMAP/SMTP user shouldn't necessarily be an email address
The input fields for the IMAP and SMTP users are set to type="email". But it should also be possible to set the username to a simple string instead of an email address. Therefore the type should be replaced by "text".
( similar to #517 )

### PR DESCRIPTION
**Pull request by Henni**
fixes #520

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
Looks good - thx

**Comment by jancborchardt** [comment]
@Henni even better: Set it to `number`. :)

**Comment by jancborchardt** [comment]
Ah nevermind – I misread the title and thought this was https://github.com/owncloud/mail/pull/518 :D

**Comment by jancborchardt** [comment]
:+1:

**Pull request merged**
