### PR TITLE
remove 'Check messages' button and add scroll-to-refresh and shortcut

### PR DESCRIPTION
**Pull request by ChristophWurst**
TODO:
- [x] loading animation should be fixed (also shown when list is scrolled down)
- [x] weird bug causes a pagination request when scrolling down

### CODE REVIEW

**Comment by ChristophWurst** [comment]
bildschirmfoto von 2016-07-28 15-40-46
@skjnldsv could you help with the CSS please? The spinner is not 100% centered, I guess we need some flexbox magic for the message-list and message content, so we can position that spinner absolute. Do you have an idea how to do that? :-)

**Comment by ChristophWurst** [comment]
:+1: for jan's part

**Comment by jancborchardt** [comment]
:+1: for the whole thing :) very nice and finally that button is gone!

**Comment by jancborchardt** [comment]
@skjnldsv if you want to play around with some flexbox stuff, feel free. :)

**Comment by jancborchardt** [comment]
And cc @BernhardPosselt @cosenal on this. ;) For the Mail app we’ll try to get pull/scroll to refresh right. Maybe if we succeed this is interesting for the News app too. And we have the `r` shortcut for refreshing as well.

**Pull request merged**
