### PR TITLE
properties added + code formatted

### PR DESCRIPTION
**Pull request by wurstchristoph**
As mail.js is mostly spaghetti code, I started refactoring a little bit and added js object properties where they make sense (Mail.State, Mail.UI).

Additionally, I changed all ``function (..`` occurrences to ``function(..``.

@aidanamavi @colmoneill  @DeepDiver1975 @irgendwie @jancborchardt please review ;-)

### CODE REVIEW

**Comment by jancborchardt** [comment]
> As mail.js is mostly spaghetti code

I can hear @DeepDiver1975 getting angry somewhere. ;D But he knows its true and he welcomes improvement. :)

**Comment by aidanamavi** [comment]
I like what you've done @wurstchristoph!

Lets move this code to the top of that variables list to keep the var list in alphabetical order. 
```
var accounts = null;
```
And lets get these code check issues fixed.

**Comment by wurstchristoph** [comment]
@aidanamavi @jancborchardt I resolved all CI errors, please review again :)

**Comment by aidanamavi** [comment]
Why did you decide to style this function/object differently than the precursors State, Cache, Search, Background, etc?
https://github.com/owncloud/mail/pull/761/files#diff-e2c9975f9881d06a58edf438a8960426R420

Also alphabetize the immediate following variable on line 421.

**Comment by wurstchristoph** [comment]
@aidanamavi mail.js components are declared using object literals. Unfortunately, you cannot add _private_ members to object literals, they are always visible from the outside. By using a function, you can declare variables that are only accessible from inside this function which means proper data hiding.

There are some examples [here](http://www.htmlgoodies.com/beyond/javascript/class-member-encapsulation-in-javascript-data-hiding.html) and [here](https://stackoverflow.com/questions/1396294/how-to-add-private-variable-to-this-javascript-object-literal-snippet). Furthermore I have already used this style for background fetching of messages (``Mail.Background.messageFetcher``)

**Comment by aidanamavi** [comment]
@wurstchristoph Ah, I didn't know literals didn't store private members. Good to know!

Any idea what the codacy issues are? Otherwise, everything looks good to me.

**Comment by wurstchristoph** [comment]
@aidanamavi I think we can ignore those codacy issues, there's nothing related to this PR (only PHP and CSS issues)
Thanks for reviewing :)

**Comment by DeepDiver1975** [comment]
@wurstchristoph please rebase - THX

**Comment by wurstchristoph** [comment]
@DeepDiver1975 done

**Comment by aidanamavi** [comment]
:+1: Can anyone else give a quick review, so we can get this merged?

**Comment by DeepDiver1975** [comment]
:+1:

**Pull request merged**
