### PR TITLE
Block images

### LINKED ISSUE #424: Don't load external images
### Steps to reproduce
1. Go to mail app
2. Load any mail with linked external images

### Expected behaviour
The external images should not show up immediately, only after an additional request to do so (similar to Thunderbird's default behavior).

### Actual behaviour
External images are immediately loaded (proxied somehow via owncloud, but still).
This might be considered a security concern (as Junk mail senders get notified if their mail is read...).

### Server configuration
mostly not relevant
Mail app version: 0.1.3 (not sure if this is still the current one... according to master in github.com/owncloud/mail, it seems to be. it's not the current master version though but from some time ago).

### Client configuration
not relevant

### Logs
not relevant

### PR DESCRIPTION
**Pull request by jakobsack**
Fixes #424

### CODE REVIEW

**Comment by irgendwie** [comment]
Nice work! :+1: LGTM

**Comment by ChristophWurst** [comment]
Awesome!! :+1:

**Comment by Gomez** [comment]
:+1: 
Nice work! 
@jancborchardt Maybe some design ideas? The blue is to blue?

**Comment by jancborchardt** [comment]
@jakobsack I mentioned using a transparent PNG, can you please fix that?

**Pull request merged**
