### PR TITLE
fix email length in the database

### PR DESCRIPTION
**Pull request by tahaalibra**
change email length from 64 to 255 in the database
@ChristophWurst @Gomez

### CODE REVIEW

**Comment by ChristophWurst** [comment]
@tahaalibra please set the labels appropriately when submitting pull requests, thanks :)

**Comment by ChristophWurst** [comment]
please add a changelog entry for this fix

**Comment by ChristophWurst** [comment]
@viki53 you [volunteered for testing](https://github.com/owncloud/mail/pull/1433#issuecomment-218120690), can you test with innodb please?

**Comment by ChristophWurst** [comment]
needs rebase

**Comment by tahaalibra** [comment]
@ChristophWurst done!!

**Comment by ChristophWurst** [comment]
:+1: thanks

**Comment by viki53** [comment]
@ChristophWurst Sure! Which branch/commit should I clone to test?

**Comment by ChristophWurst** [comment]
this one ;-)

**Comment by viki53** [comment]
I just installed the app.

DB upgrade went fine but then I got an error when I accessed the Web interface.

Now that I fixed that by upgrading other apps (which made OwnCloud deactivate all the apps), I can't enable the Mail app because it "makes the server unstable" apparently…

**Comment by ChristophWurst** [comment]
> makes the server unstable

could be a duplicate https://github.com/owncloud/mail/issues/1522.
Could you provide the info asked by the issue_template so we can try to reproduce and fix that bug?

**Comment by viki53** [comment]
I posted [a comment](https://github.com/owncloud/mail/issues/1522#issuecomment-224852157) on the #1522 issue with all the details I can get

**Comment by viki53** [comment]
All good! :+1: 

Upgrade worked fine, app seems to work as expected (at least for the retrieving mails part).

Thanks!

**Comment by ChristophWurst** [comment]
@viki53 the version in the store is signed and you should get the next updated when it's available. I don't think you need to replace it now. It should be fine :-)

**Pull request merged**
