### PR TITLE
Fix: New issue New mails sent from unified inbox #921

### LINKED ISSUE #921: New mails sent from unified inbox seem to be always sent from first account
Even though you choose another one from the switcher. :\ That’s quite an annoying bug which you only find out when you look into your sent folder, or notice it in the reply.

### PR DESCRIPTION
**Pull request by itheiss**
@jancborchardt  Please test and review and let me know what you think. :-)

Fix #921

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
@ChristophWurst

**Comment by jancborchardt** [comment]
Nice! :+1: works very well

**Comment by jancborchardt** [comment]
@itheiss you are very welcome in our IRC channel #owncloud-mail (on freenode network) :)

**Comment by jancborchardt** [comment]
@itheiss and if you want to help more with the 0.2 release, fixing issues and reviewing pull requests of others – please do! : )

**Comment by itheiss** [comment]
@jancborchardt  Thanks. I will help where I can. But spare time is very very limited :-(

**Comment by jancborchardt** [comment]
Ohh … this seems to have broken replying (from the unified inbox) with this error:
```
{"reqId":"+Me9TVTkwkkkL2mZ4KSR","remoteAddr":"127.0.0.1","app":"index","message":"Exception: {\"Exception\":\"OCP\\\\AppFramework\\\\Db\\\\DoesNotExistException\",\"Message\":\"No matching entry found\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/jan\\\/owncloud\\\/lib\\\/public\\\/appframework\\\/db\\\/mapper.php(346): OCP\\\\AppFramework\\\\Db\\\\Mapper->findOneQuery('SELECT * FROM `...', Array, NULL, NULL)\\n#1 \\\/home\\\/jan\\\/owncloud\\\/apps\\\/mail\\\/lib\\\/db\\\/mailaccountmapper.php(47): OCP\\\\AppFramework\\\\Db\\\\Mapper->findEntity('SELECT * FROM `...', Array)\\n#2 \\\/home\\\/jan\\\/owncloud\\\/apps\\\/mail\\\/lib\\\/service\\\/accountservice.php(51): OCA\\\\Mail\\\\Db\\\\MailAccountMapper->find('jan', 0)\\n#3 \\\/home\\\/jan\\\/owncloud\\\/apps\\\/mail\\\/lib\\\/controller\\\/accountscontroller.php(261): OCA\\\\Mail\\\\Service\\\\AccountService->find('jan', 0)\\n#4 [internal function]: OCA\\\\Mail\\\\Controller\\\\AccountsController->send(0, 'YWxsLWluYm94ZXM...', NULL, 'Yeah, Carlos al...', '\\\"Debars…\\\" ...', '\\\"Andreas...', '', 1528, 'WzE2LDExNTg4XQ=...', NULL)\\n#5 \\\/home\\\/jan\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(159): call_user_func_array(Array, Array)\\n#6 \\\/home\\\/jan\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Mail\\\\Controller\\\\AccountsController), 'send')\\n#7 \\\/home\\\/jan\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/app.php(108): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Mail\\\\Controller\\\\AccountsController), 'send')\\n#8 \\\/home\\\/jan\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/routing\\\/routeactionhandler.php(45): OC\\\\AppFramework\\\\App::main('AccountsControl...', 'send', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#9 [internal function]: OC\\\\AppFramework\\\\routing\\\\RouteActionHandler->__invoke(Array)\\n#10 \\\/home\\\/jan\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(274): call_user_func(Object(OC\\\\AppFramework\\\\routing\\\\RouteActionHandler), Array)\\n#11 \\\/home\\\/jan\\\/owncloud\\\/lib\\\/base.php(879): OC\\\\Route\\\\Router->match('\\\/apps\\\/mail\\\/acco...')\\n#12 \\\/home\\\/jan\\\/owncloud\\\/index.php(40): OC::handleRequest()\\n#13 {main}\",\"File\":\"\\\/home\\\/jan\\\/owncloud\\\/lib\\\/public\\\/appframework\\\/db\\\/mapper.php\",\"Line\":284}","level":4,"time":"2015-08-08T08:08:23+00:00","method":"POST","url":"\/owncloud\/index.php\/apps\/mail\/accounts\/%7BaccountId%7D\/send"}
```

I’ll have to revert it to make master work again. :\ @itheiss would be cool if you can find the issue and do a new pull request. :)

**Comment by jancborchardt** [comment]
(Reverted via https://github.com/owncloud/mail/pull/927)

**Comment by itheiss** [comment]
Damn! I will habe a look at this. Did not notice this in my tests.

**Comment by jancborchardt** [comment]
@itheiss no worries – we all missed it. :) I look forward to your fix, cause the original issue is really important.

**Pull request merged**
