### PR TITLE
update php libs, fix Makefile target 'update-composer'

### PR DESCRIPTION
**Pull request by ChristophWurst**
TODO:
- [x] test the app with updated libraries

---
This change is [Reviewable](https://reviewable.io/reviews/owncloud/mail/1369)

### CODE REVIEW

**Comment by enoch85** [comment]
Will this fix #1375?

**Comment by ChristophWurst** [comment]
> Will this fix #1375?

No ;-)

**Comment by ChristophWurst** [comment]
no (new) errors found -> @owncloud/mail review please

**Comment by Gomez** [comment]
Lets do a 0.4.1 and i will test this after the release? @ChristophWurst What u think?

**Comment by Gomez** [comment]
No error found so far...

**Pull request merged**
