### PR TITLE
update index.php - dual scrollbar

### PR DESCRIPTION
**Pull request by mitpro**
Dual scrollbar-problem (Issue #848)

### CODE REVIEW

**Comment by jancborchardt** [comment]
@mitpro thanks! One problem with this is that in case the HTML mail is wider than the viewport (like some newsletters or notifications) the content is cut off and it’s not possible to scroll horizontally.

cc also @ChristophWurst @irgendwie @clementhk @zinks- for testing.

**Comment by jancborchardt** [comment]
Moving to 0.3 as it’s not critical. @mitpro can you address my comment? :)

**Comment by ChristophWurst** [comment]
closing this because of no activity

**Comment by mitpro** [comment]
was searching for a solution that only the horitol scrollbar would be shown - but not realy relevant

**Pull request closed without merging**
