### PR TITLE
fix whitespace between cc list and closing parenthesis

### PR DESCRIPTION
**Pull request by jancborchardt**
Before 
capture du 2015-05-06 10 53 36
After
capture du 2015-05-06 10 53 58

Please review @Gomez @irgendwie @wurstchristoph

### CODE REVIEW

**Comment by Xenopathic** [comment]
Much good. Such easy. Very nicer. :+1:

**Comment by jakobsack** [comment]
looks fine :+1:

**Comment by jancborchardt** [comment]
doge

**Comment by jancborchardt** [comment]
OOOH LOOK @JAKOBSACK RETURNED! :) Lord and savior of the Mail app?

**Comment by jancborchardt** [comment]
cc @DeepDiver1975 ^

**Pull request merged**
