### PR TITLE
Go for php7

### PR DESCRIPTION
**Pull request by clementhk**

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
thx - let's see :wink:

**Comment by clementhk** [comment]
Passed: https://travis-ci.org/clementhk/mail/jobs/106975213

(it's fast)

**Comment by ChristophWurst** [comment]
I did some quick tests and everything seemed to work, nice!
However, I'd say we should wait until all horde libs officially support php7

**Comment by ChristophWurst** [comment]
fixed in https://github.com/owncloud/mail/pull/1300

**Pull request closed without merging**
