### PR TITLE
fill imap, smtp user and password inputs automatically

### LINKED ISSUE #1311: Enhance auto/manual account setup UX
- When toggling manual setup, email address and password for imap and smtp should be pre-filled
- When autoconfig fails with "Autoconfig failed, try manual mode", manual mode should be toggled automatically

cc @jancborchardt @colmoneill

### PR DESCRIPTION
**Pull request by ChristophWurst**
partially fixes #1311

@jancborchardt @ErikPel @Tagada85 easy to review

### CODE REVIEW

**Comment by ErikPel** [comment]
Mail app stops working for me completely with this branch
I either get
`M…e.E…r.M…e.e…d.c…l.constructor {name: "Error", message: "An "el" #setup must exist in DOM"}message: "An "el" #setup must exist in DOM"name: "Error"stack: (...)get stack: get stack()set stack: set stack()__proto__: SurrogateModule.check @ require.js?v=0ec3ec046fa8b285811da09cf4a9de5d:900(anonymous function) @ require.js?v=0ec3ec046fa8b285811da09cf4a9de5d:1140(anonymous function) @ require.js?v=0ec3ec046fa8b285811da09cf4a9de5d:131(anonymous function) @ require.js?v=0ec3ec046fa8b285811da09cf4a9de5d:1190each @ require.js?v=0ec3ec046fa8b285811da09cf4a9de5d:56Module.emit @ require.js?v=0ec3ec046fa8b285811da09cf4a9de5d:1189Module.check @ require.js?v=0ec3ec046fa8b285811da09cf4a9de5d:940(anonymous function) @ require.js?v=0ec3ec046fa8b285811da09cf4a9de5d:1140(anonymous function) @ require.js?v=0ec3ec046fa8b285811da09cf4a9de5d:131(anonymous function) @ require.js?v=0ec3ec046fa8b285811da09cf4a9de5d:1190each @ require.js?v=0ec3ec046fa8b285811da09cf4a9de5d:56Module.emit @ require.js?v=0ec3ec046fa8b285811da09cf4a9de5d:1189Module.check @ require.js?v=0ec3ec046fa8b285811da09cf4a9de5d:940(anonymous function) @ require.js?v=0ec3ec046fa8b285811da09cf4a9de5d:625each @ require.js?v=0ec3ec046fa8b285811da09cf4a9de5d:56breakCycle @ require.js?v=0ec3ec046fa8b285811da09cf4a9de5d:614(anonymous function) @ require.js?v=0ec3ec046fa8b285811da09cf4a9de5d:627each @ require.js?v=0ec3ec046fa8b285811da09cf4a9de5d:56breakCycle @ require.js?v=0ec3ec046fa8b285811da09cf4a9de5d:614(anonymous function) @ require.js?v=0ec3ec046fa8b285811da09cf4a9de5d:627each @ require.js?v=0ec3ec046fa8b285811da09cf4a9de5d:56breakCycle @ require.js?v=0ec3ec046fa8b285811da09cf4a9de5d:614(anonymous function) @ require.js?v=0ec3ec046fa8b285811da09cf4a9de5d:701each @ require.js?v=0ec3ec046fa8b285811da09cf4a9de5d:56checkLoaded @ require.js?v=0ec3ec046fa8b285811da09cf4a9de5d:700context.completeLoad @ require.js?v=0ec3ec046fa8b285811da09cf4a9de5d:1608context.onScriptLoad @ require.js?v=0ec3ec046fa8b285811da09cf4a9de5d:1711`
error or 
```
Refused to execute script from 'http://erikpellikka.com/owncloud/apps/mail/js/vendor/backbone.radio/build/backbone.radio.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
require.js?v=0ec3ec046fa8b285811da09cf4a9de5d:165 Uncaught Error: Script error for "backbone.radio"
http://requirejs.org/docs/errors.html#scripterror

```

After I switch to master branch the app works fine

**Comment by ChristophWurst** [comment]
@ErikPel this looks weird. Please try to delete and re-install your js dependencies. This PR doesn't change how the view is rendered into the dom. Hence, if the ``#setup`` can't be found the error should also occur on master.

> Refused to execute script from 'http://erikpellikka.com/owncloud/apps/mail/js/vendor/backbone.radio/build/backbone.radio.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.

Please have a look at that file. Are your js dependencies corrupt?

**Comment by ErikPel** [comment]
@ChristophWurst 
Yeah it's good possibility there might be something wrong with my setup.
I'll investigate more tomorrow.
Weird that every time I went
`git checkout master`
everything worked fine again.

But then when I installed the mail app again my whole owncloud stopped working so there might be something very wrong with my setup

**Comment by ChristophWurst** [comment]
@ErikPel could you fix your setup? Did you test this branch?

**Comment by Gomez** [comment]
```
TypeError: this.ui is undefined
.toggleManualMode/<()
 setup.js:97
x.speed/r.complete()
 jquery.min.js:6
x.Callbacks/c()
 jquery.min.js:4
x.Callbacks/p.fireWith()
 jquery.min.js:4
er/l()
 jquery.min.js:6
x.fx.tick()
```

**Comment by ErikPel** [comment]
Yeah sorry. Had some issues with my server and I'm on vacation now. I'll
try and take a look as soon as I can

**Comment by Gomez** [comment]
I checked it. Works! @ErikPel Report if you find something.

**Pull request merged**
