### PR TITLE
add tests for accountsservice

### PR DESCRIPTION
**Pull request by ChristophWurst**
Another class that didn't have any tests (https://scrutinizer-ci.com/g/owncloud/mail/code-structure/master?elementType=class&orderField=test_coverage&order=asc&changesExpanded=0)

### CODE REVIEW

**Comment by clementhk** [comment]
Are you going to finish your TODO before merging?

**Comment by ChristophWurst** [comment]
> Are you going to finish your TODO before merging?

Nope, that's just a note that this class needs more tests ;-)

**Comment by ChristophWurst** [comment]
Scrutinizer is super reliable. You write tests for a class that didn't have any tests before and get this:  Test Coverage 44%▼ -1%

**Comment by Gomez** [comment]
:+1:

**Pull request merged**
