### PR TITLE
[WIP] Some bugfixes for the unread mail counter

### PR DESCRIPTION
**Pull request by irgendwie**

### CODE REVIEW

**Comment by jancborchardt** [comment]
@irgendwie is this ready for review yet or still work in progress? :)

**Comment by irgendwie** [comment]
Still work in progress @jancborchardt - it doesn't work completely and there are still some other bugs with the counter.

**Comment by irgendwie** [comment]
Needs  #122... to don't get hacky

**Comment by jancborchardt** [comment]
@irgendwie #122 aliases seem to be entirely unrelated – sure you linked the right issue? ;)

**Comment by irgendwie** [comment]
@jancborchardt For mails sent to an alias, I would need a hack to determine which account the mail belongs to (in the unified mailbox), because the message itself doesn't contain that information for mails with a different address than specified within the settings of the mail account.
If alias support is implemented, this issue would be fixed and I could just take the information, instead of writing a "dirty" workaround.

I think we have more than enough hacks in the mail app already.

**Comment by ChristophWurst** [comment]
> I think we have more than enough hacks in the mail app already.

Yes, indeed :)

**Comment by jancborchardt** [comment]
Any updates here @irgendwie? Would be awesome to get this fixed :)

**Comment by irgendwie** [comment]
@jancborchardt Sorry, currently working on my bachelor thesis and therefore no time for owncloud :smile:

**Comment by jancborchardt** [comment]
Ah, damn! :D Good luck then!

**Comment by Gomez** [comment]
@irgendwie Can you finish?

**Comment by irgendwie** [comment]
@Gomez Will take a look tomorrow!

**Comment by jancborchardt** [comment]
@irgendwie tomorrow was yesterday. ;)

**Comment by irgendwie** [comment]
@jancborchardt I know, did look into it -> stuff is handled differently now and the function isn't even called anymore. Need some time to get into the new code.
Maybe we should close this PR and create a new one.

**Comment by ChristophWurst** [comment]
@irgendwie can the branch be deleted?

**Comment by irgendwie** [comment]
Yes it can - the code isn't usable anymore.

**Pull request closed without merging**
