### PR TITLE
change icons to black to fit ownCloud 8.2 style

### PR DESCRIPTION
**Pull request by jancborchardt**
Simply changed from 50% transparency to fully black so it’s in line with the Files app.

Please review @owncloud/designers

### CODE REVIEW

**Comment by raghunayyar** [comment]
:+1:

**Comment by raghunayyar** [comment]
@jancborchardt why is the opacity tweaked in the svg? Ideally, it should be set by CSS. Am I missing something?

**Comment by jancborchardt** [comment]
It was tweaked in the SVG before. That’s why I’m fixing it.

**Comment by enoch85** [comment]
@jancborchardt Does this close https://github.com/owncloud/mail/issues/1073 ?

**Comment by jancborchardt** [comment]
No, this is about the icons of the special folders in the navigation sidebar on the left.

**Pull request merged**
