### PR TITLE
update developer setup info

### PR DESCRIPTION
**Pull request by ChristophWurst**
This change is [Reviewable](https://reviewable.io/reviews/owncloud/mail/1391)

### CODE REVIEW

**Comment by enoch85** [comment]
:+1:

**Comment by ChristophWurst** [comment]
@enoch85 that was fast :-D

**Comment by enoch85** [comment]
Was sitting with it. :)

**Comment by jancborchardt** [comment]
Nice, thanks!

**Comment by jancborchardt** [comment]
Actually – do these commands have to be run always on pulls? Can we combine them into one command? Or just list them in there with `&&`.

**Comment by ChristophWurst** [comment]
We should find a uniform way if installing dependencies. I think contacts and news are now also using the Makefile to install their dependencies

**Comment by enoch85** [comment]
Just for the record, maybe not related to this merge, but I get his in the nightly script:

**Comment by ChristophWurst** [comment]
@enoch85 could you check if that was maybe a temporary error? e.g. faulty network could cause such errors.

Everything works for me (deleted the vendor folder and ran composer install):
```
php composer.phar install
You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
  - Installing ezyang/htmlpurifier (v4.7.0)
    Downloading: 100%         

  - Installing kwi/urllinker (dev-default b5e097f)
    Cloning b5e097f03963454b4e8f32581265c8e57c3409e6
    Failed to download kwi/urllinker from source: Failed to execute hg clone 'https://bitbucket.org/kwi/urllinker' '/home/christoph/workspace/owncloud/apps/mail/vendor/kwi/urllinker'

sh: hg: command not found

    Now trying to download from dist
  - Installing kwi/urllinker (dev-default b5e097f)
    Downloading: 100%         

  - Installing pear-pear.horde.org/horde_translation (2.2.1)
    Loading from cache
  - Installing pear-pear.horde.org/horde_util (2.5.7)
    Loading from cache
  - Installing pear-pear.horde.org/horde_nls (2.1.1)
    Downloading: 100%         
  - Installing pear-pear.horde.org/horde_exception (2.0.8)
    Loading from cache
  - Installing pear-pear.horde.org/horde_date (2.3.0)
    Downloading: 100%         
  - Installing pear-pear.horde.org/horde_stream_filter (2.0.4)
    Loading from cache
  - Installing pear-pear.horde.org/horde_stream (1.6.3)
    Loading from cache
  - Installing pear-pear.horde.org/horde_socket_client (2.1.1)
    Downloading: 100%         
  - Installing pear-pear.horde.org/horde_stream_wrapper (2.1.3)
    Loading from cache
  - Installing pear-pear.horde.org/horde_support (2.1.5)
    Loading from cache
  - Installing pear-pear.horde.org/horde_crypt_blowfish (1.1.1)
    Downloading: 100%         
  - Installing pear-pear.horde.org/horde_secret (2.0.6)
    Downloading: 100%         
  - Installing pear-pear.horde.org/horde_text_flowed (2.0.3)
    Loading from cache
  - Installing pear-pear.horde.org/horde_mime (2.9.4)
    Loading from cache
  - Installing pear-pear.horde.org/horde_idna (1.0.4)
    Loading from cache
  - Installing pear-pear.horde.org/horde_mail (2.6.3)
    Loading from cache
  - Installing pear-pear.horde.org/horde_listheaders (1.2.3)
    Loading from cache
  - Installing pear-pear.horde.org/horde_imap_client (2.29.6)
    Downloading: 100%         
  - Installing pear-pear.horde.org/horde_smtp (1.9.3)
    Downloading: 100%         
  - Installing pear-pear.horde.org/horde_text_filter (2.3.4)
    Downloading: 100%         
Generating autoload files
```

**Comment by enoch85** [comment]
@ChristophWurst Sorry for the noise, it works!

**Comment by jancborchardt** [comment]
@ChristophWurst yeah, can the makefile default command just be making everything?

**Comment by ChristophWurst** [comment]
@jancborchardt does *everything* also include packaging?

**Comment by jancborchardt** [comment]
Probably not. Just everything that a dev needs to make a git clone running locally.

**Pull request merged**
