### PR TITLE
add installation section to readme

### PR DESCRIPTION
**Pull request by jancborchardt**
Please check if this is understandable @enoch85 @Gomez @clementhk thanks! :)

### CODE REVIEW

**Comment by enoch85** [comment]
:+1:

**Comment by jancborchardt** [comment]
Maybe rather »app menu«?

**Comment by enoch85** [comment]
@jancborchardt Perfect.

**Comment by clementhk** [comment]
LGTM. Though I don't know how many people would come on github to look for installation, as github is more likely for devs.

**Pull request merged**
