### PR TITLE
Create sent folder automatically if it does not exist

### PR DESCRIPTION
**Pull request by wurstchristoph**
``getSentFolder`` changed so it creates the 'sent' folder if it does not exist.

``getSpecialFolder`` had to be changed a little bit because it was not clear whether the function returned a ``Mailbox`` or an array. I'm not totally happy with this solution as the functions name would suggest it returns only a single folder.

### CODE REVIEW

**Comment by jancborchardt** [comment]
@zinks- @wurstchristoph any update on this by the way? :)

**Comment by wurstchristoph** [comment]
I removed the name matching code as suggested by @zinks

The code was tested using oc8 stable. If I send a mail the sent folder is created as intended.

**Comment by jancborchardt** [comment]
@DeepDiver1975 @zinks- @PoPoutdoor can you review the code? Thanks! :)

**Comment by jancborchardt** [comment]
Ooooohyeah! This fixes https://github.com/owncloud/mail/issues/449 for me :)

@DeepDiver1975 @Gomez @zinks- can you cross-test it?

Also @seal20 does this fix https://github.com/owncloud/mail/issues/412 for you?

**Comment by DeepDiver1975** [comment]
general comment: I really appreciate to have a clean commit history - please squash the commits - thx

**Comment by jancborchardt** [comment]
Merging this for now. :) In the future a cleaner commit history would be cool, but this fixes a crucial bug.

**Pull request merged**
