### PR TITLE
Js cleanup

### PR DESCRIPTION
**Pull request by ChristophWurst**
This is the result of 10 hour pair-programming with @Radlr. We tried to kill ``ui.js``. Unfortunately, moving some of the methods will need bigger changes in the app. We should consider something like a content-view to show either messages or the setup view. Currently a lot of that code – especially showing message bodies and composers – is handled by ``ui.js``.

Backbone radio was added for enhanced event and request/response handling. As a side effect, this will also help debugging js-errors as all events are logged to the console:

bildschirmfoto von 2016-02-06 20-57-20

Note that this is only shown in debug mode as it uses ``console.log``.

This is part of #944

@Gomez @DeepDiver1975 @ErikPel @owncloud/mail please have a look. It should be possible to review commit by commit. Thanks! :-)

### CODE REVIEW

**Comment by Gomez** [comment]
Cool, already read through some of the code, but needs more time :)

**Comment by ChristophWurst** [comment]
> Cool, already read through some of the code, but needs more time :)

There's a lot that changed. Take your time ;-)

**Comment by Gomez** [comment]
I have two accounts, access the inbox of the first is not a problem. But the second throw this error:
```
15:11:11.545 TypeError: model is undefined
._onModelEvent() backbone.js:1148
triggerEvents() backbone.js:369
triggerApi() backbone.js:357
eventsApi() backbone.js:155
Events.trigger() backbone.js:346
._transformEvent() message.js:30
triggerEvents() backbone.js:370
triggerApi() backbone.js:356
eventsApi() backbone.js:155
Events.trigger() backbone.js:346
.set() backbone.js:526
.flagMessage() message.js:46
.setMessageFlag() messages.js:71
triggerEvents() backbone.js:371
triggerApi() backbone.js:356
eventsApi() backbone.js:155
Events.trigger() backbone.js:346
loadMessage/loadMessageSuccess() ui.js:404
loadMessage/<.onSuccess() ui.js:483
fetchMessage() communication.js:77
loadMessage() ui.js:471
<anonymous> ui.js:30
triggerEvents() backbone.js:372
triggerApi() backbone.js:356
eventsApi() backbone.js:155
Events.trigger() backbone.js:346
.openMessage() message.js:77
x.event.dispatch() jquery.min.js:5
x.event.add/v.handle() jquery.min.js:5
1 backbone.js:1148:13
```

**Comment by ChristophWurst** [comment]
> I have two accounts, access the inbox of the first is not a problem. But the second throw this error:

I can't reproduce this. Did you run ``bower install`` to install/update dependencies?

Please clear you browser log, refresh the page and try to reproduce the bug. The browser log should help to identify the bug (see screenshot above)

**Comment by ChristophWurst** [comment]
Found it. I happens when a message is being flagged as seen. However, I can also reproduce that on master, hence I can assume it was not introduced by any commit of this PR.

**Comment by ChristophWurst** [comment]
@Gomez rebased. If there's anything unclear about the changes we made please let me know.

**Comment by Gomez** [comment]
Correct, i get error on master too. Cant do a full review but i learn a lot about backbone.radio. Looks good.
Just a jshint error to fix.

**Comment by ChristophWurst** [comment]
> Just a jshint error to fix.

Done.

**Comment by ChristophWurst** [comment]
> Cant do a full review but i learn a lot about backbone.radio. Looks good.

@Gomez @owncloud/mail So what are we gonna do with this? :-) Another review? Merge?

**Comment by Gomez** [comment]
We merge and i catch up with the changes as we go.

**Pull request merged**
