### PR TITLE
CSS Coding Style #817

### PR DESCRIPTION
**Pull request by Tagada85**
Few changes from _ to -

### CODE REVIEW

**Comment by ChristophWurst** [comment]
@Tagada85 thanks for cleaning this up. Did you check for possible duplicate ids? I remember some places we had stuff like ``mail_messages`` and ``mail-messages``, but for different elements.

@owncloud/mail @jancborchardt have a look please

**Comment by Tagada85** [comment]
I remember seeing mail-message and mail_message so I didn't touch it. I don't think I saw any mail-messages. But I'll take an other look.

**Comment by ChristophWurst** [comment]
> I remember seeing mail-message and mail_message so I didn't touch it.

``mail-message`` was the one I had in mind. Good that you didn't touch it ;-)

**Comment by ChristophWurst** [comment]
@Tagada85 btw. you are welcome to join us in our IRC channel #owncloud-mail if you need any help ;-)

**Comment by Tagada85** [comment]
@ChristophWurst Thank you very much !! :)

**Comment by ChristophWurst** [comment]
:+1: seems to not break anything

**Pull request merged**
