### PR TITLE
split client code into AMD modules and load them with requirejs

### PR DESCRIPTION
**Pull request by ChristophWurst**
replacement for #917

@Gomez @irgendwie @DeepDiver1975 @jancborchardt please test if this breaks anything :see_no_evil: 

__'34 changed files with 3,095 additions and 2,637 deletions'__… Only small steps from now on @jancborchardt, right? :)

### CODE REVIEW

**Comment by Gomez** [comment]
If you delete a Mail Account & add a new Account: 

ReferenceError: Mail is not defined

**Comment by irgendwie** [comment]
I just see the three spinner and get the following output in the 'owncloud.log':

>{"reqId":"c+zcGxY0SxcFxeyvGLbR","remoteAddr":"127.0.0.1","app":"mail","message":"Could not find resource file \"\/oc\/apps\/mail\/js\/node_modules\/requirejs\/require.js\"","level":3,"time":"2015-08-29T15:57:56+00:00","method":"GET","url":"\/oc\/index.php\/apps\/mail\/"}

**Comment by ChristophWurst** [comment]
> I just see the three spinner and get the following output in the 'owncloud.log':
> 
>     {"reqId":"c+zcGxY0SxcFxeyvGLbR","remoteAddr":"127.0.0.1","app":"mail","message":"Could not find resource file \"\/oc\/apps\/mail\/js\/node_modules\/requirejs\/require.js\"","level":3,"time":"2015-08-29T15:57:56+00:00","method":"GET","url":"\/oc\/index.php\/apps\/mail\/"}

easy to fix:
```BASH
cd js
npm install
```

we'll have to add that to the readme ;-)

**Comment by irgendwie** [comment]
Mmh, is it planned, that we ship it with the app, as I don't have npm installed on my system?

**Comment by Gomez** [comment]
@irgendwie Only needed for development. We will ship it with the production zip.

**Comment by irgendwie** [comment]
Ah, again something learned :+1: thanks @Gomez
LGTM :+1:

**Comment by ChristophWurst** [comment]
:+1:

**Pull request merged**
