### PR TITLE
Such an ugly hack - fixes #611

### LINKED ISSUE #611: Subfolders don't load
Clicking on a subfolder does not show it's content, the spinners stay on screen.

the error occurrs in this code (**folder.js**) :
```js
	updateTitle: function() {

		var activeAccount = Mail.State.currentAccountId;
		var activeFolder = Mail.State.currentFolderId;
		activeAccount = this.collection.get(activeAccount);
		activeFolder = activeAccount.get('folders').get(activeFolder);
		var unread = activeFolder.get('unseen');
```
``TypeError: activeFolder is undefined``

The Json message list is retrieved successfully, though.

### PR DESCRIPTION
**Pull request by DeepDiver1975**
fix #611

@zinks-

### CODE REVIEW

**Comment by jancborchardt** [comment]
Does not work for me. Still 2 spinners.

**Comment by jancborchardt** [comment]
Also cc @irgendwie for testing

**Comment by Xenopathic** [comment]
Does not fix :cry:

**Comment by DeepDiver1975** [comment]
bildschirmvideo von 06 05 2015 12_01_07

**Comment by irgendwie** [comment]
`{"reqId":"01da0decd4b807bcd7c2ec6de8c68934","remoteAddr":"::1","app":"index","message":"Exception: {\"Message\":\"IMAP error reported by server.\",\"Code\":0,\"Trace\":\"#0 \\\/opt\\\/lampp\\\/htdocs\\\/oc\\\/apps\\\/mail\\\/vendor\\\/pear-pear.horde.org\\\/Horde_Imap_Client\\\/Horde\\\/Imap\\\/Client\\\/Socket.php(4208): Horde_Imap_Client_Socket->_getLine(Object(Horde_Imap_Client_Interaction_Pipeline))\\n#1 \\\/opt\\\/lampp\\\/htdocs\\\/oc\\\/apps\\\/mail\\\/vendor\\\/pear-pear.horde.org\\\/Horde_Imap_Client\\\/Horde\\\/Imap\\\/Client\\\/Socket.php(4136): Horde_Imap_Client_Socket->_sendCmdChunk(Object(Horde_Imap_Client_Interaction_Pipeline), Array)\\n#2 \\\/opt\\\/lampp\\\/htdocs\\\/oc\\\/apps\\\/mail\\\/vendor\\\/pear-pear.horde.org\\\/Horde_Imap_Client\\\/Horde\\\/Imap\\\/Client\\\/Socket.php(1656): Horde_Imap_Client_Socket->_sendCmd(Object(Horde_Imap_Client_Interaction_Pipeline))\\n#3 \\\/opt\\\/lampp\\\/htdocs\\\/oc\\\/apps\\\/mail\\\/vendor\\\/pear-pear.horde.org\\\/Horde_Imap_Client\\\/Horde\\\/Imap\\\/Client\\\/Base.php(1724): Horde_Imap_Client_Socket->_status(Array, 63)\\n#4 \\\/opt\\\/lampp\\\/htdocs\\\/oc\\\/apps\\\/mail\\\/lib\\\/account.php(216): Horde_Imap_Client_Base->status(Array)\\n#5 \\\/opt\\\/lampp\\\/htdocs\\\/oc\\\/apps\\\/mail\\\/lib\\\/controller\\\/folderscontroller.php(62): OCA\\\\Mail\\\\Account->getListArray()\\n#6 [internal function]: OCA\\\\Mail\\\\Controller\\\\FoldersController->index()\\n#7 \\\/opt\\\/lampp\\\/htdocs\\\/oc\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(158): call_user_func_array(Array, Array)\\n#8 \\\/opt\\\/lampp\\\/htdocs\\\/oc\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(86): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Mail\\\\Controller\\\\FoldersController), 'index')\\n#9 \\\/opt\\\/lampp\\\/htdocs\\\/oc\\\/lib\\\/private\\\/appframework\\\/app.php(97): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Mail\\\\Controller\\\\FoldersController), 'index')\\n#10 \\\/opt\\\/lampp\\\/htdocs\\\/oc\\\/lib\\\/private\\\/appframework\\\/routing\\\/routeactionhandler.php(44): OC\\\\AppFramework\\\\App::main('FoldersControll...', 'index', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#11 [internal function]: OC\\\\AppFramework\\\\routing\\\\RouteActionHandler->__invoke(Array)\\n#12 \\\/opt\\\/lampp\\\/htdocs\\\/oc\\\/lib\\\/private\\\/route\\\/router.php(250): call_user_func(Object(OC\\\\AppFramework\\\\routing\\\\RouteActionHandler), Array)\\n#13 \\\/opt\\\/lampp\\\/htdocs\\\/oc\\\/lib\\\/base.php(767): OC\\\\Route\\\\Router->match('\\\/apps\\\/mail\\\/acco...')\\n#14 \\\/opt\\\/lampp\\\/htdocs\\\/oc\\\/index.php(36): OC::handleRequest()\\n#15 {main}\",\"File\":\"\\\/opt\\\/lampp\\\/htdocs\\\/oc\\\/apps\\\/mail\\\/vendor\\\/pear-pear.horde.org\\\/Horde_Imap_Client\\\/Horde\\\/Imap\\\/Client\\\/Socket.php\",\"Line\":4496}","level":4,"time":"2015-05-06T10:19:12+00:00","method":"GET","url":"\/oc\/index.php\/apps\/mail\/accounts\/2\/folders"}`

**Comment by DeepDiver1975** [comment]
@irgendwie this looks like an unrelated issue to me - or does this happen only on this branch?

**Comment by irgendwie** [comment]
Didn't think of it :see_no_evil:
Fails also for master, so unrelated to this issue, sry!

**Comment by DeepDiver1975** [comment]
> Fails also for master, so unrelated to this issue, sry!

no worries

**Comment by DeepDiver1975** [comment]
@jancborchardt @Xenopathic please retest

**Comment by jancborchardt** [comment]
@DeepDiver1975 still does not work for me, 2 spinners. No error in owncloud.log or JS console. Can you test with your owncloud.com account or another non-gmail one too?

**Comment by irgendwie** [comment]
(Now related to the issue :grin:) Doesn't work for me either, with the same behavior as for @jancborchardt

**Comment by DeepDiver1975** [comment]
okay - I get the two spinners for subfolders with 0 unread messages ...

**Comment by DeepDiver1975** [comment]
@jancborchardt @irgendwie @Xenopathic

**Comment by Xenopathic** [comment]
`TypeError: activeFolder is undefined`

**Comment by DeepDiver1975** [comment]
@Xenopathic do you have a line number as well? THX

**Comment by Xenopathic** [comment]
@DeepDiver1975 Yes, line 116...

**Comment by DeepDiver1975** [comment]
What is the folder/mailbox name?

**Comment by Xenopathic** [comment]
At the time it was Education/University

**Comment by zinks-** [comment]
Works for me on one account, but in another account I can't load the folder if it has a "/" in the name.
Some mail servers use "/" hierarchy separator.

**Comment by DeepDiver1975** [comment]
this hack relies on / being the delimiter of mailbox names - well ... a hack is a hack

**Comment by Xenopathic** [comment]
@DeepDiver1975 AH sorry, I see what you mean now - the folder name was actually Education.University, so I guess my server was using dots as the separator (which explains why it broke for me)

**Comment by zinks-** [comment]
@Xenopathic can you test this : https://github.com/owncloud/mail/pull/638
It uses the delimite the server says it uses

**Comment by Gomez** [comment]
https://github.com/owncloud/mail/pull/638 & this PR does not work for me. But we found out that my mail account is in some kind special. I will investigate further and hope we get it done right in 0.2

**Comment by jancborchardt** [comment]
@wurstchristoph you said on IRC that subfolders work again with this PR now? Can you confirm here?

Also @zinks- @Gomez @irgendwie can you double-check?

**Comment by irgendwie** [comment]
Subfolders work for me :+1:, still SubSubfolders don't :-1:

**SubFolder:**
SubFolder.SubSubFolder

**Chromium:**
`Uncaught TypeError: Cannot read property 'set' of undefined
Mail.UI.setFolderActive @ mail.js?v=c385df8d5d048611bfed23f46dcae666:678
Mail.UI.loadMessages @ mail.js?v=c385df8d5d048611bfed23f46dcae666:372
views.Folder.Backbone.Marionette.ItemView.extend.loadMessages @ folder.js?v=c385df8d5d048611bfed23f46dcae666:28
x.event.dispatch @ jquery.min.js?v=c385df8d5d048611bfed23f46dcae666:5
v.handle @ jquery.min.js?v=c385df8d5d048611bfed23f46dcae666:5`

**Comment by DeepDiver1975** [comment]
@irgendwie how are your folders named? What's the delimiter? THX

**Comment by irgendwie** [comment]
**Delimiter** seems to be a dot ('.').

**Structure of the Mailbox:** (Folders are also called that way.)
INBOX
-- SubFolder
---- SubSubFolder
(SubFolder is in Inbox, SubSubFolder is in SubFolder)

**Comment by DeepDiver1975** [comment]
> Subfolders work for me :+1:, still SubSubfolders don't :-1:

Ah - I see - there is another level of mailboxes - I'd like to postpone this for 0.2 - otherwise this is getting too messy

**Comment by irgendwie** [comment]
Ok, alright - then it's working as expected :+1:

**Comment by DeepDiver1975** [comment]
> Ah - I see - there is another level of mailboxes - I'd like to postpone this for 0.2 - otherwise this is getting too messy

regs https://github.com/owncloud/mail/issues/618

**Comment by wurstchristoph** [comment]
> @wurstchristoph you said on IRC that subfolders work again with this PR now? Can you confirm here?

I can confirm that the first level of subfolders works for me (that's what I tested yesterday). Subsubfolders do not work, tested with a folder structure of
- INBOX
- ...
- testsub
  - testsub1
    - testsub2

While testsub1 loads messages as expected, testsub2 doesn't. I get
```
TypeError: Mail.State.folderView.getFolderById(...) is undefined
    Mail.State.folderView.getFolderById(accountId, folderId)
```
in FF console.

**Comment by jancborchardt** [comment]
@DeepDiver1975 @wurstchristoph @irgendwie ok, so we merge this here for 0.1? And 2nd-level-subfolders we postpone to 0.2?

**Comment by DeepDiver1975** [comment]
Let's merge this.

**Comment by jancborchardt** [comment]
@DeepDiver1975 can you open a new issue for 0.2 about the sub-subfolders?

**Comment by DeepDiver1975** [comment]
#613 from my pov

**Comment by jancborchardt** [comment]
@DeepDiver1975 that’s an unrelated issue?

**Comment by jancborchardt** [comment]
I guess you meant https://github.com/owncloud/mail/issues/618

**Pull request merged**
