### PR TITLE
Revert "change to secure connection"

### PR DESCRIPTION
**Pull request by enoch85**
Reverts owncloud/mail#1526

Merged to quick before testing properly.

### CODE REVIEW

**Comment by ChristophWurst** [comment]
Why do you want to revert it? [It worked](https://travis-ci.org/owncloud/mail/builds/137032195)?!

**Comment by enoch85** [comment]
Did you test it?

**Comment by ChristophWurst** [comment]
Yes, works as expected. I think we used http for pear in the past as they didn't serve their packages via https.

**Comment by ChristophWurst** [comment]
Also CI would catch those errors as it downloads the packages too

**Comment by enoch85** [comment]
Sorry, my misstake. It was a temporary error on my side. Everything is ok! :)

**Pull request closed without merging**
