### PR TITLE
Fewer global selectors

### PR DESCRIPTION
**Pull request by ChristophWurst**
This moves global selectors into the app-view, because it feels less hacky to me then. I also added some TODOs, where a bigger refactoring is needed.

Some day I would like to fully get rid of hacky files like init.js and ui.js. We should try to encapsulate all view code into view classes instead of global event handlers that nobody really remembers what they are doing :smile: 

@owncloud/mail have a look please. The easiest is to review each of the commits since I tried to do it step-by-step.

### CODE REVIEW

**Comment by ChristophWurst** [comment]
Failing tests are not related, this PR doesn't touch any PHP. See #1186

**Comment by PoPoutdoor** [comment]
Seems I point to the wrong code, should be
https://github.com/owncloud/mail/blob/master/js/ui.js#L291

Other than this, :+1:

**Comment by jancborchardt** [comment]
@Gomez @irgendwie @phsc @aspdye can we have another review? :)

**Comment by Gomez** [comment]
:+1: Just a log (debug) that should be removed.

**Comment by ChristophWurst** [comment]
Thanks for reviewing!

**Pull request merged**
