### PR TITLE
Revert "getStatus()->utf8/utf7imap does not always return with INBOX pre...

### LINKED ISSUE #626: Having a subfolder in Inbox leads to "Error while loading the selected account."
pic

**What doesn't work:** Having subfolders in Inbox
**What works:** Having subfolders everywhere else instead of Inbox
**Mail-Provider:** Strato.de
**Owncloud-Log:** `{"reqId":"0d8796a92c585d32c9551fa8da2ec226","remoteAddr":"::1","app":"index","message":"Exception: {\"Message\":\"IMAP error reported by server.\",\"Code\":0,\"Trace\":\"#0 \\\/opt\\\/lampp\\\/htdocs\\\/oc\\\/apps\\\/mail\\\/vendor\\\/pear-pear.horde.org\\\/Horde_Imap_Client\\\/Horde\\\/Imap\\\/Client\\\/Socket.php(4208): Horde_Imap_Client_Socket->_getLine(Object(Horde_Imap_Client_Interaction_Pipeline))\\n#1 \\\/opt\\\/lampp\\\/htdocs\\\/oc\\\/apps\\\/mail\\\/vendor\\\/pear-pear.horde.org\\\/Horde_Imap_Client\\\/Horde\\\/Imap\\\/Client\\\/Socket.php(4136): Horde_Imap_Client_Socket->_sendCmdChunk(Object(Horde_Imap_Client_Interaction_Pipeline), Array)\\n#2 \\\/opt\\\/lampp\\\/htdocs\\\/oc\\\/apps\\\/mail\\\/vendor\\\/pear-pear.horde.org\\\/Horde_Imap_Client\\\/Horde\\\/Imap\\\/Client\\\/Socket.php(1656): Horde_Imap_Client_Socket->_sendCmd(Object(Horde_Imap_Client_Interaction_Pipeline))\\n#3 \\\/opt\\\/lampp\\\/htdocs\\\/oc\\\/apps\\\/mail\\\/vendor\\\/pear-pear.horde.org\\\/Horde_Imap_Client\\\/Horde\\\/Imap\\\/Client\\\/Base.php(1724): Horde_Imap_Client_Socket->_status(Array, 63)\\n#4 \\\/opt\\\/lampp\\\/htdocs\\\/oc\\\/apps\\\/mail\\\/lib\\\/account.php(216): Horde_Imap_Client_Base->status(Array)\\n#5 \\\/opt\\\/lampp\\\/htdocs\\\/oc\\\/apps\\\/mail\\\/lib\\\/controller\\\/folderscontroller.php(62): OCA\\\\Mail\\\\Account->getListArray()\\n#6 [internal function]: OCA\\\\Mail\\\\Controller\\\\FoldersController->index()\\n#7 \\\/opt\\\/lampp\\\/htdocs\\\/oc\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(158): call_user_func_array(Array, Array)\\n#8 \\\/opt\\\/lampp\\\/htdocs\\\/oc\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(86): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Mail\\\\Controller\\\\FoldersController), 'index')\\n#9 \\\/opt\\\/lampp\\\/htdocs\\\/oc\\\/lib\\\/private\\\/appframework\\\/app.php(97): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Mail\\\\Controller\\\\FoldersController), 'index')\\n#10 \\\/opt\\\/lampp\\\/htdocs\\\/oc\\\/lib\\\/private\\\/appframework\\\/routing\\\/routeactionhandler.php(44): OC\\\\AppFramework\\\\App::main('FoldersControll...', 'index', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#11 [internal function]: OC\\\\AppFramework\\\\routing\\\\RouteActionHandler->__invoke(Array)\\n#12 \\\/opt\\\/lampp\\\/htdocs\\\/oc\\\/lib\\\/private\\\/route\\\/router.php(250): call_user_func(Object(OC\\\\AppFramework\\\\routing\\\\RouteActionHandler), Array)\\n#13 \\\/opt\\\/lampp\\\/htdocs\\\/oc\\\/lib\\\/base.php(767): OC\\\\Route\\\\Router->match('\\\/apps\\\/mail\\\/acco...')\\n#14 \\\/opt\\\/lampp\\\/htdocs\\\/oc\\\/index.php(36): OC::handleRequest()\\n#15 {main}\",\"File\":\"\\\/opt\\\/lampp\\\/htdocs\\\/oc\\\/apps\\\/mail\\\/vendor\\\/pear-pear.horde.org\\\/Horde_Imap_Client\\\/Horde\\\/Imap\\\/Client\\\/Socket.php\",\"Line\":4496}","level":4,"time":"2015-05-06T11:09:19+00:00","method":"GET","url":"\/oc\/index.php\/apps\/mail\/accounts\/2\/folders"}`

### PR DESCRIPTION
**Pull request by Xenopathic**
...fix, let's clean it up for good"

This reverts commit ba2ef7c050213672d0eec502bbab0800af115f11.

Fixes #626, #617 

Confirmed working by me, @sndrsk and @clementhk 

@clementhk You introduced this change in the first place a few days ago, what was the original intent?

### CODE REVIEW

**Comment by irgendwie** [comment]
Can also confirm, that it fixes my problem #626 :+1:

**Comment by jancborchardt** [comment]
@sndrsk can you review this pull request specifically again and confirm it fixes the problem?

**Comment by clementhk** [comment]
Reviewed-by: me

I'll reply in details once I get on my laptop.

**Comment by sndrsk** [comment]
@jancborchardt I will be able to review this pull request but not until later in the evening when I am home from the day job.

**Comment by jancborchardt** [comment]
Merging because we basically have 3 reviews already. :)

**Comment by clementhk** [comment]
Alright, @Xenopathic @DeepDiver1975 here is the reason for that change.
For those IMAP servers that enforce to have `INBOX` as folder prefix, when we create a folder called `test`, what it will actually create is `INBOX.test`, but when we are creating we do not put that prefix in the folder's name, but after we have created it with horde, and when we get folder's both utf7imap and utf8, it will return a name without a prefix, as `test`, but when we list all folders or contract a new mailbox object, then it will return as `INBOX.test`, this behavior makes the folder's name inconsistent, so when doing tests, we don't know when a folder has a prefix or not.
To these IMAP servers that enforce `INBOX` as prefix, they assume we are working on `INBOX.test` when we ask for `test`. Therefore the change made sense, at least to those servers, and it made folder's name consistent that we can test and compare and work on.

*But* apparently this does not work on all servers, too bad. Therefore the solution for us is to work on horde upstream, to return folder as `INBOX.test` when we create a folder called `test`.

**Comment by Xenopathic** [comment]
Note that the folder prefix can be configured (at least with Dovecot), so we cannot rely on it being INBOX.

**Pull request merged**
