### PR TITLE
Dont show empty notifications

### PR DESCRIPTION
**Pull request by DeepDiver1975**
@jancborchardt @Xenopathic

### CODE REVIEW

**Comment by jancborchardt** [comment]
How can we best test this case? As in, how to fire notifications from the JS console?

**Comment by DeepDiver1975** [comment]
> As in, how to fire notifications from the JS console?

hmmmm - let me see ... I need to restructure the code for this ....

**Comment by DeepDiver1975** [comment]
```js
Mail.BackGround.showMailNotification({messages: []}, 'a@b.c')
undefined
Mail.BackGround.showMailNotification({messages: [{}]}, 'a@b.c')
undefined
Mail.BackGround.showMailNotification({messages: [{}, {}]}, 'a@b.c')
undefined

**Comment by DeepDiver1975** [comment]
@jancborchardt ^^^

**Comment by Xenopathic** [comment]
Well, it seemed to work (I didn't get a notification when I did before), however I still see the favicon change to the 'new messages' icon and the title bar change, so I don't think the root cause has been fixed. It seems the background update triggers on emails that were read in this session, not just unread emails.

**Comment by DeepDiver1975** [comment]
> however I still see the favicon change to the 'new messages' icon and the title bar change,

I should handle this case as well - true - thanks for the hint

**Comment by DeepDiver1975** [comment]
> It seems the background update triggers on emails that were read in this session, not just unread emails.

this is an isolated issue to discuss/think/analyse

**Comment by Xenopathic** [comment]
The thing is, we can either stop the *display* of the problem, but still have the underlying problem (this works until we extend the background checking logic, then we need the display hiding stuff there too), or we target the root cause and make the checker smarter.

**Comment by DeepDiver1975** [comment]
sure ... nothing more to add

**Comment by jancborchardt** [comment]
So you will update this pull request @DeepDiver1975 or is this something for the future?

**Comment by jancborchardt** [comment]
Also getting this when running the commands above:
```
Mail.BackGround.showMailNotification({messages: []}, 'a@b.c');
mail.js?v=248cd893e410dac47688d136b7985123:55 Uncaught TypeError: Cannot read property 'length' of undefinedMail.BackGround.showMailNotification @ mail.js?v=248cd893e410dac47688d136b7985123:55(anonymous function) @ VM3990:2InjectedScript._evaluateOn @ VM3950:883InjectedScript._evaluateAndWrap @ VM3950:816InjectedScript.evaluate @ VM3950:682
Mail.BackGround.showMailNotification({messages: [{}]}, 'a@b.c')
mail.js?v=248cd893e410dac47688d136b7985123:55 Uncaught TypeError: Cannot read property 'length' of undefinedMail.BackGround.showMailNotification @ mail.js?v=248cd893e410dac47688d136b7985123:55(anonymous function) @ VM3992:2InjectedScript._evaluateOn @ VM3950:883InjectedScript._evaluateAndWrap @ VM3950:816InjectedScript.evaluate @ VM3950:682
Mail.BackGround.showMailNotification({messages: [{}, {}]}, 'a@b.c')
mail.js?v=248cd893e410dac47688d136b7985123:55 Uncaught TypeError: Cannot read property 'length' of undefinedMail.BackGround.showMailNotification @ mail.js?v=248cd893e410dac47688d136b7985123:55(anonymous function) @ VM4004:2InjectedScript._evaluateOn @ VM3950:883InjectedScript._evaluateAndWrap @ VM3950:816InjectedScript.evaluate @ VM3950:682
```

**Comment by jancborchardt** [comment]
:+1:

**Pull request merged**
