### PR TITLE
Unified Inbox

### PR DESCRIPTION
**Pull request by DeepDiver1975**
Issues left:

* [x] It’s not possible to delete or star mails – neither in the unified inbox nor in the individual ones (only starring is possible in the individual ones)
* [ ] We need to not show the color of the account when there is only one. Simply do not set the background-color of `.mail-account-color`
* [x] And: When writing a new message, the first entry in the dropdown is `from <>` – I suppose that is because we think the unified inbox is an account.
* [x] sending mails does not work anymore: `Call to undefined method: OCA\\ … getOutboundPassword at account.php line 244`
* [ ] On new mails, the list is not automatically refreshed
* [x] The first message opened / highlighted in the unified inbox is the latest of the first account, not the latest overall.
* [ ] When clicking »load more« the list jump-scrolls to the top as soon as more emails are loaded.
* [x] In the unified inbox, only emails from the first inbox are loaded. When clicking another mail, it shows `Error loading message. No matching entry found`

### CODE REVIEW

**Comment by jancborchardt** [comment]
Nice! One bug at the moment: The first message opened / highlighted in the unified inbox is the latest of the first account, not the latest overall.

**Comment by DeepDiver1975** [comment]
> Nice! One bug at the moment: The first message opened / highlighted in the unified inbox is the latest of the first account, not the latest overall.

I cannot reproduce this with a clean local storage - please retry after cleaning the local storage in the browser - TH

**Comment by jancborchardt** [comment]
@DeepDiver1975 when clicking »load more« the list jump-scrolls to the top as soon as more emails are loaded.

**Comment by jancborchardt** [comment]
@DeepDiver1975 (Travis errors fixed btw)

**Comment by jancborchardt** [comment]
@DeepDiver1975 added some issues/TODO to the original post.

**Comment by DeepDiver1975** [comment]
@jancborchardt please retest - 2 issues are solved from my pov - for the first todo I need #763 - the 3rd issue might be related to #773

**Comment by jancborchardt** [comment]
@DeepDiver1975 you need to rebase :)

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 you need to rebase :)

done

**Comment by jancborchardt** [comment]
We need some more testing of this @wurstchristoph @Gomez @LukasReschke @irgendwie please :)

**Comment by irgendwie** [comment]
Looks good so far, but two issues

- The unified mailbox shows no name, but "[object Object]".
- HTML mails seem to be loaded (inline reply is filled) but not shown.

@DeepDiver1975 Have fun! :-)

**Comment by Gomez** [comment]
Unified
Randomly choosing colour happened bad for me....

**Comment by LukasReschke** [comment]
> Randomly choosing colour happened bad for me....

@jancborchardt Color blindness?

**Comment by DeepDiver1975** [comment]
> The unified mailbox shows no name, but "[object Object]".

@irgendwie can I have a screenshot please? THX

**Comment by irgendwie** [comment]
bugs

**Comment by irgendwie** [comment]
:+1: HTML mails are now loading.

**Comment by jancborchardt** [comment]
Another one: We need to not show the color of the account when there is only one. Simply do not set the background-color of `.mail-account-color`

**Comment by jancborchardt** [comment]
And: When writing a new message, the first entry in the dropdown is `from <>` – I suppose that is because we think the unified inbox is an account.

**Comment by jancborchardt** [comment]
:+1: – everything else we can do in follow-up PRs. We need to merge this before it gets too big.

A second review please @wurstchristoph @aidanamavi @colmoneill @irgendwie @zinks-! :)

**Comment by wurstchristoph** [comment]
> We need to merge this before it gets too big.

16 changed files with 612 additions and 74 deletions. :-)

**Comment by jancborchardt** [comment]
@wurstchristoph is that a +1? :D

**Comment by wurstchristoph** [comment]
It's a +0.9 because there's one little issue: The 'Check messages' button disappears once refreshing the message list has finished.
Other than that :+1: Looks very good! :)

**Comment by jancborchardt** [comment]
Yeah, same here. ;) @DeepDiver1975 care to fix that last thing? ;)

**Comment by jancborchardt** [comment]
@DeepDiver1975 rebase, and can you fix the »Check messages« button disappearing as @wurstchristoph mentioned? :)

**Comment by jancborchardt** [comment]
MERGED! :D Great work

Opened https://github.com/owncloud/mail/issues/803 for the remaining issues.

**Pull request merged**
