### PR TITLE
Adjust version to 0.3.0

### PR DESCRIPTION
**Pull request by itheiss**
I assume this also has to be 0.3.0 ...

### CODE REVIEW

**Comment by ChristophWurst** [comment]
Yes, thank you :+1:

**Comment by jancborchardt** [comment]
It’s not 0.3.0 yet though? cc @DeepDiver1975?

**Comment by ChristophWurst** [comment]
@jancborchardt we can't set it to ``0.3-alpha`` because some tools expect numeric versions numbers

**Comment by jancborchardt** [comment]
Hm, ok. Then we probably should use something like 0.2.9 so we can use 0.3.0 when we actually release 0.3.0?

**Pull request merged**
