### PR TITLE
update grunt

### PR DESCRIPTION
**Pull request by ChristophWurst**
replaces #1528 

Note that I had to update my local npm with ``npm install -g npm`` to get rid of an dependency error related to the package ``fsevents``.

cc @enoch85

### CODE REVIEW

**Comment by enoch85** [comment]
@ChristophWurst Some new issues: 

```
root@en0ch:/var/scripts# bash mail_nightly.sh 
Cloning into 'mail'...
remote: Counting objects: 28145, done.
remote: Compressing objects: 100% (78/78), done.
remote: Total 28145 (delta 11), reused 1 (delta 1), pack-reused 28066
Receiving objects: 100% (28145/28145), 10.68 MiB | 2.88 MiB/s, done.
Resolving deltas: 100% (16478/16478), done.
Checking connectivity... done.
--2016-06-22 18:00:25--  https://patch-diff.githubusercontent.com/raw/owncloud/mail/pull/1540.patch
Resolving patch-diff.githubusercontent.com (patch-diff.githubusercontent.com)... 192.30.252.130
Connecting to patch-diff.githubusercontent.com (patch-diff.githubusercontent.com)|192.30.252.130|:443... connected.
HTTP request sent, awaiting response... 200 OK
Cookie coming from patch-diff.githubusercontent.com attempted to set domain to github.com
Length: unspecified [text/plain]
Saving to: ‘1540.patch’

1540.patch                              [ <=>                                                                ]     528  --.-KB/s    in 0.003s  

2016-06-22 18:00:25 (161 KB/s) - ‘1540.patch’ saved [528]

npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated react-tools@0.13.3: react-tools is deprecated. For more information, visit https://fb.me/react-tools-deprecated
npm WARN deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN prefer global coffee-script@1.10.0 should be installed with -g
npm WARN prefer global react-tools@0.13.3 should be installed with -g

> phantomjs@1.9.20 install /var/scripts/mail/node_modules/phantomjs
> node install.js
```

**Comment by ChristophWurst** [comment]
unrelated, I can fix that in another PR

**Comment by enoch85** [comment]
:+1: then

**Comment by enoch85** [comment]
but `├── UNMET PEER DEPENDENCY grunt@1.0.1 invalid`

**Comment by ChristophWurst** [comment]
> but ├── UNMET PEER DEPENDENCY grunt@1.0.1 invalid

when did you get that?

**Comment by enoch85** [comment]
Check at the bottom of my output post.

**Comment by ChristophWurst** [comment]
Hm, I don't see that message in there

**Comment by enoch85** [comment]
To avoid this `Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them.` I run `npm update` in the script. But when I removed it everything worked fine except that.

This is OK to merge.

**Comment by ChristophWurst** [comment]
> To avoid this Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them. I run npm update in the script. But when I removed it everything worked fine except that.

Please elaborate on which step throws which errors when you build the packages. There are three dependency managers we use: composer, npm and bower.

**Comment by enoch85** [comment]
diff http://pastebin.com/2JuQ4GaV | http://pastebin.com/QZU7vwjU

**Comment by enoch85** [comment]
Anyway, this can be merged, it improves the output with less errors. :+1:

**Pull request merged**
