### PR TITLE
fix opacity & shading of several icons

### PR DESCRIPTION
**Pull request by jancborchardt**
Yeah I know @colmoneill maybe CSS preprocessing wouldn’t be such a bad idea. ;)

Please review @wurstchristoph @irgendwie @zinks- @Gomez

### CODE REVIEW

**Comment by zinks-** [comment]
Looks very nice, but this just struck me : why do we keep the 'delete' icon always visible and not the star ?

**Comment by irgendwie** [comment]
Looks good! :+1:

**Comment by jancborchardt** [comment]
@zinks- because the star icon is also an indicator and would otherwise only distinguish itself by color – not good for colorblind people (or also for everyone, because you need to actually look at the icon instead of only glancing). On top of that, delete is more often used than favoriting, and it needs to be usable on touchscreens – hence always shown instead of only on hover. Starring however suffices when only available for the currently active mail.

**Comment by jancborchardt** [comment]
Only CSS –> not covered by tests –> merge. :)

**Pull request merged**
