### PR TITLE
remove double encoding

### PR DESCRIPTION
**Pull request by wurstchristoph**
same as https://github.com/owncloud/mail/pull/431

@LukasReschke are those parameters double encoded as well?

### CODE REVIEW

**Comment by LukasReschke** [comment]
Confirmation for @jancborchardt: This is cool :+1:

**Comment by jancborchardt** [comment]
Nice. What about the failing tests @wurstchristoph?

**Comment by LukasReschke** [comment]
These are unrelated and caused by our config – I guess.

**Comment by jancborchardt** [comment]
Thank you again @wurstchristoph :) great contributions

**Pull request merged**
