### PR TITLE
Style empty content messages

### PR DESCRIPTION
**Pull request by jancborchardt**
Better design for:
* initial mail account connection
* empty mail folders
* no search results

Only thing left to do: Hide `#app-navigation` and `#app-navigation-toggle` on first time setup. But only when no account is configured yet. Please help @DeepDiver1975

### CODE REVIEW

**Comment by jancborchardt** [comment]
Ready for review @Xenopathic @zinks- @Gomez

**Comment by jancborchardt** [comment]
Oi, we need a review here :) @clementhk @irgendwie @Henni and the others

**Comment by Xenopathic** [comment]
When searching for something, there's a couple of things that look off.

1) The text in the search box is too close to the search icon
2) The currently loaded message remains visible, with 'No search results for foobar' visible where the message list would be. I think the currently visible message should disappear...

Also, with the 'no mails' empty folder view, the 'Check messages' button looks out of place. Perhaps it'd be better suited to the sidebar?

**Comment by jancborchardt** [comment]
> 1) The text in the search box is too close to the search icon

Looks fine for me. Can you supply a screenshot? If anything though that’s a core issue.

> 2) The currently loaded message remains visible, with 'No search results for foobar' visible where the message list would be. I think the currently visible message should disappear...

Hm, not sure about that. I actually think it’s good that the current message still stays because it leaves you with some anchor. What do you think @wurstchristoph @DeepDiver1975 @irgendwie?

> Also, with the 'no mails' empty folder view, the 'Check messages' button looks out of place. Perhaps it'd be better suited to the sidebar?

I’d prefer for now if it stays where it normally is already. Hopefully it just goes away with pull to refresh #104 ;)

**Comment by jancborchardt** [comment]
Merging for now, any improvements we can do later.

**Pull request merged**
