### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Gomez**
How to reset info

### CODE REVIEW

**Comment by jancborchardt** [comment]
Can you put it below as the second point of »Developer setup info«? More related to that. :) And by now you can only install the mail app by also doing the dev setup.

**Comment by Gomez** [comment]
Right. done.

**Comment by DeepDiver1975** [comment]
:squash: :please:

**Comment by Gomez** [comment]
fight against github editor gone.

**Comment by jancborchardt** [comment]
:+1: thanks! :)

**Pull request merged**
