### PR TITLE
Use account model instead of id

### LINKED ISSUE #1261: Uncaught TypeError: Cannot read property 'currentTarget' of undefined
### Steps to reproduce
1. Press new message button

### Expected behaviour
Everything should work without console output
### Actual behaviour
Everything seems to work but javascript console outputs Uncaught TypeError: Cannot read property 'currentTarget' of undefined
**OwnCloud Mail version:** 0.3

**Mailserver or service:**Outlook

**Transport security - IMAP:** SSL

**Transport security - SMTP:** TLS

**Number of accounts:** 1

**ownCloud Mail version build date:** (only if you are using a Nightly Build)

### Server configuration
**Operating system**: Ubuntu 14.04

**Web server:** Apache

**Database:** MariaDB

**PHP version:**  5.5.9-1ubuntu4.14

**ownCloud version:** ownCloud 9.0 pre alpha (git)

**Updated from an older ownCloud or fresh install:**
Fresh
**List of activated apps:**
  - comments: 0.1
  - dav: 0.1.4
  - files: 1.4.2
  - files_external: 0.5.2
  - files_sharing: 0.9.0
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - mail: 0.3.1
  - provisioning_api: 0.4.1
  - systemtags: 0.2

**The content of config/config.php:**

<?php
$CONFIG = array (
  'instanceid' => 'oc1bpjvralzl',
  'trusted_domains' => 
  array (
    0 => '46.101.176.116',
    1 => 'erikpellikka.com',
  ),
  'datadirectory' => '/var/www/html/owncloud/data',
  'dbtype' => 'mysql',
  'version' => '9.0.0.9',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_admin',
  'logtimezone' => 'UTC',
  'installed' => true,
  'loglevel' => 0,
  'mail_from_address' => 'erik',
  'mail_smtpmode' => 'php',
  'mail_domain' => 'erikpellikka.com',
  'debug' => true,
  'theme' => '',
  'maintenance' => false,
  'app.mail.imaplog.enabled' => true

);

### Client configuration
**Browser:** Chrome

**Operating system:** Windows 10

#### Web server error log
```
Insert your webserver log here
```
[Wed Feb 03 07:15:49.242171 2016] [:error] [pid 16277] [client 37.16.101.93:2656] PHP Fatal error:  require_once(): Failed opening required '/var/www/html/owncloud/lib/private/l10n.php' (include_path='/var/www/html/owncloud/3rdparty/pear/console_getopt:/var/www/html/owncloud/3rdparty/pear/pear_exception:/var/www/html/owncloud/3rdparty/pear/pear-core-minimal/src:/var/www/html/owncloud/3rdparty/pear/archive_tar:/var/www/html/owncloud/3rdparty/phpseclib/phpseclib/phpseclib:/var/www/html/owncloud/lib/private:/var/www/html/owncloud/config:/var/www/html/owncloud/3rdparty:/var/www/html/owncloud/apps:.:/usr/share/php:/usr/share/pear:/var/www/html/owncloud') in /var/www/html/owncloud/lib/autoloader.php on line 183
[Wed Feb 03 07:32:54.871944 2016] [:error] [pid 18258] [client 82.211.60.216:20345] script '/usr/share/phpmyadmin/main.php' not found or unable to stat

#### ownCloud log (data/owncloud.log)
{"reqId":"WC1DVha3zo81BuS58MmN","remoteAddr":"37.16.101.93","app":"mail","message":"loading messages 0 to 20 of folder <SU5CT1g=>","level":0,"time":"2016-02-03T13:46:08+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/mail\/accounts\/2\/folders\/SU5CT1g%3D\/messages?from=0&to=20&filter="}
{"reqId":"YI30kbylDCIcabeHWjjL","remoteAddr":"37.16.101.93","app":"mail","message":"loading messages 0 to 20 of folder <SU5CT1g=>","level":0,"time":"2016-02-03T14:09:02+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/mail\/accounts\/2\/folders\/SU5CT1g%3D\/messages?from=0&to=20&filter="}
{"reqId":"jOzd3mif32LQMkqJW6OQ","remoteAddr":"37.16.101.93","app":"core","message":"No update found at the ownCloud appstore for app 166048","level":0,"time":"2016-02-03T14:10:00+00:00","method":"GET","url":"\/owncloud\/index.php\/settings\/apps\/list?category=enabled&includeUpdateInfo=1"}
{"reqId":"iDLaFI\/cqb6VwjNQDnSC","remoteAddr":"37.16.101.93","app":"DeleteOrphanedSharesJob","message":"0 orphaned share(s) deleted","level":0,"time":"2016-02-03T14:10:39+00:00","method":"GET","url":"\/owncloud\/cron.php"}
{"reqId":"F6WEX1UZv8qxPdrkfjXt","remoteAddr":"37.16.101.93","app":"mail","message":"loading messages 0 to 20 of folder <SU5CT1g=>","level":0,"time":"2016-02-03T14:10:46+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/mail\/accounts\/2\/folders\/SU5CT1g%3D\/messages?from=0&to=20&filter="}

#### Horde log (data/horde.log)
------------------------------
>> Wed, 03 Feb 2016 14:18:28 +0000
>> Connection to: imap://imap-mail.outlook.com:993/
>> Server connection took 0.1257 seconds.
S: * OK Outlook.com IMAP4rev1 server version 17.4.0.0 ready (DUB451-IMAP172)
C: 1 CAPABILITY
S: * CAPABILITY IMAP4rev1 CHILDREN ID NAMESPACE UIDPLUS UNSELECT AUTH=PLAIN AUTH=XOAUTH2 SASL-IR
S: 1 OK CAPABILITY completed
>> Command 1 took 0.1298 seconds.
C: 2 AUTHENTICATE PLAIN [INITIAL CLIENT RESPONSE (username: erikpellikka@outlook.com)]
S: * CAPABILITY IMAP4rev1 CHILDREN ID NAMESPACE UIDPLUS UNSELECT
S: 2 OK erik@pellikka.org authenticated successfully
>> Command 2 took 1.374 seconds.
C: 3 LIST "" *
S: * LIST (\HasNoChildren) "/" "Inbox"
S: * LIST (\HasNoChildren \Trash) "/" "Deleted"
S: * LIST (\HasNoChildren \Sent) "/" "Sent"
S: * LIST (\HasNoChildren \Drafts) "/" "Drafts"
S: * LIST (\HasNoChildren \Junk) "/" "Junk"
S: * LIST (\HasChildren) "/" "Folder"
S: * LIST (\HasChildren) "/" "Folder/Subfolder"
S: * LIST (\HasNoChildren) "/" "Folder/Subfolder/Sub-sub-folder"
S: 3 OK LIST completed
>> Command 3 took 0.4194 seconds.
C: 4 STATUS INBOX (MESSAGES RECENT UIDNEXT UIDVALIDITY UNSEEN)
C: 5 STATUS Drafts (MESSAGES RECENT UIDNEXT UIDVALIDITY UNSEEN)
C: 6 STATUS Sent (MESSAGES RECENT UIDNEXT UIDVALIDITY UNSEEN)
C: 7 STATUS Junk (MESSAGES RECENT UIDNEXT UIDVALIDITY UNSEEN)
C: 8 STATUS Deleted (MESSAGES RECENT UIDNEXT UIDVALIDITY UNSEEN)
C: 9 STATUS Folder (MESSAGES RECENT UIDNEXT UIDVALIDITY UNSEEN)
C: 10 STATUS Folder/Subfolder (MESSAGES RECENT UIDNEXT UIDVALIDITY UNSEEN)
C: 11 STATUS Folder/Subfolder/Sub-sub-folder (MESSAGES RECENT UIDNEXT UIDVALIDITY UNSEEN)
S: * STATUS "INBOX" (MESSAGES 1 RECENT 0 UIDNEXT 100014 UIDVALIDITY 97262432 UNSEEN 0)
S: 4 OK STATUS completed
>> Command 4 took 0.4394 seconds.
S: * STATUS "Drafts" (MESSAGES 1 RECENT 0 UIDNEXT 100002 UIDVALIDITY 97262432 UNSEEN 0)
S: 5 OK STATUS completed
>> Command 5 took 0.729 seconds.
S: * STATUS "Sent" (MESSAGES 0 RECENT 0 UIDNEXT 100001 UIDVALIDITY 97262432 UNSEEN 0)
S: 6 OK STATUS completed
>> Command 6 took 1.0202 seconds.
S: * STATUS "Junk" (MESSAGES 0 RECENT 0 UIDNEXT 100001 UIDVALIDITY 97262433 UNSEEN 0)
S: 7 OK STATUS completed
>> Command 7 took 1.3077 seconds.
S: * STATUS "Deleted" (MESSAGES 0 RECENT 0 UIDNEXT 100001 UIDVALIDITY 97262433 UNSEEN 0)
S: 8 OK STATUS completed
>> Command 8 took 1.5978 seconds.
S: * STATUS "Folder" (MESSAGES 0 RECENT 0 UIDNEXT 100001 UIDVALIDITY 97262433 UNSEEN 0)
S: 9 OK STATUS completed
>> Command 9 took 1.8898 seconds.
S: * STATUS "Folder/Subfolder" (MESSAGES 1 RECENT 0 UIDNEXT 100029 UIDVALIDITY 97262434 UNSEEN 0)
S: 10 OK STATUS completed
>> Command 10 took 2.185 seconds.
S: * STATUS "Folder/Subfolder/Sub-sub-folder" (MESSAGES 2 RECENT 0 UIDNEXT 100027 UIDVALIDITY 97262434 UNSEEN 1)
S: 11 OK STATUS completed
>> Command 11 took 2.4748 seconds.
C: 12 STATUS INBOX (MESSAGES RECENT UIDNEXT UIDVALIDITY UNSEEN)
S: * STATUS "INBOX" (MESSAGES 1 RECENT 0 UIDNEXT 100014 UIDVALIDITY 97262432 UNSEEN 0)
S: 12 OK STATUS completed
>> Command 12 took 0.1292 seconds.
C: 13 LOGOUT
S: * BYE Logout requested
S: 13 OK LOGOUT completed
>> Command 13 took 0.0299 seconds.
------------------------------
>> Wed, 03 Feb 2016 14:18:33 +0000
>> Connection to: imap://imap-mail.outlook.com:993/
------------------------------
>> Wed, 03 Feb 2016 14:18:33 +0000
>> Connection to: imap://imap-mail.outlook.com:993/
>> Server connection took 0.1244 seconds.
S: * OK Outlook.com IMAP4rev1 server version 17.4.0.0 ready (DUB451-IMAP101)
C: 1 CAPABILITY
>> Server connection took 0.1352 seconds.
S: * CAPABILITY IMAP4rev1 CHILDREN ID NAMESPACE UIDPLUS UNSELECT AUTH=PLAIN AUTH=XOAUTH2 SASL-IR
S: * OK Outlook.com IMAP4rev1 server version 17.4.0.0 ready (DUB451-IMAP129)
C: 1 CAPABILITY
S: 1 OK CAPABILITY completed
>> Command 1 took 0.1281 seconds.
C: 2 AUTHENTICATE PLAIN [INITIAL CLIENT RESPONSE (username: erikpellikka@outlook.com)]
S: * CAPABILITY IMAP4rev1 CHILDREN ID NAMESPACE UIDPLUS UNSELECT AUTH=PLAIN AUTH=XOAUTH2 SASL-IR
S: 1 OK CAPABILITY completed
>> Command 1 took 0.1368 seconds.
C: 2 AUTHENTICATE PLAIN [INITIAL CLIENT RESPONSE (username: erikpellikka@outlook.com)]
S: * CAPABILITY IMAP4rev1 CHILDREN ID NAMESPACE UIDPLUS UNSELECT
S: 2 OK erik@pellikka.org authenticated successfully
>> Command 2 took 1.1217 seconds.
C: 3 SELECT INBOX
S: * CAPABILITY IMAP4rev1 CHILDREN ID NAMESPACE UIDPLUS UNSELECT
S: 2 OK erik@pellikka.org authenticated successfully
>> Command 2 took 1.1909 seconds.
C: 3 EXAMINE INBOX
S: * FLAGS (\Answered \Flagged \Deleted \Seen \Draft)
S: * 1 EXISTS
S: * 0 RECENT
S: * OK [UIDVALIDITY 97262432] UIDs valid
S: * OK [UIDNEXT 100014] Predicted next UID
S: * OK [PERMANENTFLAGS (\Answered \Flagged \Deleted \Seen \Draft)] Limited
S: 3 OK [READ-WRITE] SELECT completed.
>> Command 3 took 0.5678 seconds.
C: 4 UID STORE 100007 +FLAGS \seen
S: * FLAGS (\Answered \Flagged \Deleted \Seen \Draft)
S: * 1 EXISTS
S: * 0 RECENT
S: * OK [UIDVALIDITY 97262432] UIDs valid
S: * OK [UIDNEXT 100014] Predicted next UID
S: * OK [PERMANENTFLAGS (\Answered \Flagged \Deleted \Seen \Draft)] Limited
S: 3 OK [READ-ONLY] EXAMINE completed.
>> Command 3 took 0.5748 seconds.
C: 4 UID SEARCH UNDELETED
S: * 1 FETCH (FLAGS (\Seen) UID 100007)
S: 4 OK STORE completed
>> Command 4 took 0.4279 seconds.
C: 5 LOGOUT
S: * SEARCH 100007
S: 4 OK SEARCH Completed
>> Command 4 took 0.4376 seconds.
C: 5 UID FETCH 100007 (INTERNALDATE ENVELOPE)
S: * BYE Logout requested
S: 5 OK LOGOUT completed
>> Command 5 took 0.3142 seconds.
S: * 1 FETCH (UID 100007 INTERNALDATE " 3-Feb-2016 13:38:59 +0000" ENVELOPE ("Wed, 3 Feb 2016 15:38:57 +0200" "testing" (("Erik Pellikka" NIL "pellikkaerik" "gmail.com")) (("Erik Pellikka" NIL "pellikkaerik" "gmail.com")) (("Erik Pellikka" NIL "pellikkaerik" "gmail.com")) ((NIL NIL "erikpellikka" "outlook.com")) NIL NIL NIL "<CAL2GqhSRudyG2x0XZ+_Jb7eUZoCw6XATA-9ZM4BiJ_ej-XMXcw@mail.gmail.com>"))
S: * 1 FETCH (FLAGS (\Seen) UID 100007)
S: 5 OK FETCH Completed
>> Command 5 took 0.6251 seconds.
C: 6 UID FETCH 100007 (ENVELOPE FLAGS RFC822.SIZE INTERNALDATE BODYSTRUCTURE BODY.PEEK[HEADER.FIELDS (IMPORTANCE LIST-POST X-PRIORITY CONTENT-TYPE)])
S: * 1 FETCH (UID 100007 RFC822.SIZE 3389 FLAGS (\Seen) INTERNALDATE " 3-Feb-2016 13:38:59 +0000" ENVELOPE ("Wed, 3 Feb 2016 15:38:57 +0200" "testing" (("Erik Pellikka" NIL "pellikkaerik" "gmail.com")) (("Erik Pellikka" NIL "pellikkaerik" "gmail.com")) (("Erik Pellikka" NIL "pellikkaerik" "gmail.com")) ((NIL NIL "erikpellikka" "outlook.com")) NIL NIL NIL "<CAL2GqhSRudyG2x0XZ+_Jb7eUZoCw6XATA-9ZM4BiJ_ej-XMXcw@mail.gmail.com>") BODYSTRUCTURE (("TEXT" "plain" ("charset" "UTF-8") NIL NIL "7BIT" 9 1 NIL NIL NIL NIL)("TEXT" "html" ("charset" "UTF-8") NIL NIL "7BIT" 30 1 NIL NIL NIL NIL) "alternative" ("boundary" "001a114b75e8685643052addbdf3") NIL NIL NIL) BODY[HEADER.FIELDS ("IMPORTANCE" "LIST-POST" "X-PRIORITY" "CONTENT-TYPE")] {80}
S: [LITERAL DATA: 80 bytes]
S: )
S: 6 OK FETCH Completed
>> Command 6 took 0.5911 seconds.
C: 7 LOGOUT
S: * BYE Logout requested
S: 7 OK LOGOUT completed
>> Command 7 took 0.3145 seconds.

#### Browser log

Deprecation warning: tipsy is deprecated. Use tooltip instead.
ui.js:405 Uncaught TypeError: Cannot read property 'currentTarget' of undefined

### LINKED ISSUE #1314: Backbone models
Right now we're using Backbone models only for rendering Marionette collection views. By consistently using models throughout the client, we could lower the complexity of working with related data. 

I had a look at the JavaScript code and identified the following models:
- Account
- Folder
- Messge
- MessageFlag

backbone_models

Using Backbone models has some advantages:
- By using bidirectional association between models it will be easier to work with related data
- Global state variables (e.g. inside the ``state`` module) can be eliminated because all the data is passed when calling a module function or triggering an event.
- We can use [Backbone sync](http://backbonejs.org/#Sync) on those models
  - Might be helpful to use [horde sync](https://github.com/owncloud/mail/pull/763) for folders
- Existing code will be easier to maintain
- It will be easier to implement new features

@owncloud/mail

### PR DESCRIPTION
**Pull request by ChristophWurst**
partially fixes #1314 
fixes #1261

TODO:
- [x] fix ``checkNotification``
- [x] ``TypeError: activeFolder is undefined, navigation-accounts.js:42:4``
- [x] ``TypeError: localAccount is undefined, background.js:92:8``
- [x] ``TypeError: account.get is not a function, ui.js:306:22``
- [x] ``TypeError: account.get is not a function, cache.js:20:24``
- [x] ``TypeError: data is undefined, ui.js:254:7 when sending a message``

### CODE REVIEW

**Comment by ChristophWurst** [comment]
rebased, tested and fixed all the bugs I could find. #1297 is the only error left, but it's unrelated to this PR.

@owncloud/mail please test and review this. Thanks.

**Comment by clementhk** [comment]
All changes (as well as a lot of new TODOs) look correct.

**Comment by ChristophWurst** [comment]
> All changes (as well as a lot of new TODOs) look correct.

Thank you for reviewing. Did you run the app on this branch?

**Comment by ChristophWurst** [comment]
@Gomez @DeepDiver1975 review please :-)

**Comment by Gomez** [comment]
On a single email setting i get this:
```
TypeError: Marionette.ItemView is undefined
Stack trace:
@http://localhost:8080/apps/mail/js/views/setup.js:21:2
newContext/context.execCb@http://localhost:8080/apps/mail/js/vendor/requirejs/require.js?v=eb53e42ae6f5983a86c8b9fe7cab7dd9:1690:24
```

owncloud 9.0.0

**Comment by Gomez** [comment]
```
TypeError: e.toLowerCase is not a function
[5]</matching.dictionary_match()
 jquery.min.js:18
[5]</matching.omnimatch()
 jquery.min.js:18
[4]</zxcvbn()
 jquery.min.js:15
.onShowMessage()
 messagecontent.js:62
triggerEvents()
 backbone.js:369
triggerApi()
 backbone.js:356
eventsApi()
 backbone.js:155
Events.trigger()
 backbone.js:346
loadMessage/<.onSuccess()
 ui.js:253
x.Callbacks/c()
 jquery.min.js:4
x.Callbacks/p.fireWith()
 jquery.min.js:4
k()
 jquery.min.js:6
.send/r()
```

**Comment by Gomez** [comment]
call

**Comment by Gomez** [comment]
Looks good! No error found.

**Pull request merged**
