### PR TITLE
Better dev setup

### PR DESCRIPTION
**Pull request by Gomez**
Much faster and easier now.

@ChristophWurst Please try
@enoch85 Would be cool if you could test on new vm. Just follow the Readme.

### CODE REVIEW

**Comment by enoch85** [comment]
@Gomez The install-ubuntu.sh fails with this:

```
user@owncloud:/var/www/owncloud/apps/mail# bash install_ubuntu.sh
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 node : Conflicts: nodejs-legacy but 0.10.25~dfsg2-2ubuntu1 is to be installed
 nodejs-legacy : Conflicts: node but 0.3.2-7.4 is to be installed
E: Unable to correct problems, you have held broken packages.
#!/usr/bin/env php
All settings correct for using Composer
Downloading...

Composer successfully installed to: /var/www/owncloud/apps/mail/composer.phar
Use it: php composer.phar
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them.
  - Installing ezyang/htmlpurifier (v4.6.0)
    Downloading: 100%

  - Installing kwi/urllinker (dev-default b5e097f)
    Cloning b5e097f03963454b4e8f32581265c8e57c3409e6
    Failed to download kwi/urllinker from source: Failed to execute hg clone 'https://bitbucket.org/kwi/urllinker' '/var/www/owncloud/apps/mail/vendor/kwi/urllinker'

sh: 1: hg: not found

    Now trying to download from dist
  - Installing kwi/urllinker (dev-default b5e097f)
    Downloading: 100%

  - Installing pear-pear.horde.org/horde_translation (2.2.0)
    Downloading: 100%
  - Installing pear-pear.horde.org/horde_util (2.5.6)
    Downloading: 100%
  - Installing pear-pear.horde.org/horde_nls (2.0.5)
    Downloading: 100%
  - Installing pear-pear.horde.org/horde_exception (2.0.6)
    Downloading: 100%
  - Installing pear-pear.horde.org/horde_date (2.1.1)
    Downloading: 100%
  - Installing pear-pear.horde.org/horde_stream_filter (2.0.3)
    Downloading: 100%
  - Installing pear-pear.horde.org/horde_stream (1.6.2)
    Downloading: 100%
  - Installing pear-pear.horde.org/horde_socket_client (2.0.0)
    Downloading: 100%
  - Installing pear-pear.horde.org/horde_stream_wrapper (2.1.2)
    Downloading: 100%
  - Installing pear-pear.horde.org/horde_support (2.1.4)
    Downloading: 100%
  - Installing pear-pear.horde.org/horde_crypt_blowfish (1.1.0)
    Downloading: 100%
  - Installing pear-pear.horde.org/horde_secret (2.0.4)
    Downloading: 100%
  - Installing pear-pear.horde.org/horde_text_flowed (2.0.2)
    Downloading: 100%
  - Installing pear-pear.horde.org/horde_mime (2.9.1)
    Downloading: 100%
  - Installing pear-pear.horde.org/horde_idna (1.0.3)
    Downloading: 100%
  - Installing pear-pear.horde.org/horde_mail (2.6.2)
    Downloading: 100%
  - Installing pear-pear.horde.org/horde_listheaders (1.2.2)
    Downloading: 100%
  - Installing pear-pear.horde.org/horde_imap_client (2.29.1)
    Downloading: 100%
  - Installing pear-pear.horde.org/horde_smtp (1.9.1)
    Downloading: 100%
  - Installing pear-pear.horde.org/horde_text_filter (2.3.2)
    Downloading: 100%
Generating autoload files
> npm install
sh: 1: npm: not found
Script npm install handling the post-install-cmd event returned with an error



  [RuntimeException]
  Error Output: sh: 1: npm: not found



install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-plugins] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [--ignore-platform-reqs] [packages1] ... [packagesN]
```

**Comment by enoch85** [comment]
Fixed the nodejs issue, look at the script - comited directly into it. Anyway, issue still persist with npm:

```
user@owncloud:/var/www/owncloud/apps/mail# bash install_ubuntu.sh
Reading package lists... Done
Building dependency tree
Reading state information... Done
nodejs-legacy is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
#!/usr/bin/env php
All settings correct for using Composer
Downloading...

Composer successfully installed to: /var/www/owncloud/apps/mail/composer.phar
Use it: php composer.phar
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them.
Nothing to install or update
Generating autoload files
> npm install
sh: 1: npm: not found
Script npm install handling the post-install-cmd event returned with an error



  [RuntimeException]
  Error Output: sh: 1: npm: not found



install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-plugins] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [--ignore-platform-reqs] [packages1] ... [packagesN]

```

**Comment by Gomez** [comment]
Thanks @enoch85. I just added npm as package. Should now work.

**Comment by ChristophWurst** [comment]
Great! Now it's definitely easier to install all dependencies :+1:

**Comment by enoch85** [comment]
Yes, now it works as it should. :+1:

**Comment by jancborchardt** [comment]
Awesome, good testing and feedback @enoch85 :)

**Comment by jancborchardt** [comment]
@enoch85 join us on IRC in #owncloud-dev and #owncloud-mail btw :)

**Pull request merged**
