### PR TITLE
add Mailvelope link to settings

### PR DESCRIPTION
**Pull request by jancborchardt**
Add link pointing to Mailvelope so people can use encrypted emails. Please review @DeepDiver1975 @toberndo @uggrock

### CODE REVIEW

**Comment by irgendwie** [comment]
Functional :+1:, still it's not very pretty :grin:

**Comment by irgendwie** [comment]
How about adding a little lock icon next to "Add mail account", which shows the information in a tooltip or something? Instead of the plain text under the button?

**Comment by zinks-** [comment]
Works, maybe we can pretty it up later? The account list should be clearly separated from it.
 (but :+1:)

**Comment by DeepDiver1975** [comment]
@jancborchardt rebase please

**Comment by DeepDiver1975** [comment]
rebased

**Comment by DeepDiver1975** [comment]
I'm all in to merge this - we can still style it differently later :+1:

**Comment by jancborchardt** [comment]
Yeah, I also think we can style it up later. Just having an icon with tooltip is too little I think. It’s the settings section after all.

**Pull request merged**
