### PR TITLE
Dropdown selection added for IMAP & SMTP security config

### PR DESCRIPTION
**Pull request by jancborchardt**
@mikelupe I rebased your original pull request https://github.com/owncloud/mail/pull/391 and also fixed the design. :)

@zinks- @PoPoutdoor @DeepDiver1975 @wurstchristoph please review

### CODE REVIEW

**Comment by wurstchristoph** [comment]
great :+1:

**Comment by jancborchardt** [comment]
A big thanks to @mikelupe for his contribution! :) @mikelupe you are also very welcome in our IRC channel #owncloud-mail

**Comment by mikelupe** [comment]
What a coincidence, I was now just about to "unwatch" this thread (as the number of notifications exeeded my level of tolerance:) as I could see it was closed. Thanks for adapting the design! Unfortunately I will not be able to do more additions right now, perhaps in future. Thanks for the short "ride", my first contribution to open source ever ;)

**Comment by clementhk** [comment]
Congrats and thanks, @mikelupe :)

**Comment by jancborchardt** [comment]
@mikelupe that’s awesome to hear! Feeling honored we are the first open source project you contributed to! :)

Sorry for the long wait though – we’re about to work lots more on ownCloud Mail. You’re welcome back any time! :rocket:

**Comment by mikelupe** [comment]
No no, _I_ felt honored that you guys supported me that well, as I'm not really a coder anymore since a quite long time :) Looking forward for this app and many other great things you create!

**Pull request merged**
