### PR TITLE
Add target="_blank" to all html links

### LINKED ISSUE #1041: Links from HTML emails open in message iFrame
Instead, all links from inside emails should be force set to `target="_blank"` if possible. @LukasReschke @irgendwie @ChristophWurst is that possible?

### PR DESCRIPTION
**Pull request by jakobsack**
Fixes #1041

### CODE REVIEW

**Comment by enoch85** [comment]
@jakobsack Is this ready for review?

**Comment by jakobsack** [comment]
@enoch85 Yes, please go ahead

@ChristophWurst @gomez @jancborchardt could you please test this as well?

**Comment by ChristophWurst** [comment]
@jakobsack please use rebase to keep your PR up to date with master instead of merging master into your feature branch. thanks

**Comment by ChristophWurst** [comment]
Does anybody have an explanation why this is needed at all? Didn't we already have this feature? :confused:

**Comment by jakobsack** [comment]
@ChristophWurst it got implemented in b6a593b28769b6f3e76c972ddaef351e3a829beb, got changed in 6bcda3fe7022c79d5ef734bda148304c0773822c. Apparently this feature of htmlpurifier does not work as expected or we are using it the wrong way :confused:

**Comment by ChristophWurst** [comment]
> @ChristophWurst it got implemented in b6a593b, got changed in 6bcda3f. Apparently this feature of htmlpurifier does not work as expected or we are using it the wrong way :confused:

ah, thanks for the clarification :)

**Comment by jancborchardt** [comment]
Please review @enoch85 @zinks- @PoPoutdoor :)

**Comment by jancborchardt** [comment]
Works for some, not for others. For example an account creation email confirm link for https://ghost.io (try it yourself)

**Comment by jakobsack** [comment]
@jancborchardt can't confirm, please send me the mail (as *.eml or whatever) that causes the error on your installation. Are you sure you were on the correct branch?

**Comment by jancborchardt** [comment]
Hm, works now, must’ve been some cache of the mail I guess cause I had it open before.

**Pull request merged**
