### PR TITLE
Make blocked images transparent as asked by Jan

### PR DESCRIPTION
**Pull request by jakobsack**
This replaces the current blue "blocked image" with a 1px transparent version.

### CODE REVIEW

**Comment by Gomez** [comment]
Hmm, i don't like the transparent version. There should be a little difference, so i can see the place of the missing image?
A little bit grey? 
@jancborchardt

**Comment by jancborchardt** [comment]
Now after using the image blocking for some time, it’s clear that we need to free the space which was occupied by the pictures. That is, there should be _no_ placeholder, with 0 width/height. Otherwise there’s a whole lot of useless space in most emails, and the layout is not really broken by just removing it.

**Comment by jakobsack** [comment]
@jancborchardt @Gomez @ChristophWurst  Please have a look at the updated version, it hides the images ("display: none") and shows them when requested.

**Comment by jancborchardt** [comment]
@jakobsack nice, much better! Thanks

**Pull request merged**
